// AuditEvent: append-only record of significant actions taken in the system.
// Backs s.206 (Excise Act, 2001) daily records expectations: every meaningful
// change is captured with actor, timestamp, and payload.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stillhouse/v1/audit.proto

package stillhousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditAction int32

const (
	AuditAction_AUDIT_ACTION_UNSPECIFIED AuditAction = 0
	AuditAction_AUDIT_ACTION_CREATE      AuditAction = 1
	AuditAction_AUDIT_ACTION_UPDATE      AuditAction = 2
	AuditAction_AUDIT_ACTION_DELETE      AuditAction = 3
	AuditAction_AUDIT_ACTION_SIGN        AuditAction = 4
	AuditAction_AUDIT_ACTION_LOGIN       AuditAction = 5
	AuditAction_AUDIT_ACTION_LOGOUT      AuditAction = 6
)

// Enum value maps for AuditAction.
var (
	AuditAction_name = map[int32]string{
		0: "AUDIT_ACTION_UNSPECIFIED",
		1: "AUDIT_ACTION_CREATE",
		2: "AUDIT_ACTION_UPDATE",
		3: "AUDIT_ACTION_DELETE",
		4: "AUDIT_ACTION_SIGN",
		5: "AUDIT_ACTION_LOGIN",
		6: "AUDIT_ACTION_LOGOUT",
	}
	AuditAction_value = map[string]int32{
		"AUDIT_ACTION_UNSPECIFIED": 0,
		"AUDIT_ACTION_CREATE":      1,
		"AUDIT_ACTION_UPDATE":      2,
		"AUDIT_ACTION_DELETE":      3,
		"AUDIT_ACTION_SIGN":        4,
		"AUDIT_ACTION_LOGIN":       5,
		"AUDIT_ACTION_LOGOUT":      6,
	}
)

func (x AuditAction) Enum() *AuditAction {
	p := new(AuditAction)
	*p = x
	return p
}

func (x AuditAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditAction) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_audit_proto_enumTypes[0].Descriptor()
}

func (AuditAction) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_audit_proto_enumTypes[0]
}

func (x AuditAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditAction.Descriptor instead.
func (AuditAction) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_audit_proto_rawDescGZIP(), []int{0}
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // nullable in DB; empty string here when system-generated
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // e.g., "tenant", "user", "bulk_movement"
	EntityId      string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        AuditAction            `protobuf:"varint,6,opt,name=action,proto3,enum=stillhouse.v1.AuditAction" json:"action,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON-encoded change payload (before/after where applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_stillhouse_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditEvent) GetAction() AuditAction {
	if x != nil {
		return x.Action
	}
	return AuditAction_AUDIT_ACTION_UNSPECIFIED
}

func (x *AuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuditEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

var File_stillhouse_v1_audit_proto protoreflect.FileDescriptor

const file_stillhouse_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x19stillhouse/v1/audit.proto\x12\rstillhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x122\n" +
	"\x06action\x18\x06 \x01(\x0e2\x1a.stillhouse.v1.AuditActionR\x06action\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12!\n" +
	"\fpayload_json\x18\b \x01(\fR\vpayloadJson*\xbe\x01\n" +
	"\vAuditAction\x12\x1c\n" +
	"\x18AUDIT_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AUDIT_ACTION_CREATE\x10\x01\x12\x17\n" +
	"\x13AUDIT_ACTION_UPDATE\x10\x02\x12\x17\n" +
	"\x13AUDIT_ACTION_DELETE\x10\x03\x12\x15\n" +
	"\x11AUDIT_ACTION_SIGN\x10\x04\x12\x16\n" +
	"\x12AUDIT_ACTION_LOGIN\x10\x05\x12\x17\n" +
	"\x13AUDIT_ACTION_LOGOUT\x10\x06B\xce\x01\n" +
	"\x11com.stillhouse.v1B\n" +
	"AuditProtoP\x01ZXgithub.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1;stillhousev1\xa2\x02\x03SXX\xaa\x02\rStillhouse.V1\xca\x02\rStillhouse\\V1\xe2\x02\x19Stillhouse\\V1\\GPBMetadata\xea\x02\x0eStillhouse::V1b\x06proto3"

var (
	file_stillhouse_v1_audit_proto_rawDescOnce sync.Once
	file_stillhouse_v1_audit_proto_rawDescData []byte
)

func file_stillhouse_v1_audit_proto_rawDescGZIP() []byte {
	file_stillhouse_v1_audit_proto_rawDescOnce.Do(func() {
		file_stillhouse_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillhouse_v1_audit_proto_rawDesc), len(file_stillhouse_v1_audit_proto_rawDesc)))
	})
	return file_stillhouse_v1_audit_proto_rawDescData
}

var file_stillhouse_v1_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stillhouse_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stillhouse_v1_audit_proto_goTypes = []any{
	(AuditAction)(0),              // 0: stillhouse.v1.AuditAction
	(*AuditEvent)(nil),            // 1: stillhouse.v1.AuditEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_stillhouse_v1_audit_proto_depIdxs = []int32{
	0, // 0: stillhouse.v1.AuditEvent.action:type_name -> stillhouse.v1.AuditAction
	2, // 1: stillhouse.v1.AuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stillhouse_v1_audit_proto_init() }
func file_stillhouse_v1_audit_proto_init() {
	if File_stillhouse_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillhouse_v1_audit_proto_rawDesc), len(file_stillhouse_v1_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stillhouse_v1_audit_proto_goTypes,
		DependencyIndexes: file_stillhouse_v1_audit_proto_depIdxs,
		EnumInfos:         file_stillhouse_v1_audit_proto_enumTypes,
		MessageInfos:      file_stillhouse_v1_audit_proto_msgTypes,
	}.Build()
	File_stillhouse_v1_audit_proto = out.File
	file_stillhouse_v1_audit_proto_goTypes = nil
	file_stillhouse_v1_audit_proto_depIdxs = nil
}
