// CRA Form B266 (Excise Duty Return — Spirits Licensee). The values in
// B266Report are what you transcribe into the My Business Account / Web
// Form Filer return for the period.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stillhouse/v1/b266.proto

package stillhousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type B266Status int32

const (
	B266Status_B266_STATUS_UNSPECIFIED B266Status = 0
	B266Status_B266_STATUS_DRAFT       B266Status = 1
	B266Status_B266_STATUS_SUBMITTED   B266Status = 2
)

// Enum value maps for B266Status.
var (
	B266Status_name = map[int32]string{
		0: "B266_STATUS_UNSPECIFIED",
		1: "B266_STATUS_DRAFT",
		2: "B266_STATUS_SUBMITTED",
	}
	B266Status_value = map[string]int32{
		"B266_STATUS_UNSPECIFIED": 0,
		"B266_STATUS_DRAFT":       1,
		"B266_STATUS_SUBMITTED":   2,
	}
)

func (x B266Status) Enum() *B266Status {
	p := new(B266Status)
	*p = x
	return p
}

func (x B266Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (B266Status) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_b266_proto_enumTypes[0].Descriptor()
}

func (B266Status) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_b266_proto_enumTypes[0]
}

func (x B266Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use B266Status.Descriptor instead.
func (B266Status) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{0}
}

type B266Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PeriodStart   string                 `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // ISO date
	PeriodEnd     string                 `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Status        B266Status             `protobuf:"varint,4,opt,name=status,proto3,enum=stillhouse.v1.B266Status" json:"status,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	SubmittedBy   string                 `protobuf:"bytes,6,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *B266Period) Reset() {
	*x = B266Period{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B266Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B266Period) ProtoMessage() {}

func (x *B266Period) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B266Period.ProtoReflect.Descriptor instead.
func (*B266Period) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{0}
}

func (x *B266Period) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *B266Period) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *B266Period) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *B266Period) GetStatus() B266Status {
	if x != nil {
		return x.Status
	}
	return B266Status_B266_STATUS_UNSPECIFIED
}

func (x *B266Period) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *B266Period) GetSubmittedBy() string {
	if x != nil {
		return x.SubmittedBy
	}
	return ""
}

func (x *B266Period) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *B266Period) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *B266Period) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// B266Report mirrors the lines you'd enter on the CRA form. All amounts
// in LAA (litres absolute alcohol) unless otherwise noted; duty in CAD.
type B266Report struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart string                 `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd   string                 `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	// Bulk spirits section (Form lines 1-9 roughly).
	BulkOpeningLaa                float64 `protobuf:"fixed64,10,opt,name=bulk_opening_laa,json=bulkOpeningLaa,proto3" json:"bulk_opening_laa,omitempty"`
	BulkProductionLaa             float64 `protobuf:"fixed64,11,opt,name=bulk_production_laa,json=bulkProductionLaa,proto3" json:"bulk_production_laa,omitempty"` // production_gauge movements
	BulkReceivedInBondLaa         float64 `protobuf:"fixed64,12,opt,name=bulk_received_in_bond_laa,json=bulkReceivedInBondLaa,proto3" json:"bulk_received_in_bond_laa,omitempty"`
	BulkBlendInLaa                float64 `protobuf:"fixed64,13,opt,name=bulk_blend_in_laa,json=bulkBlendInLaa,proto3" json:"bulk_blend_in_laa,omitempty"`
	BulkTransferredToPackagingLaa float64 `protobuf:"fixed64,14,opt,name=bulk_transferred_to_packaging_laa,json=bulkTransferredToPackagingLaa,proto3" json:"bulk_transferred_to_packaging_laa,omitempty"`
	BulkTransferredOutInBondLaa   float64 `protobuf:"fixed64,15,opt,name=bulk_transferred_out_in_bond_laa,json=bulkTransferredOutInBondLaa,proto3" json:"bulk_transferred_out_in_bond_laa,omitempty"`
	BulkLossesLaa                 float64 `protobuf:"fixed64,16,opt,name=bulk_losses_laa,json=bulkLossesLaa,proto3" json:"bulk_losses_laa,omitempty"` // evaporation + unaccounted
	BulkDestroyedLaa              float64 `protobuf:"fixed64,17,opt,name=bulk_destroyed_laa,json=bulkDestroyedLaa,proto3" json:"bulk_destroyed_laa,omitempty"`
	BulkClosingLaa                float64 `protobuf:"fixed64,18,opt,name=bulk_closing_laa,json=bulkClosingLaa,proto3" json:"bulk_closing_laa,omitempty"`
	// Stock adopted into Stillhouse during this period — alcohol that was
	// already in the warehouse before the distillery started using the
	// system. It is NOT production, and is already inside bulk_opening_laa;
	// it is reported separately so an adopted balance is never invisible on
	// the return it affects.
	BulkOpeningInventoryAdoptedLaa float64 `protobuf:"fixed64,19,opt,name=bulk_opening_inventory_adopted_laa,json=bulkOpeningInventoryAdoptedLaa,proto3" json:"bulk_opening_inventory_adopted_laa,omitempty"`
	// Packaged spirits section.
	PackagedOpeningLaa             float64 `protobuf:"fixed64,30,opt,name=packaged_opening_laa,json=packagedOpeningLaa,proto3" json:"packaged_opening_laa,omitempty"`
	PackagedPackagedLaa            float64 `protobuf:"fixed64,31,opt,name=packaged_packaged_laa,json=packagedPackagedLaa,proto3" json:"packaged_packaged_laa,omitempty"` // produced by bottling runs
	PackagedPackagedBottles        int32   `protobuf:"varint,32,opt,name=packaged_packaged_bottles,json=packagedPackagedBottles,proto3" json:"packaged_packaged_bottles,omitempty"`
	PackagedRemovedDutyPaidLaa     float64 `protobuf:"fixed64,33,opt,name=packaged_removed_duty_paid_laa,json=packagedRemovedDutyPaidLaa,proto3" json:"packaged_removed_duty_paid_laa,omitempty"`
	PackagedRemovedDutyPaidBottles int32   `protobuf:"varint,34,opt,name=packaged_removed_duty_paid_bottles,json=packagedRemovedDutyPaidBottles,proto3" json:"packaged_removed_duty_paid_bottles,omitempty"`
	PackagedClosingLaa             float64 `protobuf:"fixed64,35,opt,name=packaged_closing_laa,json=packagedClosingLaa,proto3" json:"packaged_closing_laa,omitempty"`
	PackagedClosingBottles         int32   `protobuf:"varint,36,opt,name=packaged_closing_bottles,json=packagedClosingBottles,proto3" json:"packaged_closing_bottles,omitempty"`
	// Alcohol that left bulk for the bottling line but never became a sealed
	// bottle — spillage, what stays in the filler. packaged_packaged_laa
	// counts bottles only, so without this line the packaged section doesn't
	// reconcile with bulk_transferred_to_packaging_laa and the reverse-walked
	// opening balance goes negative.
	PackagedPackagingLossLaa float64 `protobuf:"fixed64,37,opt,name=packaged_packaging_loss_laa,json=packagedPackagingLossLaa,proto3" json:"packaged_packaging_loss_laa,omitempty"`
	// Duty splits by strength band and the two bands are charged in
	// different units, so each is reported with the quantity it is actually
	// charged on. duty_payable_cad is their sum.
	PackagedRemovedOver7Laa      float64 `protobuf:"fixed64,38,opt,name=packaged_removed_over7_laa,json=packagedRemovedOver7Laa,proto3" json:"packaged_removed_over7_laa,omitempty"` // charged per LAA
	PackagedRemovedOver7DutyCad  float64 `protobuf:"fixed64,39,opt,name=packaged_removed_over7_duty_cad,json=packagedRemovedOver7DutyCad,proto3" json:"packaged_removed_over7_duty_cad,omitempty"`
	PackagedRemovedOver7Bottles  int32   `protobuf:"varint,40,opt,name=packaged_removed_over7_bottles,json=packagedRemovedOver7Bottles,proto3" json:"packaged_removed_over7_bottles,omitempty"`
	PackagedRemovedUnder7Litres  float64 `protobuf:"fixed64,41,opt,name=packaged_removed_under7_litres,json=packagedRemovedUnder7Litres,proto3" json:"packaged_removed_under7_litres,omitempty"` // charged per litre of product
	PackagedRemovedUnder7DutyCad float64 `protobuf:"fixed64,42,opt,name=packaged_removed_under7_duty_cad,json=packagedRemovedUnder7DutyCad,proto3" json:"packaged_removed_under7_duty_cad,omitempty"`
	PackagedRemovedUnder7Bottles int32   `protobuf:"varint,43,opt,name=packaged_removed_under7_bottles,json=packagedRemovedUnder7Bottles,proto3" json:"packaged_removed_under7_bottles,omitempty"`
	DutyRatePerLitreUnder7       float64 `protobuf:"fixed64,44,opt,name=duty_rate_per_litre_under7,json=dutyRatePerLitreUnder7,proto3" json:"duty_rate_per_litre_under7,omitempty"`
	// Duty section.
	DutyRatePerLaa float64                `protobuf:"fixed64,50,opt,name=duty_rate_per_laa,json=dutyRatePerLaa,proto3" json:"duty_rate_per_laa,omitempty"` // current rate (CAD/LAA) >7%
	DutyPayableCad float64                `protobuf:"fixed64,51,opt,name=duty_payable_cad,json=dutyPayableCad,proto3" json:"duty_payable_cad,omitempty"`   // sum of removals.duty_amount_cad
	GeneratedAt    *timestamppb.Timestamp `protobuf:"bytes,60,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *B266Report) Reset() {
	*x = B266Report{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *B266Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B266Report) ProtoMessage() {}

func (x *B266Report) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B266Report.ProtoReflect.Descriptor instead.
func (*B266Report) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{1}
}

func (x *B266Report) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *B266Report) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *B266Report) GetBulkOpeningLaa() float64 {
	if x != nil {
		return x.BulkOpeningLaa
	}
	return 0
}

func (x *B266Report) GetBulkProductionLaa() float64 {
	if x != nil {
		return x.BulkProductionLaa
	}
	return 0
}

func (x *B266Report) GetBulkReceivedInBondLaa() float64 {
	if x != nil {
		return x.BulkReceivedInBondLaa
	}
	return 0
}

func (x *B266Report) GetBulkBlendInLaa() float64 {
	if x != nil {
		return x.BulkBlendInLaa
	}
	return 0
}

func (x *B266Report) GetBulkTransferredToPackagingLaa() float64 {
	if x != nil {
		return x.BulkTransferredToPackagingLaa
	}
	return 0
}

func (x *B266Report) GetBulkTransferredOutInBondLaa() float64 {
	if x != nil {
		return x.BulkTransferredOutInBondLaa
	}
	return 0
}

func (x *B266Report) GetBulkLossesLaa() float64 {
	if x != nil {
		return x.BulkLossesLaa
	}
	return 0
}

func (x *B266Report) GetBulkDestroyedLaa() float64 {
	if x != nil {
		return x.BulkDestroyedLaa
	}
	return 0
}

func (x *B266Report) GetBulkClosingLaa() float64 {
	if x != nil {
		return x.BulkClosingLaa
	}
	return 0
}

func (x *B266Report) GetBulkOpeningInventoryAdoptedLaa() float64 {
	if x != nil {
		return x.BulkOpeningInventoryAdoptedLaa
	}
	return 0
}

func (x *B266Report) GetPackagedOpeningLaa() float64 {
	if x != nil {
		return x.PackagedOpeningLaa
	}
	return 0
}

func (x *B266Report) GetPackagedPackagedLaa() float64 {
	if x != nil {
		return x.PackagedPackagedLaa
	}
	return 0
}

func (x *B266Report) GetPackagedPackagedBottles() int32 {
	if x != nil {
		return x.PackagedPackagedBottles
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedDutyPaidLaa() float64 {
	if x != nil {
		return x.PackagedRemovedDutyPaidLaa
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedDutyPaidBottles() int32 {
	if x != nil {
		return x.PackagedRemovedDutyPaidBottles
	}
	return 0
}

func (x *B266Report) GetPackagedClosingLaa() float64 {
	if x != nil {
		return x.PackagedClosingLaa
	}
	return 0
}

func (x *B266Report) GetPackagedClosingBottles() int32 {
	if x != nil {
		return x.PackagedClosingBottles
	}
	return 0
}

func (x *B266Report) GetPackagedPackagingLossLaa() float64 {
	if x != nil {
		return x.PackagedPackagingLossLaa
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedOver7Laa() float64 {
	if x != nil {
		return x.PackagedRemovedOver7Laa
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedOver7DutyCad() float64 {
	if x != nil {
		return x.PackagedRemovedOver7DutyCad
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedOver7Bottles() int32 {
	if x != nil {
		return x.PackagedRemovedOver7Bottles
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedUnder7Litres() float64 {
	if x != nil {
		return x.PackagedRemovedUnder7Litres
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedUnder7DutyCad() float64 {
	if x != nil {
		return x.PackagedRemovedUnder7DutyCad
	}
	return 0
}

func (x *B266Report) GetPackagedRemovedUnder7Bottles() int32 {
	if x != nil {
		return x.PackagedRemovedUnder7Bottles
	}
	return 0
}

func (x *B266Report) GetDutyRatePerLitreUnder7() float64 {
	if x != nil {
		return x.DutyRatePerLitreUnder7
	}
	return 0
}

func (x *B266Report) GetDutyRatePerLaa() float64 {
	if x != nil {
		return x.DutyRatePerLaa
	}
	return 0
}

func (x *B266Report) GetDutyPayableCad() float64 {
	if x != nil {
		return x.DutyPayableCad
	}
	return 0
}

func (x *B266Report) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type GenerateB266Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart   string                 `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // ISO date; required
	PeriodEnd     string                 `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`       // ISO date; required (inclusive)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateB266Request) Reset() {
	*x = GenerateB266Request{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateB266Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateB266Request) ProtoMessage() {}

func (x *GenerateB266Request) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateB266Request.ProtoReflect.Descriptor instead.
func (*GenerateB266Request) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateB266Request) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *GenerateB266Request) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

type GenerateB266Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *B266Period            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Report        *B266Report            `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateB266Response) Reset() {
	*x = GenerateB266Response{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateB266Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateB266Response) ProtoMessage() {}

func (x *GenerateB266Response) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateB266Response.ProtoReflect.Descriptor instead.
func (*GenerateB266Response) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateB266Response) GetPeriod() *B266Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *GenerateB266Response) GetReport() *B266Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type SubmitB266Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodId      string                 `protobuf:"bytes,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitB266Request) Reset() {
	*x = SubmitB266Request{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitB266Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitB266Request) ProtoMessage() {}

func (x *SubmitB266Request) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitB266Request.ProtoReflect.Descriptor instead.
func (*SubmitB266Request) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitB266Request) GetPeriodId() string {
	if x != nil {
		return x.PeriodId
	}
	return ""
}

type SubmitB266Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *B266Period            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Snapshot      *B266Report            `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitB266Response) Reset() {
	*x = SubmitB266Response{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitB266Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitB266Response) ProtoMessage() {}

func (x *SubmitB266Response) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitB266Response.ProtoReflect.Descriptor instead.
func (*SubmitB266Response) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitB266Response) GetPeriod() *B266Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *SubmitB266Response) GetSnapshot() *B266Report {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ListB266PeriodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListB266PeriodsRequest) Reset() {
	*x = ListB266PeriodsRequest{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListB266PeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListB266PeriodsRequest) ProtoMessage() {}

func (x *ListB266PeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListB266PeriodsRequest.ProtoReflect.Descriptor instead.
func (*ListB266PeriodsRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{6}
}

type ListB266PeriodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []*B266Period          `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListB266PeriodsResponse) Reset() {
	*x = ListB266PeriodsResponse{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListB266PeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListB266PeriodsResponse) ProtoMessage() {}

func (x *ListB266PeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListB266PeriodsResponse.ProtoReflect.Descriptor instead.
func (*ListB266PeriodsResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{7}
}

func (x *ListB266PeriodsResponse) GetPeriods() []*B266Period {
	if x != nil {
		return x.Periods
	}
	return nil
}

type GetB266PeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetB266PeriodRequest) Reset() {
	*x = GetB266PeriodRequest{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetB266PeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetB266PeriodRequest) ProtoMessage() {}

func (x *GetB266PeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetB266PeriodRequest.ProtoReflect.Descriptor instead.
func (*GetB266PeriodRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{8}
}

func (x *GetB266PeriodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetB266PeriodResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Period *B266Period            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	// Frozen snapshot from submit time. Unset when status == DRAFT (which
	// means values were never frozen — re-run GenerateB266 to compute fresh).
	Snapshot      *B266Report `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetB266PeriodResponse) Reset() {
	*x = GetB266PeriodResponse{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetB266PeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetB266PeriodResponse) ProtoMessage() {}

func (x *GetB266PeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetB266PeriodResponse.ProtoReflect.Descriptor instead.
func (*GetB266PeriodResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{9}
}

func (x *GetB266PeriodResponse) GetPeriod() *B266Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *GetB266PeriodResponse) GetSnapshot() *B266Report {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Reopen flips a submitted period back to draft. Owner-only — needed
// when a genuine correction has to be made to a filed month and the
// operator wants the period-lock guard (stage 66) to stop blocking
// backdated mutations. Snapshot stays for audit.
type ReopenB266PeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReopenB266PeriodRequest) Reset() {
	*x = ReopenB266PeriodRequest{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReopenB266PeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReopenB266PeriodRequest) ProtoMessage() {}

func (x *ReopenB266PeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReopenB266PeriodRequest.ProtoReflect.Descriptor instead.
func (*ReopenB266PeriodRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{10}
}

func (x *ReopenB266PeriodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReopenB266PeriodRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReopenB266PeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *B266Period            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReopenB266PeriodResponse) Reset() {
	*x = ReopenB266PeriodResponse{}
	mi := &file_stillhouse_v1_b266_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReopenB266PeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReopenB266PeriodResponse) ProtoMessage() {}

func (x *ReopenB266PeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_b266_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReopenB266PeriodResponse.ProtoReflect.Descriptor instead.
func (*ReopenB266PeriodResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_b266_proto_rawDescGZIP(), []int{11}
}

func (x *ReopenB266PeriodResponse) GetPeriod() *B266Period {
	if x != nil {
		return x.Period
	}
	return nil
}

var File_stillhouse_v1_b266_proto protoreflect.FileDescriptor

const file_stillhouse_v1_b266_proto_rawDesc = "" +
	"\n" +
	"\x18stillhouse/v1/b266.proto\x12\rstillhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x02\n" +
	"\n" +
	"B266Period\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fperiod_start\x18\x02 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x03 \x01(\tR\tperiodEnd\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.stillhouse.v1.B266StatusR\x06status\x12=\n" +
	"\fsubmitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12!\n" +
	"\fsubmitted_by\x18\x06 \x01(\tR\vsubmittedBy\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb3\r\n" +
	"\n" +
	"B266Report\x12!\n" +
	"\fperiod_start\x18\x01 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x02 \x01(\tR\tperiodEnd\x12(\n" +
	"\x10bulk_opening_laa\x18\n" +
	" \x01(\x01R\x0ebulkOpeningLaa\x12.\n" +
	"\x13bulk_production_laa\x18\v \x01(\x01R\x11bulkProductionLaa\x128\n" +
	"\x19bulk_received_in_bond_laa\x18\f \x01(\x01R\x15bulkReceivedInBondLaa\x12)\n" +
	"\x11bulk_blend_in_laa\x18\r \x01(\x01R\x0ebulkBlendInLaa\x12H\n" +
	"!bulk_transferred_to_packaging_laa\x18\x0e \x01(\x01R\x1dbulkTransferredToPackagingLaa\x12E\n" +
	" bulk_transferred_out_in_bond_laa\x18\x0f \x01(\x01R\x1bbulkTransferredOutInBondLaa\x12&\n" +
	"\x0fbulk_losses_laa\x18\x10 \x01(\x01R\rbulkLossesLaa\x12,\n" +
	"\x12bulk_destroyed_laa\x18\x11 \x01(\x01R\x10bulkDestroyedLaa\x12(\n" +
	"\x10bulk_closing_laa\x18\x12 \x01(\x01R\x0ebulkClosingLaa\x12J\n" +
	"\"bulk_opening_inventory_adopted_laa\x18\x13 \x01(\x01R\x1ebulkOpeningInventoryAdoptedLaa\x120\n" +
	"\x14packaged_opening_laa\x18\x1e \x01(\x01R\x12packagedOpeningLaa\x122\n" +
	"\x15packaged_packaged_laa\x18\x1f \x01(\x01R\x13packagedPackagedLaa\x12:\n" +
	"\x19packaged_packaged_bottles\x18  \x01(\x05R\x17packagedPackagedBottles\x12B\n" +
	"\x1epackaged_removed_duty_paid_laa\x18! \x01(\x01R\x1apackagedRemovedDutyPaidLaa\x12J\n" +
	"\"packaged_removed_duty_paid_bottles\x18\" \x01(\x05R\x1epackagedRemovedDutyPaidBottles\x120\n" +
	"\x14packaged_closing_laa\x18# \x01(\x01R\x12packagedClosingLaa\x128\n" +
	"\x18packaged_closing_bottles\x18$ \x01(\x05R\x16packagedClosingBottles\x12=\n" +
	"\x1bpackaged_packaging_loss_laa\x18% \x01(\x01R\x18packagedPackagingLossLaa\x12;\n" +
	"\x1apackaged_removed_over7_laa\x18& \x01(\x01R\x17packagedRemovedOver7Laa\x12D\n" +
	"\x1fpackaged_removed_over7_duty_cad\x18' \x01(\x01R\x1bpackagedRemovedOver7DutyCad\x12C\n" +
	"\x1epackaged_removed_over7_bottles\x18( \x01(\x05R\x1bpackagedRemovedOver7Bottles\x12C\n" +
	"\x1epackaged_removed_under7_litres\x18) \x01(\x01R\x1bpackagedRemovedUnder7Litres\x12F\n" +
	" packaged_removed_under7_duty_cad\x18* \x01(\x01R\x1cpackagedRemovedUnder7DutyCad\x12E\n" +
	"\x1fpackaged_removed_under7_bottles\x18+ \x01(\x05R\x1cpackagedRemovedUnder7Bottles\x12:\n" +
	"\x1aduty_rate_per_litre_under7\x18, \x01(\x01R\x16dutyRatePerLitreUnder7\x12)\n" +
	"\x11duty_rate_per_laa\x182 \x01(\x01R\x0edutyRatePerLaa\x12(\n" +
	"\x10duty_payable_cad\x183 \x01(\x01R\x0edutyPayableCad\x12=\n" +
	"\fgenerated_at\x18< \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"W\n" +
	"\x13GenerateB266Request\x12!\n" +
	"\fperiod_start\x18\x01 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x02 \x01(\tR\tperiodEnd\"|\n" +
	"\x14GenerateB266Response\x121\n" +
	"\x06period\x18\x01 \x01(\v2\x19.stillhouse.v1.B266PeriodR\x06period\x121\n" +
	"\x06report\x18\x02 \x01(\v2\x19.stillhouse.v1.B266ReportR\x06report\"0\n" +
	"\x11SubmitB266Request\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\tR\bperiodId\"~\n" +
	"\x12SubmitB266Response\x121\n" +
	"\x06period\x18\x01 \x01(\v2\x19.stillhouse.v1.B266PeriodR\x06period\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.stillhouse.v1.B266ReportR\bsnapshot\"\x18\n" +
	"\x16ListB266PeriodsRequest\"N\n" +
	"\x17ListB266PeriodsResponse\x123\n" +
	"\aperiods\x18\x01 \x03(\v2\x19.stillhouse.v1.B266PeriodR\aperiods\"&\n" +
	"\x14GetB266PeriodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x15GetB266PeriodResponse\x121\n" +
	"\x06period\x18\x01 \x01(\v2\x19.stillhouse.v1.B266PeriodR\x06period\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.stillhouse.v1.B266ReportR\bsnapshot\"A\n" +
	"\x17ReopenB266PeriodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"M\n" +
	"\x18ReopenB266PeriodResponse\x121\n" +
	"\x06period\x18\x01 \x01(\v2\x19.stillhouse.v1.B266PeriodR\x06period*[\n" +
	"\n" +
	"B266Status\x12\x1b\n" +
	"\x17B266_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11B266_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15B266_STATUS_SUBMITTED\x10\x022\xdc\x03\n" +
	"\vB266Service\x12W\n" +
	"\fGenerateB266\x12\".stillhouse.v1.GenerateB266Request\x1a#.stillhouse.v1.GenerateB266Response\x12Q\n" +
	"\n" +
	"SubmitB266\x12 .stillhouse.v1.SubmitB266Request\x1a!.stillhouse.v1.SubmitB266Response\x12`\n" +
	"\x0fListB266Periods\x12%.stillhouse.v1.ListB266PeriodsRequest\x1a&.stillhouse.v1.ListB266PeriodsResponse\x12Z\n" +
	"\rGetB266Period\x12#.stillhouse.v1.GetB266PeriodRequest\x1a$.stillhouse.v1.GetB266PeriodResponse\x12c\n" +
	"\x10ReopenB266Period\x12&.stillhouse.v1.ReopenB266PeriodRequest\x1a'.stillhouse.v1.ReopenB266PeriodResponseB\xcd\x01\n" +
	"\x11com.stillhouse.v1B\tB266ProtoP\x01ZXgithub.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1;stillhousev1\xa2\x02\x03SXX\xaa\x02\rStillhouse.V1\xca\x02\rStillhouse\\V1\xe2\x02\x19Stillhouse\\V1\\GPBMetadata\xea\x02\x0eStillhouse::V1b\x06proto3"

var (
	file_stillhouse_v1_b266_proto_rawDescOnce sync.Once
	file_stillhouse_v1_b266_proto_rawDescData []byte
)

func file_stillhouse_v1_b266_proto_rawDescGZIP() []byte {
	file_stillhouse_v1_b266_proto_rawDescOnce.Do(func() {
		file_stillhouse_v1_b266_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillhouse_v1_b266_proto_rawDesc), len(file_stillhouse_v1_b266_proto_rawDesc)))
	})
	return file_stillhouse_v1_b266_proto_rawDescData
}

var file_stillhouse_v1_b266_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stillhouse_v1_b266_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_stillhouse_v1_b266_proto_goTypes = []any{
	(B266Status)(0),                  // 0: stillhouse.v1.B266Status
	(*B266Period)(nil),               // 1: stillhouse.v1.B266Period
	(*B266Report)(nil),               // 2: stillhouse.v1.B266Report
	(*GenerateB266Request)(nil),      // 3: stillhouse.v1.GenerateB266Request
	(*GenerateB266Response)(nil),     // 4: stillhouse.v1.GenerateB266Response
	(*SubmitB266Request)(nil),        // 5: stillhouse.v1.SubmitB266Request
	(*SubmitB266Response)(nil),       // 6: stillhouse.v1.SubmitB266Response
	(*ListB266PeriodsRequest)(nil),   // 7: stillhouse.v1.ListB266PeriodsRequest
	(*ListB266PeriodsResponse)(nil),  // 8: stillhouse.v1.ListB266PeriodsResponse
	(*GetB266PeriodRequest)(nil),     // 9: stillhouse.v1.GetB266PeriodRequest
	(*GetB266PeriodResponse)(nil),    // 10: stillhouse.v1.GetB266PeriodResponse
	(*ReopenB266PeriodRequest)(nil),  // 11: stillhouse.v1.ReopenB266PeriodRequest
	(*ReopenB266PeriodResponse)(nil), // 12: stillhouse.v1.ReopenB266PeriodResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_stillhouse_v1_b266_proto_depIdxs = []int32{
	0,  // 0: stillhouse.v1.B266Period.status:type_name -> stillhouse.v1.B266Status
	13, // 1: stillhouse.v1.B266Period.submitted_at:type_name -> google.protobuf.Timestamp
	13, // 2: stillhouse.v1.B266Period.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: stillhouse.v1.B266Period.updated_at:type_name -> google.protobuf.Timestamp
	13, // 4: stillhouse.v1.B266Report.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: stillhouse.v1.GenerateB266Response.period:type_name -> stillhouse.v1.B266Period
	2,  // 6: stillhouse.v1.GenerateB266Response.report:type_name -> stillhouse.v1.B266Report
	1,  // 7: stillhouse.v1.SubmitB266Response.period:type_name -> stillhouse.v1.B266Period
	2,  // 8: stillhouse.v1.SubmitB266Response.snapshot:type_name -> stillhouse.v1.B266Report
	1,  // 9: stillhouse.v1.ListB266PeriodsResponse.periods:type_name -> stillhouse.v1.B266Period
	1,  // 10: stillhouse.v1.GetB266PeriodResponse.period:type_name -> stillhouse.v1.B266Period
	2,  // 11: stillhouse.v1.GetB266PeriodResponse.snapshot:type_name -> stillhouse.v1.B266Report
	1,  // 12: stillhouse.v1.ReopenB266PeriodResponse.period:type_name -> stillhouse.v1.B266Period
	3,  // 13: stillhouse.v1.B266Service.GenerateB266:input_type -> stillhouse.v1.GenerateB266Request
	5,  // 14: stillhouse.v1.B266Service.SubmitB266:input_type -> stillhouse.v1.SubmitB266Request
	7,  // 15: stillhouse.v1.B266Service.ListB266Periods:input_type -> stillhouse.v1.ListB266PeriodsRequest
	9,  // 16: stillhouse.v1.B266Service.GetB266Period:input_type -> stillhouse.v1.GetB266PeriodRequest
	11, // 17: stillhouse.v1.B266Service.ReopenB266Period:input_type -> stillhouse.v1.ReopenB266PeriodRequest
	4,  // 18: stillhouse.v1.B266Service.GenerateB266:output_type -> stillhouse.v1.GenerateB266Response
	6,  // 19: stillhouse.v1.B266Service.SubmitB266:output_type -> stillhouse.v1.SubmitB266Response
	8,  // 20: stillhouse.v1.B266Service.ListB266Periods:output_type -> stillhouse.v1.ListB266PeriodsResponse
	10, // 21: stillhouse.v1.B266Service.GetB266Period:output_type -> stillhouse.v1.GetB266PeriodResponse
	12, // 22: stillhouse.v1.B266Service.ReopenB266Period:output_type -> stillhouse.v1.ReopenB266PeriodResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_stillhouse_v1_b266_proto_init() }
func file_stillhouse_v1_b266_proto_init() {
	if File_stillhouse_v1_b266_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillhouse_v1_b266_proto_rawDesc), len(file_stillhouse_v1_b266_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stillhouse_v1_b266_proto_goTypes,
		DependencyIndexes: file_stillhouse_v1_b266_proto_depIdxs,
		EnumInfos:         file_stillhouse_v1_b266_proto_enumTypes,
		MessageInfos:      file_stillhouse_v1_b266_proto_msgTypes,
	}.Build()
	File_stillhouse_v1_b266_proto = out.File
	file_stillhouse_v1_b266_proto_goTypes = nil
	file_stillhouse_v1_b266_proto_depIdxs = nil
}
