// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: stillhouse/v1/distillation.proto

package stillhousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistillationStatus int32

const (
	DistillationStatus_DISTILLATION_STATUS_UNSPECIFIED DistillationStatus = 0
	DistillationStatus_DISTILLATION_STATUS_PLANNED     DistillationStatus = 1
	DistillationStatus_DISTILLATION_STATUS_CHARGING    DistillationStatus = 2
	DistillationStatus_DISTILLATION_STATUS_DISTILLING  DistillationStatus = 3
	DistillationStatus_DISTILLATION_STATUS_GAUGED      DistillationStatus = 4
	DistillationStatus_DISTILLATION_STATUS_CANCELLED   DistillationStatus = 5
)

// Enum value maps for DistillationStatus.
var (
	DistillationStatus_name = map[int32]string{
		0: "DISTILLATION_STATUS_UNSPECIFIED",
		1: "DISTILLATION_STATUS_PLANNED",
		2: "DISTILLATION_STATUS_CHARGING",
		3: "DISTILLATION_STATUS_DISTILLING",
		4: "DISTILLATION_STATUS_GAUGED",
		5: "DISTILLATION_STATUS_CANCELLED",
	}
	DistillationStatus_value = map[string]int32{
		"DISTILLATION_STATUS_UNSPECIFIED": 0,
		"DISTILLATION_STATUS_PLANNED":     1,
		"DISTILLATION_STATUS_CHARGING":    2,
		"DISTILLATION_STATUS_DISTILLING":  3,
		"DISTILLATION_STATUS_GAUGED":      4,
		"DISTILLATION_STATUS_CANCELLED":   5,
	}
)

func (x DistillationStatus) Enum() *DistillationStatus {
	p := new(DistillationStatus)
	*p = x
	return p
}

func (x DistillationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistillationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_distillation_proto_enumTypes[0].Descriptor()
}

func (DistillationStatus) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_distillation_proto_enumTypes[0]
}

func (x DistillationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistillationStatus.Descriptor instead.
func (DistillationStatus) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{0}
}

type DistillationCutKind int32

const (
	DistillationCutKind_DISTILLATION_CUT_KIND_UNSPECIFIED  DistillationCutKind = 0
	DistillationCutKind_DISTILLATION_CUT_KIND_FORESHOTS    DistillationCutKind = 1
	DistillationCutKind_DISTILLATION_CUT_KIND_HEADS        DistillationCutKind = 2
	DistillationCutKind_DISTILLATION_CUT_KIND_HEARTS       DistillationCutKind = 3
	DistillationCutKind_DISTILLATION_CUT_KIND_TAILS        DistillationCutKind = 4
	DistillationCutKind_DISTILLATION_CUT_KIND_FEINTS_SAVED DistillationCutKind = 5
)

// Enum value maps for DistillationCutKind.
var (
	DistillationCutKind_name = map[int32]string{
		0: "DISTILLATION_CUT_KIND_UNSPECIFIED",
		1: "DISTILLATION_CUT_KIND_FORESHOTS",
		2: "DISTILLATION_CUT_KIND_HEADS",
		3: "DISTILLATION_CUT_KIND_HEARTS",
		4: "DISTILLATION_CUT_KIND_TAILS",
		5: "DISTILLATION_CUT_KIND_FEINTS_SAVED",
	}
	DistillationCutKind_value = map[string]int32{
		"DISTILLATION_CUT_KIND_UNSPECIFIED":  0,
		"DISTILLATION_CUT_KIND_FORESHOTS":    1,
		"DISTILLATION_CUT_KIND_HEADS":        2,
		"DISTILLATION_CUT_KIND_HEARTS":       3,
		"DISTILLATION_CUT_KIND_TAILS":        4,
		"DISTILLATION_CUT_KIND_FEINTS_SAVED": 5,
	}
)

func (x DistillationCutKind) Enum() *DistillationCutKind {
	p := new(DistillationCutKind)
	*p = x
	return p
}

func (x DistillationCutKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistillationCutKind) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_distillation_proto_enumTypes[1].Descriptor()
}

func (DistillationCutKind) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_distillation_proto_enumTypes[1]
}

func (x DistillationCutKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistillationCutKind.Descriptor instead.
func (DistillationCutKind) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{1}
}

type CutFindingSeverity int32

const (
	CutFindingSeverity_CUT_FINDING_SEVERITY_UNSPECIFIED CutFindingSeverity = 0
	CutFindingSeverity_CUT_FINDING_SEVERITY_INFO        CutFindingSeverity = 1
	CutFindingSeverity_CUT_FINDING_SEVERITY_WARNING     CutFindingSeverity = 2
	CutFindingSeverity_CUT_FINDING_SEVERITY_PROBLEM     CutFindingSeverity = 3
)

// Enum value maps for CutFindingSeverity.
var (
	CutFindingSeverity_name = map[int32]string{
		0: "CUT_FINDING_SEVERITY_UNSPECIFIED",
		1: "CUT_FINDING_SEVERITY_INFO",
		2: "CUT_FINDING_SEVERITY_WARNING",
		3: "CUT_FINDING_SEVERITY_PROBLEM",
	}
	CutFindingSeverity_value = map[string]int32{
		"CUT_FINDING_SEVERITY_UNSPECIFIED": 0,
		"CUT_FINDING_SEVERITY_INFO":        1,
		"CUT_FINDING_SEVERITY_WARNING":     2,
		"CUT_FINDING_SEVERITY_PROBLEM":     3,
	}
)

func (x CutFindingSeverity) Enum() *CutFindingSeverity {
	p := new(CutFindingSeverity)
	*p = x
	return p
}

func (x CutFindingSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CutFindingSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_distillation_proto_enumTypes[2].Descriptor()
}

func (CutFindingSeverity) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_distillation_proto_enumTypes[2]
}

func (x CutFindingSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CutFindingSeverity.Descriptor instead.
func (CutFindingSeverity) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{2}
}

type DistillationRun struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunNo      int32                  `protobuf:"varint,3,opt,name=run_no,json=runNo,proto3" json:"run_no,omitempty"`
	StillLabel string                 `protobuf:"bytes,4,opt,name=still_label,json=stillLabel,proto3" json:"still_label,omitempty"`
	RunDate    string                 `protobuf:"bytes,5,opt,name=run_date,json=runDate,proto3" json:"run_date,omitempty"` // ISO date
	Status     DistillationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=stillhouse.v1.DistillationStatus" json:"status,omitempty"`
	Notes      string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Children, populated by GetDistillationRun.
	Charges       []*DistillationCharge  `protobuf:"bytes,10,rep,name=charges,proto3" json:"charges,omitempty"`
	Cuts          []*DistillationCut     `protobuf:"bytes,11,rep,name=cuts,proto3" json:"cuts,omitempty"`
	Gauge         *ProductionGauge       `protobuf:"bytes,12,opt,name=gauge,proto3" json:"gauge,omitempty"`                                    // unset until RecordProductionGauge runs
	TotalCutLaa   float64                `protobuf:"fixed64,13,opt,name=total_cut_laa,json=totalCutLaa,proto3" json:"total_cut_laa,omitempty"` // computed sum from cuts
	CutAnalysis   *CutAnalysis           `protobuf:"bytes,17,opt,name=cut_analysis,json=cutAnalysis,proto3" json:"cut_analysis,omitempty"`     // populated by GetDistillationRun
	VoidedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=voided_at,json=voidedAt,proto3" json:"voided_at,omitempty"`
	VoidedBy      string                 `protobuf:"bytes,15,opt,name=voided_by,json=voidedBy,proto3" json:"voided_by,omitempty"`
	VoidedReason  string                 `protobuf:"bytes,16,opt,name=voided_reason,json=voidedReason,proto3" json:"voided_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistillationRun) Reset() {
	*x = DistillationRun{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistillationRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistillationRun) ProtoMessage() {}

func (x *DistillationRun) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistillationRun.ProtoReflect.Descriptor instead.
func (*DistillationRun) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{0}
}

func (x *DistillationRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DistillationRun) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DistillationRun) GetRunNo() int32 {
	if x != nil {
		return x.RunNo
	}
	return 0
}

func (x *DistillationRun) GetStillLabel() string {
	if x != nil {
		return x.StillLabel
	}
	return ""
}

func (x *DistillationRun) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

func (x *DistillationRun) GetStatus() DistillationStatus {
	if x != nil {
		return x.Status
	}
	return DistillationStatus_DISTILLATION_STATUS_UNSPECIFIED
}

func (x *DistillationRun) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *DistillationRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DistillationRun) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DistillationRun) GetCharges() []*DistillationCharge {
	if x != nil {
		return x.Charges
	}
	return nil
}

func (x *DistillationRun) GetCuts() []*DistillationCut {
	if x != nil {
		return x.Cuts
	}
	return nil
}

func (x *DistillationRun) GetGauge() *ProductionGauge {
	if x != nil {
		return x.Gauge
	}
	return nil
}

func (x *DistillationRun) GetTotalCutLaa() float64 {
	if x != nil {
		return x.TotalCutLaa
	}
	return 0
}

func (x *DistillationRun) GetCutAnalysis() *CutAnalysis {
	if x != nil {
		return x.CutAnalysis
	}
	return nil
}

func (x *DistillationRun) GetVoidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VoidedAt
	}
	return nil
}

func (x *DistillationRun) GetVoidedBy() string {
	if x != nil {
		return x.VoidedBy
	}
	return ""
}

func (x *DistillationRun) GetVoidedReason() string {
	if x != nil {
		return x.VoidedReason
	}
	return ""
}

type DistillationCharge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistillationRunId string                 `protobuf:"bytes,2,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	FermentationRunId string                 `protobuf:"bytes,3,opt,name=fermentation_run_id,json=fermentationRunId,proto3" json:"fermentation_run_id,omitempty"`
	FermenterLabel    string                 `protobuf:"bytes,4,opt,name=fermenter_label,json=fermenterLabel,proto3" json:"fermenter_label,omitempty"`
	MashNo            int32                  `protobuf:"varint,5,opt,name=mash_no,json=mashNo,proto3" json:"mash_no,omitempty"`
	VolumeChargedL    float64                `protobuf:"fixed64,6,opt,name=volume_charged_l,json=volumeChargedL,proto3" json:"volume_charged_l,omitempty"`
	AbvPct            float64                `protobuf:"fixed64,7,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	Laa               float64                `protobuf:"fixed64,8,opt,name=laa,proto3" json:"laa,omitempty"` // computed in service
	ChargeOrder       int32                  `protobuf:"varint,9,opt,name=charge_order,json=chargeOrder,proto3" json:"charge_order,omitempty"`
	Notes             string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DistillationCharge) Reset() {
	*x = DistillationCharge{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistillationCharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistillationCharge) ProtoMessage() {}

func (x *DistillationCharge) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistillationCharge.ProtoReflect.Descriptor instead.
func (*DistillationCharge) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{1}
}

func (x *DistillationCharge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DistillationCharge) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *DistillationCharge) GetFermentationRunId() string {
	if x != nil {
		return x.FermentationRunId
	}
	return ""
}

func (x *DistillationCharge) GetFermenterLabel() string {
	if x != nil {
		return x.FermenterLabel
	}
	return ""
}

func (x *DistillationCharge) GetMashNo() int32 {
	if x != nil {
		return x.MashNo
	}
	return 0
}

func (x *DistillationCharge) GetVolumeChargedL() float64 {
	if x != nil {
		return x.VolumeChargedL
	}
	return 0
}

func (x *DistillationCharge) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *DistillationCharge) GetLaa() float64 {
	if x != nil {
		return x.Laa
	}
	return 0
}

func (x *DistillationCharge) GetChargeOrder() int32 {
	if x != nil {
		return x.ChargeOrder
	}
	return 0
}

func (x *DistillationCharge) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type DistillationCut struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistillationRunId string                 `protobuf:"bytes,2,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	Kind              DistillationCutKind    `protobuf:"varint,3,opt,name=kind,proto3,enum=stillhouse.v1.DistillationCutKind" json:"kind,omitempty"`
	VolumeL           float64                `protobuf:"fixed64,4,opt,name=volume_l,json=volumeL,proto3" json:"volume_l,omitempty"`
	AbvPct            float64                `protobuf:"fixed64,5,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	Laa               float64                `protobuf:"fixed64,6,opt,name=laa,proto3" json:"laa,omitempty"`
	CutOrder          int32                  `protobuf:"varint,7,opt,name=cut_order,json=cutOrder,proto3" json:"cut_order,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Notes             string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DistillationCut) Reset() {
	*x = DistillationCut{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistillationCut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistillationCut) ProtoMessage() {}

func (x *DistillationCut) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistillationCut.ProtoReflect.Descriptor instead.
func (*DistillationCut) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{2}
}

func (x *DistillationCut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DistillationCut) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *DistillationCut) GetKind() DistillationCutKind {
	if x != nil {
		return x.Kind
	}
	return DistillationCutKind_DISTILLATION_CUT_KIND_UNSPECIFIED
}

func (x *DistillationCut) GetVolumeL() float64 {
	if x != nil {
		return x.VolumeL
	}
	return 0
}

func (x *DistillationCut) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *DistillationCut) GetLaa() float64 {
	if x != nil {
		return x.Laa
	}
	return 0
}

func (x *DistillationCut) GetCutOrder() int32 {
	if x != nil {
		return x.CutOrder
	}
	return 0
}

func (x *DistillationCut) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *DistillationCut) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CutFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      CutFindingSeverity     `protobuf:"varint,1,opt,name=severity,proto3,enum=stillhouse.v1.CutFindingSeverity" json:"severity,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutFinding) Reset() {
	*x = CutFinding{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutFinding) ProtoMessage() {}

func (x *CutFinding) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutFinding.ProtoReflect.Descriptor instead.
func (*CutFinding) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{3}
}

func (x *CutFinding) GetSeverity() CutFindingSeverity {
	if x != nil {
		return x.Severity
	}
	return CutFindingSeverity_CUT_FINDING_SEVERITY_UNSPECIFIED
}

func (x *CutFinding) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CutFinding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CutFinding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// CutAnalysis is what a run's cuts add up to.
//
// The judgements are limited to what holds for any spirit. Cut points are
// not universal — a wash run's heads and tails cuts sit at 54 % and 48 %
// ABV, while a botanical spirit's tails are diverted between 30 % and 20 %
// — so the hearts window is reported as a figure and the judgement is left
// to the distiller. What is checked is arithmetic that must hold either
// way: you cannot collect more alcohol than you charged, and strength
// falls as a run proceeds.
type CutAnalysis struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChargeLaa float64                `protobuf:"fixed64,1,opt,name=charge_laa,json=chargeLaa,proto3" json:"charge_laa,omitempty"`
	CutLaa    float64                `protobuf:"fixed64,2,opt,name=cut_laa,json=cutLaa,proto3" json:"cut_laa,omitempty"`
	// Cut LAA over charge LAA. The shortfall is the run's real losses —
	// vapour that never condensed, and what stayed in the pot and the line.
	AccountedPct   float64 `protobuf:"fixed64,3,opt,name=accounted_pct,json=accountedPct,proto3" json:"accounted_pct,omitempty"`
	HeartsLaa      float64 `protobuf:"fixed64,4,opt,name=hearts_laa,json=heartsLaa,proto3" json:"hearts_laa,omitempty"`
	HeartsSharePct float64 `protobuf:"fixed64,5,opt,name=hearts_share_pct,json=heartsSharePct,proto3" json:"hearts_share_pct,omitempty"`
	// The strength at the first and last hearts fraction: the cut points the
	// distiller actually took, and the number worth comparing between runs
	// of the same spirit.
	HeartsStartAbv float64       `protobuf:"fixed64,6,opt,name=hearts_start_abv,json=heartsStartAbv,proto3" json:"hearts_start_abv,omitempty"`
	HeartsEndAbv   float64       `protobuf:"fixed64,7,opt,name=hearts_end_abv,json=heartsEndAbv,proto3" json:"hearts_end_abv,omitempty"`
	HeartsSet      bool          `protobuf:"varint,8,opt,name=hearts_set,json=heartsSet,proto3" json:"hearts_set,omitempty"`
	Findings       []*CutFinding `protobuf:"bytes,9,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CutAnalysis) Reset() {
	*x = CutAnalysis{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutAnalysis) ProtoMessage() {}

func (x *CutAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutAnalysis.ProtoReflect.Descriptor instead.
func (*CutAnalysis) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{4}
}

func (x *CutAnalysis) GetChargeLaa() float64 {
	if x != nil {
		return x.ChargeLaa
	}
	return 0
}

func (x *CutAnalysis) GetCutLaa() float64 {
	if x != nil {
		return x.CutLaa
	}
	return 0
}

func (x *CutAnalysis) GetAccountedPct() float64 {
	if x != nil {
		return x.AccountedPct
	}
	return 0
}

func (x *CutAnalysis) GetHeartsLaa() float64 {
	if x != nil {
		return x.HeartsLaa
	}
	return 0
}

func (x *CutAnalysis) GetHeartsSharePct() float64 {
	if x != nil {
		return x.HeartsSharePct
	}
	return 0
}

func (x *CutAnalysis) GetHeartsStartAbv() float64 {
	if x != nil {
		return x.HeartsStartAbv
	}
	return 0
}

func (x *CutAnalysis) GetHeartsEndAbv() float64 {
	if x != nil {
		return x.HeartsEndAbv
	}
	return 0
}

func (x *CutAnalysis) GetHeartsSet() bool {
	if x != nil {
		return x.HeartsSet
	}
	return false
}

func (x *CutAnalysis) GetFindings() []*CutFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ProductionGauge struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistillationRunId        string                 `protobuf:"bytes,2,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	DestinationContainerId   string                 `protobuf:"bytes,3,opt,name=destination_container_id,json=destinationContainerId,proto3" json:"destination_container_id,omitempty"`
	DestinationContainerName string                 `protobuf:"bytes,4,opt,name=destination_container_name,json=destinationContainerName,proto3" json:"destination_container_name,omitempty"`
	BulkMovementId           string                 `protobuf:"bytes,5,opt,name=bulk_movement_id,json=bulkMovementId,proto3" json:"bulk_movement_id,omitempty"`
	GaugeDate                *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=gauge_date,json=gaugeDate,proto3" json:"gauge_date,omitempty"`
	// volume_l / abv_pct / laa are the values AT 20 °C — the pair the B266
	// is built from. observed_* below preserve what the operator read off
	// the instrument, so a gauge can be audited back to the bench.
	VolumeL         float64 `protobuf:"fixed64,7,opt,name=volume_l,json=volumeL,proto3" json:"volume_l,omitempty"`
	AbvPct          float64 `protobuf:"fixed64,8,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	TemperatureC    float64 `protobuf:"fixed64,9,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	TemperatureCSet bool    `protobuf:"varint,10,opt,name=temperature_c_set,json=temperatureCSet,proto3" json:"temperature_c_set,omitempty"`
	Laa             float64 `protobuf:"fixed64,11,opt,name=laa,proto3" json:"laa,omitempty"`
	GaugerUserId    string  `protobuf:"bytes,12,opt,name=gauger_user_id,json=gaugerUserId,proto3" json:"gauger_user_id,omitempty"`
	Notes           string  `protobuf:"bytes,13,opt,name=notes,proto3" json:"notes,omitempty"`
	// As observed, before correction to 20 °C.
	ObservedVolumeL        float64 `protobuf:"fixed64,14,opt,name=observed_volume_l,json=observedVolumeL,proto3" json:"observed_volume_l,omitempty"`
	ObservedDensityKgM3    float64 `protobuf:"fixed64,15,opt,name=observed_density_kg_m3,json=observedDensityKgM3,proto3" json:"observed_density_kg_m3,omitempty"`
	ObservedDensityKgM3Set bool    `protobuf:"varint,16,opt,name=observed_density_kg_m3_set,json=observedDensityKgM3Set,proto3" json:"observed_density_kg_m3_set,omitempty"`
	// C — the factor applied to observed_volume_l to reach volume_l.
	VolumeFactorC  float64        `protobuf:"fixed64,17,opt,name=volume_factor_c,json=volumeFactorC,proto3" json:"volume_factor_c,omitempty"`
	StrengthSource StrengthSource `protobuf:"varint,18,opt,name=strength_source,json=strengthSource,proto3,enum=stillhouse.v1.StrengthSource" json:"strength_source,omitempty"`
	// The instruments the determination was made with, resolved. This is the
	// last link in the audit chain: quantity → movement → determination →
	// the approved instrument that made it (EDM3-1-1 ¶24, EDM1-1-5). Unset
	// on rows recorded before the register existed, which is honest — they
	// name no instrument because none was named.
	Instruments   *DeterminationInstruments `protobuf:"bytes,19,opt,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionGauge) Reset() {
	*x = ProductionGauge{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionGauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionGauge) ProtoMessage() {}

func (x *ProductionGauge) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionGauge.ProtoReflect.Descriptor instead.
func (*ProductionGauge) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{5}
}

func (x *ProductionGauge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductionGauge) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *ProductionGauge) GetDestinationContainerId() string {
	if x != nil {
		return x.DestinationContainerId
	}
	return ""
}

func (x *ProductionGauge) GetDestinationContainerName() string {
	if x != nil {
		return x.DestinationContainerName
	}
	return ""
}

func (x *ProductionGauge) GetBulkMovementId() string {
	if x != nil {
		return x.BulkMovementId
	}
	return ""
}

func (x *ProductionGauge) GetGaugeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.GaugeDate
	}
	return nil
}

func (x *ProductionGauge) GetVolumeL() float64 {
	if x != nil {
		return x.VolumeL
	}
	return 0
}

func (x *ProductionGauge) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *ProductionGauge) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *ProductionGauge) GetTemperatureCSet() bool {
	if x != nil {
		return x.TemperatureCSet
	}
	return false
}

func (x *ProductionGauge) GetLaa() float64 {
	if x != nil {
		return x.Laa
	}
	return 0
}

func (x *ProductionGauge) GetGaugerUserId() string {
	if x != nil {
		return x.GaugerUserId
	}
	return ""
}

func (x *ProductionGauge) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ProductionGauge) GetObservedVolumeL() float64 {
	if x != nil {
		return x.ObservedVolumeL
	}
	return 0
}

func (x *ProductionGauge) GetObservedDensityKgM3() float64 {
	if x != nil {
		return x.ObservedDensityKgM3
	}
	return 0
}

func (x *ProductionGauge) GetObservedDensityKgM3Set() bool {
	if x != nil {
		return x.ObservedDensityKgM3Set
	}
	return false
}

func (x *ProductionGauge) GetVolumeFactorC() float64 {
	if x != nil {
		return x.VolumeFactorC
	}
	return 0
}

func (x *ProductionGauge) GetStrengthSource() StrengthSource {
	if x != nil {
		return x.StrengthSource
	}
	return StrengthSource_STRENGTH_SOURCE_UNSPECIFIED
}

func (x *ProductionGauge) GetInstruments() *DeterminationInstruments {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type CreateDistillationRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StillLabel    string                 `protobuf:"bytes,1,opt,name=still_label,json=stillLabel,proto3" json:"still_label,omitempty"`
	RunDate       string                 `protobuf:"bytes,2,opt,name=run_date,json=runDate,proto3" json:"run_date,omitempty"` // ISO; empty = today
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDistillationRunRequest) Reset() {
	*x = CreateDistillationRunRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDistillationRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDistillationRunRequest) ProtoMessage() {}

func (x *CreateDistillationRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDistillationRunRequest.ProtoReflect.Descriptor instead.
func (*CreateDistillationRunRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDistillationRunRequest) GetStillLabel() string {
	if x != nil {
		return x.StillLabel
	}
	return ""
}

func (x *CreateDistillationRunRequest) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

func (x *CreateDistillationRunRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateDistillationRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *DistillationRun       `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDistillationRunResponse) Reset() {
	*x = CreateDistillationRunResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDistillationRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDistillationRunResponse) ProtoMessage() {}

func (x *CreateDistillationRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDistillationRunResponse.ProtoReflect.Descriptor instead.
func (*CreateDistillationRunResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDistillationRunResponse) GetRun() *DistillationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetDistillationRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistillationRunRequest) Reset() {
	*x = GetDistillationRunRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistillationRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistillationRunRequest) ProtoMessage() {}

func (x *GetDistillationRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistillationRunRequest.ProtoReflect.Descriptor instead.
func (*GetDistillationRunRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{8}
}

func (x *GetDistillationRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDistillationRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *DistillationRun       `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistillationRunResponse) Reset() {
	*x = GetDistillationRunResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistillationRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistillationRunResponse) ProtoMessage() {}

func (x *GetDistillationRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistillationRunResponse.ProtoReflect.Descriptor instead.
func (*GetDistillationRunResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{9}
}

func (x *GetDistillationRunResponse) GetRun() *DistillationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListDistillationRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        DistillationStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=stillhouse.v1.DistillationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistillationRunsRequest) Reset() {
	*x = ListDistillationRunsRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistillationRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistillationRunsRequest) ProtoMessage() {}

func (x *ListDistillationRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistillationRunsRequest.ProtoReflect.Descriptor instead.
func (*ListDistillationRunsRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{10}
}

func (x *ListDistillationRunsRequest) GetStatus() DistillationStatus {
	if x != nil {
		return x.Status
	}
	return DistillationStatus_DISTILLATION_STATUS_UNSPECIFIED
}

type ListDistillationRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*DistillationRun     `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistillationRunsResponse) Reset() {
	*x = ListDistillationRunsResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistillationRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistillationRunsResponse) ProtoMessage() {}

func (x *ListDistillationRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistillationRunsResponse.ProtoReflect.Descriptor instead.
func (*ListDistillationRunsResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{11}
}

func (x *ListDistillationRunsResponse) GetRuns() []*DistillationRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

type UpdateDistillationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        DistillationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=stillhouse.v1.DistillationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDistillationStatusRequest) Reset() {
	*x = UpdateDistillationStatusRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDistillationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistillationStatusRequest) ProtoMessage() {}

func (x *UpdateDistillationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistillationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDistillationStatusRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDistillationStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDistillationStatusRequest) GetStatus() DistillationStatus {
	if x != nil {
		return x.Status
	}
	return DistillationStatus_DISTILLATION_STATUS_UNSPECIFIED
}

type UpdateDistillationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *DistillationRun       `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDistillationStatusResponse) Reset() {
	*x = UpdateDistillationStatusResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDistillationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistillationStatusResponse) ProtoMessage() {}

func (x *UpdateDistillationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistillationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDistillationStatusResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDistillationStatusResponse) GetRun() *DistillationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type AddDistillationChargeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DistillationRunId string                 `protobuf:"bytes,1,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	FermentationRunId string                 `protobuf:"bytes,2,opt,name=fermentation_run_id,json=fermentationRunId,proto3" json:"fermentation_run_id,omitempty"`
	VolumeChargedL    float64                `protobuf:"fixed64,3,opt,name=volume_charged_l,json=volumeChargedL,proto3" json:"volume_charged_l,omitempty"`
	AbvPct            float64                `protobuf:"fixed64,4,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	ChargeOrder       int32                  `protobuf:"varint,5,opt,name=charge_order,json=chargeOrder,proto3" json:"charge_order,omitempty"`
	Notes             string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddDistillationChargeRequest) Reset() {
	*x = AddDistillationChargeRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDistillationChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistillationChargeRequest) ProtoMessage() {}

func (x *AddDistillationChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistillationChargeRequest.ProtoReflect.Descriptor instead.
func (*AddDistillationChargeRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{14}
}

func (x *AddDistillationChargeRequest) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *AddDistillationChargeRequest) GetFermentationRunId() string {
	if x != nil {
		return x.FermentationRunId
	}
	return ""
}

func (x *AddDistillationChargeRequest) GetVolumeChargedL() float64 {
	if x != nil {
		return x.VolumeChargedL
	}
	return 0
}

func (x *AddDistillationChargeRequest) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *AddDistillationChargeRequest) GetChargeOrder() int32 {
	if x != nil {
		return x.ChargeOrder
	}
	return 0
}

func (x *AddDistillationChargeRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AddDistillationChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charge        *DistillationCharge    `protobuf:"bytes,1,opt,name=charge,proto3" json:"charge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDistillationChargeResponse) Reset() {
	*x = AddDistillationChargeResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDistillationChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistillationChargeResponse) ProtoMessage() {}

func (x *AddDistillationChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistillationChargeResponse.ProtoReflect.Descriptor instead.
func (*AddDistillationChargeResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{15}
}

func (x *AddDistillationChargeResponse) GetCharge() *DistillationCharge {
	if x != nil {
		return x.Charge
	}
	return nil
}

type AddDistillationCutRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DistillationRunId string                 `protobuf:"bytes,1,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	Kind              DistillationCutKind    `protobuf:"varint,2,opt,name=kind,proto3,enum=stillhouse.v1.DistillationCutKind" json:"kind,omitempty"`
	VolumeL           float64                `protobuf:"fixed64,3,opt,name=volume_l,json=volumeL,proto3" json:"volume_l,omitempty"`
	AbvPct            float64                `protobuf:"fixed64,4,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	CutOrder          int32                  `protobuf:"varint,5,opt,name=cut_order,json=cutOrder,proto3" json:"cut_order,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Notes             string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddDistillationCutRequest) Reset() {
	*x = AddDistillationCutRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDistillationCutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistillationCutRequest) ProtoMessage() {}

func (x *AddDistillationCutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistillationCutRequest.ProtoReflect.Descriptor instead.
func (*AddDistillationCutRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{16}
}

func (x *AddDistillationCutRequest) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *AddDistillationCutRequest) GetKind() DistillationCutKind {
	if x != nil {
		return x.Kind
	}
	return DistillationCutKind_DISTILLATION_CUT_KIND_UNSPECIFIED
}

func (x *AddDistillationCutRequest) GetVolumeL() float64 {
	if x != nil {
		return x.VolumeL
	}
	return 0
}

func (x *AddDistillationCutRequest) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *AddDistillationCutRequest) GetCutOrder() int32 {
	if x != nil {
		return x.CutOrder
	}
	return 0
}

func (x *AddDistillationCutRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *AddDistillationCutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AddDistillationCutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cut           *DistillationCut       `protobuf:"bytes,1,opt,name=cut,proto3" json:"cut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDistillationCutResponse) Reset() {
	*x = AddDistillationCutResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDistillationCutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDistillationCutResponse) ProtoMessage() {}

func (x *AddDistillationCutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDistillationCutResponse.ProtoReflect.Descriptor instead.
func (*AddDistillationCutResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{17}
}

func (x *AddDistillationCutResponse) GetCut() *DistillationCut {
	if x != nil {
		return x.Cut
	}
	return nil
}

type UpdateDistillationCutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          DistillationCutKind    `protobuf:"varint,2,opt,name=kind,proto3,enum=stillhouse.v1.DistillationCutKind" json:"kind,omitempty"`
	VolumeL       float64                `protobuf:"fixed64,3,opt,name=volume_l,json=volumeL,proto3" json:"volume_l,omitempty"`
	AbvPct        float64                `protobuf:"fixed64,4,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	CutOrder      int32                  `protobuf:"varint,5,opt,name=cut_order,json=cutOrder,proto3" json:"cut_order,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDistillationCutRequest) Reset() {
	*x = UpdateDistillationCutRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDistillationCutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistillationCutRequest) ProtoMessage() {}

func (x *UpdateDistillationCutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistillationCutRequest.ProtoReflect.Descriptor instead.
func (*UpdateDistillationCutRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateDistillationCutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDistillationCutRequest) GetKind() DistillationCutKind {
	if x != nil {
		return x.Kind
	}
	return DistillationCutKind_DISTILLATION_CUT_KIND_UNSPECIFIED
}

func (x *UpdateDistillationCutRequest) GetVolumeL() float64 {
	if x != nil {
		return x.VolumeL
	}
	return 0
}

func (x *UpdateDistillationCutRequest) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *UpdateDistillationCutRequest) GetCutOrder() int32 {
	if x != nil {
		return x.CutOrder
	}
	return 0
}

func (x *UpdateDistillationCutRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *UpdateDistillationCutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateDistillationCutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cut           *DistillationCut       `protobuf:"bytes,1,opt,name=cut,proto3" json:"cut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDistillationCutResponse) Reset() {
	*x = UpdateDistillationCutResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDistillationCutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistillationCutResponse) ProtoMessage() {}

func (x *UpdateDistillationCutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistillationCutResponse.ProtoReflect.Descriptor instead.
func (*UpdateDistillationCutResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDistillationCutResponse) GetCut() *DistillationCut {
	if x != nil {
		return x.Cut
	}
	return nil
}

type DeleteDistillationCutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDistillationCutRequest) Reset() {
	*x = DeleteDistillationCutRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDistillationCutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistillationCutRequest) ProtoMessage() {}

func (x *DeleteDistillationCutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistillationCutRequest.ProtoReflect.Descriptor instead.
func (*DeleteDistillationCutRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteDistillationCutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDistillationCutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDistillationCutResponse) Reset() {
	*x = DeleteDistillationCutResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDistillationCutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistillationCutResponse) ProtoMessage() {}

func (x *DeleteDistillationCutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistillationCutResponse.ProtoReflect.Descriptor instead.
func (*DeleteDistillationCutResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{21}
}

type RecordProductionGaugeRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DistillationRunId      string                 `protobuf:"bytes,1,opt,name=distillation_run_id,json=distillationRunId,proto3" json:"distillation_run_id,omitempty"`
	DestinationContainerId string                 `protobuf:"bytes,2,opt,name=destination_container_id,json=destinationContainerId,proto3" json:"destination_container_id,omitempty"`
	GaugeDate              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=gauge_date,json=gaugeDate,proto3" json:"gauge_date,omitempty"`
	// volume_l is the volume as gauged, at temperature_c.
	VolumeL float64 `protobuf:"fixed64,4,opt,name=volume_l,json=volumeL,proto3" json:"volume_l,omitempty"`
	// abv_pct is the strength at 20 °C when the instrument already corrects
	// (density meter), or when no temperature is supplied at all. Leave it
	// unset and send density_kg_m3 instead to have Stillhouse resolve the
	// strength through the published tables — CRA's approved path.
	AbvPct          float64 `protobuf:"fixed64,5,opt,name=abv_pct,json=abvPct,proto3" json:"abv_pct,omitempty"`
	TemperatureC    float64 `protobuf:"fixed64,6,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	TemperatureCSet bool    `protobuf:"varint,7,opt,name=temperature_c_set,json=temperatureCSet,proto3" json:"temperature_c_set,omitempty"`
	Notes           string  `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	// Hydrometer indication in kg/m³, read at temperature_c.
	DensityKgM3    float64 `protobuf:"fixed64,9,opt,name=density_kg_m3,json=densityKgM3,proto3" json:"density_kg_m3,omitempty"`
	DensityKgM3Set bool    `protobuf:"varint,10,opt,name=density_kg_m3_set,json=densityKgM3Set,proto3" json:"density_kg_m3_set,omitempty"`
	// The instruments this determination was made with. Optional — the
	// register starts empty — but any instrument named here is checked, and
	// one without a CRA approval on file is refused.
	Instruments   *InstrumentRefs `protobuf:"bytes,11,opt,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordProductionGaugeRequest) Reset() {
	*x = RecordProductionGaugeRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordProductionGaugeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordProductionGaugeRequest) ProtoMessage() {}

func (x *RecordProductionGaugeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordProductionGaugeRequest.ProtoReflect.Descriptor instead.
func (*RecordProductionGaugeRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{22}
}

func (x *RecordProductionGaugeRequest) GetDistillationRunId() string {
	if x != nil {
		return x.DistillationRunId
	}
	return ""
}

func (x *RecordProductionGaugeRequest) GetDestinationContainerId() string {
	if x != nil {
		return x.DestinationContainerId
	}
	return ""
}

func (x *RecordProductionGaugeRequest) GetGaugeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.GaugeDate
	}
	return nil
}

func (x *RecordProductionGaugeRequest) GetVolumeL() float64 {
	if x != nil {
		return x.VolumeL
	}
	return 0
}

func (x *RecordProductionGaugeRequest) GetAbvPct() float64 {
	if x != nil {
		return x.AbvPct
	}
	return 0
}

func (x *RecordProductionGaugeRequest) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *RecordProductionGaugeRequest) GetTemperatureCSet() bool {
	if x != nil {
		return x.TemperatureCSet
	}
	return false
}

func (x *RecordProductionGaugeRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RecordProductionGaugeRequest) GetDensityKgM3() float64 {
	if x != nil {
		return x.DensityKgM3
	}
	return 0
}

func (x *RecordProductionGaugeRequest) GetDensityKgM3Set() bool {
	if x != nil {
		return x.DensityKgM3Set
	}
	return false
}

func (x *RecordProductionGaugeRequest) GetInstruments() *InstrumentRefs {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type RecordProductionGaugeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Gauge                *ProductionGauge       `protobuf:"bytes,1,opt,name=gauge,proto3" json:"gauge,omitempty"`
	DestinationContainer *BulkContainer         `protobuf:"bytes,2,opt,name=destination_container,json=destinationContainer,proto3" json:"destination_container,omitempty"`
	// Conditions that did not block the determination but that an operator
	// and an auditor both want to see — an instrument past due for
	// calibration is still approved, so it is a warning, not a refusal.
	Warnings      []string `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordProductionGaugeResponse) Reset() {
	*x = RecordProductionGaugeResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordProductionGaugeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordProductionGaugeResponse) ProtoMessage() {}

func (x *RecordProductionGaugeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordProductionGaugeResponse.ProtoReflect.Descriptor instead.
func (*RecordProductionGaugeResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{23}
}

func (x *RecordProductionGaugeResponse) GetGauge() *ProductionGauge {
	if x != nil {
		return x.Gauge
	}
	return nil
}

func (x *RecordProductionGaugeResponse) GetDestinationContainer() *BulkContainer {
	if x != nil {
		return x.DestinationContainer
	}
	return nil
}

func (x *RecordProductionGaugeResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type VoidDistillationRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidDistillationRunRequest) Reset() {
	*x = VoidDistillationRunRequest{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidDistillationRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidDistillationRunRequest) ProtoMessage() {}

func (x *VoidDistillationRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidDistillationRunRequest.ProtoReflect.Descriptor instead.
func (*VoidDistillationRunRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{24}
}

func (x *VoidDistillationRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoidDistillationRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VoidDistillationRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *DistillationRun       `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidDistillationRunResponse) Reset() {
	*x = VoidDistillationRunResponse{}
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidDistillationRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidDistillationRunResponse) ProtoMessage() {}

func (x *VoidDistillationRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_distillation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidDistillationRunResponse.ProtoReflect.Descriptor instead.
func (*VoidDistillationRunResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_distillation_proto_rawDescGZIP(), []int{25}
}

func (x *VoidDistillationRunResponse) GetRun() *DistillationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_stillhouse_v1_distillation_proto protoreflect.FileDescriptor

const file_stillhouse_v1_distillation_proto_rawDesc = "" +
	"\n" +
	" stillhouse/v1/distillation.proto\x12\rstillhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1estillhouse/v1/instrument.proto\x1a!stillhouse/v1/alcoholometry.proto\x1a\x18stillhouse/v1/bulk.proto\"\xdd\x05\n" +
	"\x0fDistillationRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_no\x18\x03 \x01(\x05R\x05runNo\x12\x1f\n" +
	"\vstill_label\x18\x04 \x01(\tR\n" +
	"stillLabel\x12\x19\n" +
	"\brun_date\x18\x05 \x01(\tR\arunDate\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.stillhouse.v1.DistillationStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\acharges\x18\n" +
	" \x03(\v2!.stillhouse.v1.DistillationChargeR\acharges\x122\n" +
	"\x04cuts\x18\v \x03(\v2\x1e.stillhouse.v1.DistillationCutR\x04cuts\x124\n" +
	"\x05gauge\x18\f \x01(\v2\x1e.stillhouse.v1.ProductionGaugeR\x05gauge\x12\"\n" +
	"\rtotal_cut_laa\x18\r \x01(\x01R\vtotalCutLaa\x12=\n" +
	"\fcut_analysis\x18\x11 \x01(\v2\x1a.stillhouse.v1.CutAnalysisR\vcutAnalysis\x127\n" +
	"\tvoided_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\bvoidedAt\x12\x1b\n" +
	"\tvoided_by\x18\x0f \x01(\tR\bvoidedBy\x12#\n" +
	"\rvoided_reason\x18\x10 \x01(\tR\fvoidedReason\"\xd4\x02\n" +
	"\x12DistillationCharge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13distillation_run_id\x18\x02 \x01(\tR\x11distillationRunId\x12.\n" +
	"\x13fermentation_run_id\x18\x03 \x01(\tR\x11fermentationRunId\x12'\n" +
	"\x0ffermenter_label\x18\x04 \x01(\tR\x0efermenterLabel\x12\x17\n" +
	"\amash_no\x18\x05 \x01(\x05R\x06mashNo\x12(\n" +
	"\x10volume_charged_l\x18\x06 \x01(\x01R\x0evolumeChargedL\x12\x17\n" +
	"\aabv_pct\x18\a \x01(\x01R\x06abvPct\x12\x10\n" +
	"\x03laa\x18\b \x01(\x01R\x03laa\x12!\n" +
	"\fcharge_order\x18\t \x01(\x05R\vchargeOrder\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\"\xbf\x02\n" +
	"\x0fDistillationCut\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13distillation_run_id\x18\x02 \x01(\tR\x11distillationRunId\x126\n" +
	"\x04kind\x18\x03 \x01(\x0e2\".stillhouse.v1.DistillationCutKindR\x04kind\x12\x19\n" +
	"\bvolume_l\x18\x04 \x01(\x01R\avolumeL\x12\x17\n" +
	"\aabv_pct\x18\x05 \x01(\x01R\x06abvPct\x12\x10\n" +
	"\x03laa\x18\x06 \x01(\x01R\x03laa\x12\x1b\n" +
	"\tcut_order\x18\a \x01(\x05R\bcutOrder\x12;\n" +
	"\vobserved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\"\x8d\x01\n" +
	"\n" +
	"CutFinding\x12=\n" +
	"\bseverity\x18\x01 \x01(\x0e2!.stillhouse.v1.CutFindingSeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\xd9\x02\n" +
	"\vCutAnalysis\x12\x1d\n" +
	"\n" +
	"charge_laa\x18\x01 \x01(\x01R\tchargeLaa\x12\x17\n" +
	"\acut_laa\x18\x02 \x01(\x01R\x06cutLaa\x12#\n" +
	"\raccounted_pct\x18\x03 \x01(\x01R\faccountedPct\x12\x1d\n" +
	"\n" +
	"hearts_laa\x18\x04 \x01(\x01R\theartsLaa\x12(\n" +
	"\x10hearts_share_pct\x18\x05 \x01(\x01R\x0eheartsSharePct\x12(\n" +
	"\x10hearts_start_abv\x18\x06 \x01(\x01R\x0eheartsStartAbv\x12$\n" +
	"\x0ehearts_end_abv\x18\a \x01(\x01R\fheartsEndAbv\x12\x1d\n" +
	"\n" +
	"hearts_set\x18\b \x01(\bR\theartsSet\x125\n" +
	"\bfindings\x18\t \x03(\v2\x19.stillhouse.v1.CutFindingR\bfindings\"\xd9\x06\n" +
	"\x0fProductionGauge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13distillation_run_id\x18\x02 \x01(\tR\x11distillationRunId\x128\n" +
	"\x18destination_container_id\x18\x03 \x01(\tR\x16destinationContainerId\x12<\n" +
	"\x1adestination_container_name\x18\x04 \x01(\tR\x18destinationContainerName\x12(\n" +
	"\x10bulk_movement_id\x18\x05 \x01(\tR\x0ebulkMovementId\x129\n" +
	"\n" +
	"gauge_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tgaugeDate\x12\x19\n" +
	"\bvolume_l\x18\a \x01(\x01R\avolumeL\x12\x17\n" +
	"\aabv_pct\x18\b \x01(\x01R\x06abvPct\x12#\n" +
	"\rtemperature_c\x18\t \x01(\x01R\ftemperatureC\x12*\n" +
	"\x11temperature_c_set\x18\n" +
	" \x01(\bR\x0ftemperatureCSet\x12\x10\n" +
	"\x03laa\x18\v \x01(\x01R\x03laa\x12$\n" +
	"\x0egauger_user_id\x18\f \x01(\tR\fgaugerUserId\x12\x14\n" +
	"\x05notes\x18\r \x01(\tR\x05notes\x12*\n" +
	"\x11observed_volume_l\x18\x0e \x01(\x01R\x0fobservedVolumeL\x123\n" +
	"\x16observed_density_kg_m3\x18\x0f \x01(\x01R\x13observedDensityKgM3\x12:\n" +
	"\x1aobserved_density_kg_m3_set\x18\x10 \x01(\bR\x16observedDensityKgM3Set\x12&\n" +
	"\x0fvolume_factor_c\x18\x11 \x01(\x01R\rvolumeFactorC\x12F\n" +
	"\x0fstrength_source\x18\x12 \x01(\x0e2\x1d.stillhouse.v1.StrengthSourceR\x0estrengthSource\x12I\n" +
	"\vinstruments\x18\x13 \x01(\v2'.stillhouse.v1.DeterminationInstrumentsR\vinstruments\"p\n" +
	"\x1cCreateDistillationRunRequest\x12\x1f\n" +
	"\vstill_label\x18\x01 \x01(\tR\n" +
	"stillLabel\x12\x19\n" +
	"\brun_date\x18\x02 \x01(\tR\arunDate\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"Q\n" +
	"\x1dCreateDistillationRunResponse\x120\n" +
	"\x03run\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationRunR\x03run\"+\n" +
	"\x19GetDistillationRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x1aGetDistillationRunResponse\x120\n" +
	"\x03run\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationRunR\x03run\"X\n" +
	"\x1bListDistillationRunsRequest\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.stillhouse.v1.DistillationStatusR\x06status\"R\n" +
	"\x1cListDistillationRunsResponse\x122\n" +
	"\x04runs\x18\x01 \x03(\v2\x1e.stillhouse.v1.DistillationRunR\x04runs\"l\n" +
	"\x1fUpdateDistillationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.stillhouse.v1.DistillationStatusR\x06status\"T\n" +
	" UpdateDistillationStatusResponse\x120\n" +
	"\x03run\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationRunR\x03run\"\xfa\x01\n" +
	"\x1cAddDistillationChargeRequest\x12.\n" +
	"\x13distillation_run_id\x18\x01 \x01(\tR\x11distillationRunId\x12.\n" +
	"\x13fermentation_run_id\x18\x02 \x01(\tR\x11fermentationRunId\x12(\n" +
	"\x10volume_charged_l\x18\x03 \x01(\x01R\x0evolumeChargedL\x12\x17\n" +
	"\aabv_pct\x18\x04 \x01(\x01R\x06abvPct\x12!\n" +
	"\fcharge_order\x18\x05 \x01(\x05R\vchargeOrder\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"Z\n" +
	"\x1dAddDistillationChargeResponse\x129\n" +
	"\x06charge\x18\x01 \x01(\v2!.stillhouse.v1.DistillationChargeR\x06charge\"\xa7\x02\n" +
	"\x19AddDistillationCutRequest\x12.\n" +
	"\x13distillation_run_id\x18\x01 \x01(\tR\x11distillationRunId\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".stillhouse.v1.DistillationCutKindR\x04kind\x12\x19\n" +
	"\bvolume_l\x18\x03 \x01(\x01R\avolumeL\x12\x17\n" +
	"\aabv_pct\x18\x04 \x01(\x01R\x06abvPct\x12\x1b\n" +
	"\tcut_order\x18\x05 \x01(\x05R\bcutOrder\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"N\n" +
	"\x1aAddDistillationCutResponse\x120\n" +
	"\x03cut\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationCutR\x03cut\"\x8a\x02\n" +
	"\x1cUpdateDistillationCutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".stillhouse.v1.DistillationCutKindR\x04kind\x12\x19\n" +
	"\bvolume_l\x18\x03 \x01(\x01R\avolumeL\x12\x17\n" +
	"\aabv_pct\x18\x04 \x01(\x01R\x06abvPct\x12\x1b\n" +
	"\tcut_order\x18\x05 \x01(\x05R\bcutOrder\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"Q\n" +
	"\x1dUpdateDistillationCutResponse\x120\n" +
	"\x03cut\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationCutR\x03cut\".\n" +
	"\x1cDeleteDistillationCutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\x1dDeleteDistillationCutResponse\"\xee\x03\n" +
	"\x1cRecordProductionGaugeRequest\x12.\n" +
	"\x13distillation_run_id\x18\x01 \x01(\tR\x11distillationRunId\x128\n" +
	"\x18destination_container_id\x18\x02 \x01(\tR\x16destinationContainerId\x129\n" +
	"\n" +
	"gauge_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tgaugeDate\x12\x19\n" +
	"\bvolume_l\x18\x04 \x01(\x01R\avolumeL\x12\x17\n" +
	"\aabv_pct\x18\x05 \x01(\x01R\x06abvPct\x12#\n" +
	"\rtemperature_c\x18\x06 \x01(\x01R\ftemperatureC\x12*\n" +
	"\x11temperature_c_set\x18\a \x01(\bR\x0ftemperatureCSet\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x12\"\n" +
	"\rdensity_kg_m3\x18\t \x01(\x01R\vdensityKgM3\x12)\n" +
	"\x11density_kg_m3_set\x18\n" +
	" \x01(\bR\x0edensityKgM3Set\x12?\n" +
	"\vinstruments\x18\v \x01(\v2\x1d.stillhouse.v1.InstrumentRefsR\vinstruments\"\xc4\x01\n" +
	"\x1dRecordProductionGaugeResponse\x124\n" +
	"\x05gauge\x18\x01 \x01(\v2\x1e.stillhouse.v1.ProductionGaugeR\x05gauge\x12Q\n" +
	"\x15destination_container\x18\x02 \x01(\v2\x1c.stillhouse.v1.BulkContainerR\x14destinationContainer\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"D\n" +
	"\x1aVoidDistillationRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\x1bVoidDistillationRunResponse\x120\n" +
	"\x03run\x18\x01 \x01(\v2\x1e.stillhouse.v1.DistillationRunR\x03run*\xe3\x01\n" +
	"\x12DistillationStatus\x12#\n" +
	"\x1fDISTILLATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDISTILLATION_STATUS_PLANNED\x10\x01\x12 \n" +
	"\x1cDISTILLATION_STATUS_CHARGING\x10\x02\x12\"\n" +
	"\x1eDISTILLATION_STATUS_DISTILLING\x10\x03\x12\x1e\n" +
	"\x1aDISTILLATION_STATUS_GAUGED\x10\x04\x12!\n" +
	"\x1dDISTILLATION_STATUS_CANCELLED\x10\x05*\xed\x01\n" +
	"\x13DistillationCutKind\x12%\n" +
	"!DISTILLATION_CUT_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDISTILLATION_CUT_KIND_FORESHOTS\x10\x01\x12\x1f\n" +
	"\x1bDISTILLATION_CUT_KIND_HEADS\x10\x02\x12 \n" +
	"\x1cDISTILLATION_CUT_KIND_HEARTS\x10\x03\x12\x1f\n" +
	"\x1bDISTILLATION_CUT_KIND_TAILS\x10\x04\x12&\n" +
	"\"DISTILLATION_CUT_KIND_FEINTS_SAVED\x10\x05*\x9d\x01\n" +
	"\x12CutFindingSeverity\x12$\n" +
	" CUT_FINDING_SEVERITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CUT_FINDING_SEVERITY_INFO\x10\x01\x12 \n" +
	"\x1cCUT_FINDING_SEVERITY_WARNING\x10\x02\x12 \n" +
	"\x1cCUT_FINDING_SEVERITY_PROBLEM\x10\x032\x8b\t\n" +
	"\x13DistillationService\x12r\n" +
	"\x15CreateDistillationRun\x12+.stillhouse.v1.CreateDistillationRunRequest\x1a,.stillhouse.v1.CreateDistillationRunResponse\x12i\n" +
	"\x12GetDistillationRun\x12(.stillhouse.v1.GetDistillationRunRequest\x1a).stillhouse.v1.GetDistillationRunResponse\x12o\n" +
	"\x14ListDistillationRuns\x12*.stillhouse.v1.ListDistillationRunsRequest\x1a+.stillhouse.v1.ListDistillationRunsResponse\x12{\n" +
	"\x18UpdateDistillationStatus\x12..stillhouse.v1.UpdateDistillationStatusRequest\x1a/.stillhouse.v1.UpdateDistillationStatusResponse\x12r\n" +
	"\x15AddDistillationCharge\x12+.stillhouse.v1.AddDistillationChargeRequest\x1a,.stillhouse.v1.AddDistillationChargeResponse\x12i\n" +
	"\x12AddDistillationCut\x12(.stillhouse.v1.AddDistillationCutRequest\x1a).stillhouse.v1.AddDistillationCutResponse\x12r\n" +
	"\x15RecordProductionGauge\x12+.stillhouse.v1.RecordProductionGaugeRequest\x1a,.stillhouse.v1.RecordProductionGaugeResponse\x12l\n" +
	"\x13VoidDistillationRun\x12).stillhouse.v1.VoidDistillationRunRequest\x1a*.stillhouse.v1.VoidDistillationRunResponse\x12r\n" +
	"\x15UpdateDistillationCut\x12+.stillhouse.v1.UpdateDistillationCutRequest\x1a,.stillhouse.v1.UpdateDistillationCutResponse\x12r\n" +
	"\x15DeleteDistillationCut\x12+.stillhouse.v1.DeleteDistillationCutRequest\x1a,.stillhouse.v1.DeleteDistillationCutResponseB\xd5\x01\n" +
	"\x11com.stillhouse.v1B\x11DistillationProtoP\x01ZXgithub.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1;stillhousev1\xa2\x02\x03SXX\xaa\x02\rStillhouse.V1\xca\x02\rStillhouse\\V1\xe2\x02\x19Stillhouse\\V1\\GPBMetadata\xea\x02\x0eStillhouse::V1b\x06proto3"

var (
	file_stillhouse_v1_distillation_proto_rawDescOnce sync.Once
	file_stillhouse_v1_distillation_proto_rawDescData []byte
)

func file_stillhouse_v1_distillation_proto_rawDescGZIP() []byte {
	file_stillhouse_v1_distillation_proto_rawDescOnce.Do(func() {
		file_stillhouse_v1_distillation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillhouse_v1_distillation_proto_rawDesc), len(file_stillhouse_v1_distillation_proto_rawDesc)))
	})
	return file_stillhouse_v1_distillation_proto_rawDescData
}

var file_stillhouse_v1_distillation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_stillhouse_v1_distillation_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_stillhouse_v1_distillation_proto_goTypes = []any{
	(DistillationStatus)(0),                  // 0: stillhouse.v1.DistillationStatus
	(DistillationCutKind)(0),                 // 1: stillhouse.v1.DistillationCutKind
	(CutFindingSeverity)(0),                  // 2: stillhouse.v1.CutFindingSeverity
	(*DistillationRun)(nil),                  // 3: stillhouse.v1.DistillationRun
	(*DistillationCharge)(nil),               // 4: stillhouse.v1.DistillationCharge
	(*DistillationCut)(nil),                  // 5: stillhouse.v1.DistillationCut
	(*CutFinding)(nil),                       // 6: stillhouse.v1.CutFinding
	(*CutAnalysis)(nil),                      // 7: stillhouse.v1.CutAnalysis
	(*ProductionGauge)(nil),                  // 8: stillhouse.v1.ProductionGauge
	(*CreateDistillationRunRequest)(nil),     // 9: stillhouse.v1.CreateDistillationRunRequest
	(*CreateDistillationRunResponse)(nil),    // 10: stillhouse.v1.CreateDistillationRunResponse
	(*GetDistillationRunRequest)(nil),        // 11: stillhouse.v1.GetDistillationRunRequest
	(*GetDistillationRunResponse)(nil),       // 12: stillhouse.v1.GetDistillationRunResponse
	(*ListDistillationRunsRequest)(nil),      // 13: stillhouse.v1.ListDistillationRunsRequest
	(*ListDistillationRunsResponse)(nil),     // 14: stillhouse.v1.ListDistillationRunsResponse
	(*UpdateDistillationStatusRequest)(nil),  // 15: stillhouse.v1.UpdateDistillationStatusRequest
	(*UpdateDistillationStatusResponse)(nil), // 16: stillhouse.v1.UpdateDistillationStatusResponse
	(*AddDistillationChargeRequest)(nil),     // 17: stillhouse.v1.AddDistillationChargeRequest
	(*AddDistillationChargeResponse)(nil),    // 18: stillhouse.v1.AddDistillationChargeResponse
	(*AddDistillationCutRequest)(nil),        // 19: stillhouse.v1.AddDistillationCutRequest
	(*AddDistillationCutResponse)(nil),       // 20: stillhouse.v1.AddDistillationCutResponse
	(*UpdateDistillationCutRequest)(nil),     // 21: stillhouse.v1.UpdateDistillationCutRequest
	(*UpdateDistillationCutResponse)(nil),    // 22: stillhouse.v1.UpdateDistillationCutResponse
	(*DeleteDistillationCutRequest)(nil),     // 23: stillhouse.v1.DeleteDistillationCutRequest
	(*DeleteDistillationCutResponse)(nil),    // 24: stillhouse.v1.DeleteDistillationCutResponse
	(*RecordProductionGaugeRequest)(nil),     // 25: stillhouse.v1.RecordProductionGaugeRequest
	(*RecordProductionGaugeResponse)(nil),    // 26: stillhouse.v1.RecordProductionGaugeResponse
	(*VoidDistillationRunRequest)(nil),       // 27: stillhouse.v1.VoidDistillationRunRequest
	(*VoidDistillationRunResponse)(nil),      // 28: stillhouse.v1.VoidDistillationRunResponse
	(*timestamppb.Timestamp)(nil),            // 29: google.protobuf.Timestamp
	(StrengthSource)(0),                      // 30: stillhouse.v1.StrengthSource
	(*DeterminationInstruments)(nil),         // 31: stillhouse.v1.DeterminationInstruments
	(*InstrumentRefs)(nil),                   // 32: stillhouse.v1.InstrumentRefs
	(*BulkContainer)(nil),                    // 33: stillhouse.v1.BulkContainer
}
var file_stillhouse_v1_distillation_proto_depIdxs = []int32{
	0,  // 0: stillhouse.v1.DistillationRun.status:type_name -> stillhouse.v1.DistillationStatus
	29, // 1: stillhouse.v1.DistillationRun.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: stillhouse.v1.DistillationRun.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 3: stillhouse.v1.DistillationRun.charges:type_name -> stillhouse.v1.DistillationCharge
	5,  // 4: stillhouse.v1.DistillationRun.cuts:type_name -> stillhouse.v1.DistillationCut
	8,  // 5: stillhouse.v1.DistillationRun.gauge:type_name -> stillhouse.v1.ProductionGauge
	7,  // 6: stillhouse.v1.DistillationRun.cut_analysis:type_name -> stillhouse.v1.CutAnalysis
	29, // 7: stillhouse.v1.DistillationRun.voided_at:type_name -> google.protobuf.Timestamp
	1,  // 8: stillhouse.v1.DistillationCut.kind:type_name -> stillhouse.v1.DistillationCutKind
	29, // 9: stillhouse.v1.DistillationCut.observed_at:type_name -> google.protobuf.Timestamp
	2,  // 10: stillhouse.v1.CutFinding.severity:type_name -> stillhouse.v1.CutFindingSeverity
	6,  // 11: stillhouse.v1.CutAnalysis.findings:type_name -> stillhouse.v1.CutFinding
	29, // 12: stillhouse.v1.ProductionGauge.gauge_date:type_name -> google.protobuf.Timestamp
	30, // 13: stillhouse.v1.ProductionGauge.strength_source:type_name -> stillhouse.v1.StrengthSource
	31, // 14: stillhouse.v1.ProductionGauge.instruments:type_name -> stillhouse.v1.DeterminationInstruments
	3,  // 15: stillhouse.v1.CreateDistillationRunResponse.run:type_name -> stillhouse.v1.DistillationRun
	3,  // 16: stillhouse.v1.GetDistillationRunResponse.run:type_name -> stillhouse.v1.DistillationRun
	0,  // 17: stillhouse.v1.ListDistillationRunsRequest.status:type_name -> stillhouse.v1.DistillationStatus
	3,  // 18: stillhouse.v1.ListDistillationRunsResponse.runs:type_name -> stillhouse.v1.DistillationRun
	0,  // 19: stillhouse.v1.UpdateDistillationStatusRequest.status:type_name -> stillhouse.v1.DistillationStatus
	3,  // 20: stillhouse.v1.UpdateDistillationStatusResponse.run:type_name -> stillhouse.v1.DistillationRun
	4,  // 21: stillhouse.v1.AddDistillationChargeResponse.charge:type_name -> stillhouse.v1.DistillationCharge
	1,  // 22: stillhouse.v1.AddDistillationCutRequest.kind:type_name -> stillhouse.v1.DistillationCutKind
	29, // 23: stillhouse.v1.AddDistillationCutRequest.observed_at:type_name -> google.protobuf.Timestamp
	5,  // 24: stillhouse.v1.AddDistillationCutResponse.cut:type_name -> stillhouse.v1.DistillationCut
	1,  // 25: stillhouse.v1.UpdateDistillationCutRequest.kind:type_name -> stillhouse.v1.DistillationCutKind
	29, // 26: stillhouse.v1.UpdateDistillationCutRequest.observed_at:type_name -> google.protobuf.Timestamp
	5,  // 27: stillhouse.v1.UpdateDistillationCutResponse.cut:type_name -> stillhouse.v1.DistillationCut
	29, // 28: stillhouse.v1.RecordProductionGaugeRequest.gauge_date:type_name -> google.protobuf.Timestamp
	32, // 29: stillhouse.v1.RecordProductionGaugeRequest.instruments:type_name -> stillhouse.v1.InstrumentRefs
	8,  // 30: stillhouse.v1.RecordProductionGaugeResponse.gauge:type_name -> stillhouse.v1.ProductionGauge
	33, // 31: stillhouse.v1.RecordProductionGaugeResponse.destination_container:type_name -> stillhouse.v1.BulkContainer
	3,  // 32: stillhouse.v1.VoidDistillationRunResponse.run:type_name -> stillhouse.v1.DistillationRun
	9,  // 33: stillhouse.v1.DistillationService.CreateDistillationRun:input_type -> stillhouse.v1.CreateDistillationRunRequest
	11, // 34: stillhouse.v1.DistillationService.GetDistillationRun:input_type -> stillhouse.v1.GetDistillationRunRequest
	13, // 35: stillhouse.v1.DistillationService.ListDistillationRuns:input_type -> stillhouse.v1.ListDistillationRunsRequest
	15, // 36: stillhouse.v1.DistillationService.UpdateDistillationStatus:input_type -> stillhouse.v1.UpdateDistillationStatusRequest
	17, // 37: stillhouse.v1.DistillationService.AddDistillationCharge:input_type -> stillhouse.v1.AddDistillationChargeRequest
	19, // 38: stillhouse.v1.DistillationService.AddDistillationCut:input_type -> stillhouse.v1.AddDistillationCutRequest
	25, // 39: stillhouse.v1.DistillationService.RecordProductionGauge:input_type -> stillhouse.v1.RecordProductionGaugeRequest
	27, // 40: stillhouse.v1.DistillationService.VoidDistillationRun:input_type -> stillhouse.v1.VoidDistillationRunRequest
	21, // 41: stillhouse.v1.DistillationService.UpdateDistillationCut:input_type -> stillhouse.v1.UpdateDistillationCutRequest
	23, // 42: stillhouse.v1.DistillationService.DeleteDistillationCut:input_type -> stillhouse.v1.DeleteDistillationCutRequest
	10, // 43: stillhouse.v1.DistillationService.CreateDistillationRun:output_type -> stillhouse.v1.CreateDistillationRunResponse
	12, // 44: stillhouse.v1.DistillationService.GetDistillationRun:output_type -> stillhouse.v1.GetDistillationRunResponse
	14, // 45: stillhouse.v1.DistillationService.ListDistillationRuns:output_type -> stillhouse.v1.ListDistillationRunsResponse
	16, // 46: stillhouse.v1.DistillationService.UpdateDistillationStatus:output_type -> stillhouse.v1.UpdateDistillationStatusResponse
	18, // 47: stillhouse.v1.DistillationService.AddDistillationCharge:output_type -> stillhouse.v1.AddDistillationChargeResponse
	20, // 48: stillhouse.v1.DistillationService.AddDistillationCut:output_type -> stillhouse.v1.AddDistillationCutResponse
	26, // 49: stillhouse.v1.DistillationService.RecordProductionGauge:output_type -> stillhouse.v1.RecordProductionGaugeResponse
	28, // 50: stillhouse.v1.DistillationService.VoidDistillationRun:output_type -> stillhouse.v1.VoidDistillationRunResponse
	22, // 51: stillhouse.v1.DistillationService.UpdateDistillationCut:output_type -> stillhouse.v1.UpdateDistillationCutResponse
	24, // 52: stillhouse.v1.DistillationService.DeleteDistillationCut:output_type -> stillhouse.v1.DeleteDistillationCutResponse
	43, // [43:53] is the sub-list for method output_type
	33, // [33:43] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_stillhouse_v1_distillation_proto_init() }
func file_stillhouse_v1_distillation_proto_init() {
	if File_stillhouse_v1_distillation_proto != nil {
		return
	}
	file_stillhouse_v1_instrument_proto_init()
	file_stillhouse_v1_alcoholometry_proto_init()
	file_stillhouse_v1_bulk_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillhouse_v1_distillation_proto_rawDesc), len(file_stillhouse_v1_distillation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stillhouse_v1_distillation_proto_goTypes,
		DependencyIndexes: file_stillhouse_v1_distillation_proto_depIdxs,
		EnumInfos:         file_stillhouse_v1_distillation_proto_enumTypes,
		MessageInfos:      file_stillhouse_v1_distillation_proto_msgTypes,
	}.Build()
	File_stillhouse_v1_distillation_proto = out.File
	file_stillhouse_v1_distillation_proto_goTypes = nil
	file_stillhouse_v1_distillation_proto_depIdxs = nil
}
