// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stillhouse/v1/recipe.proto

package stillhousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpiritKind int32

const (
	SpiritKind_SPIRIT_KIND_UNSPECIFIED     SpiritKind = 0
	SpiritKind_SPIRIT_KIND_WHISKY          SpiritKind = 1
	SpiritKind_SPIRIT_KIND_CANADIAN_WHISKY SpiritKind = 2
	SpiritKind_SPIRIT_KIND_RYE_WHISKY      SpiritKind = 3
	SpiritKind_SPIRIT_KIND_GIN             SpiritKind = 4
	SpiritKind_SPIRIT_KIND_VODKA           SpiritKind = 5
	SpiritKind_SPIRIT_KIND_RUM             SpiritKind = 6
	SpiritKind_SPIRIT_KIND_BRANDY          SpiritKind = 7
	SpiritKind_SPIRIT_KIND_LIQUEUR         SpiritKind = 8
	SpiritKind_SPIRIT_KIND_OTHER           SpiritKind = 9
)

// Enum value maps for SpiritKind.
var (
	SpiritKind_name = map[int32]string{
		0: "SPIRIT_KIND_UNSPECIFIED",
		1: "SPIRIT_KIND_WHISKY",
		2: "SPIRIT_KIND_CANADIAN_WHISKY",
		3: "SPIRIT_KIND_RYE_WHISKY",
		4: "SPIRIT_KIND_GIN",
		5: "SPIRIT_KIND_VODKA",
		6: "SPIRIT_KIND_RUM",
		7: "SPIRIT_KIND_BRANDY",
		8: "SPIRIT_KIND_LIQUEUR",
		9: "SPIRIT_KIND_OTHER",
	}
	SpiritKind_value = map[string]int32{
		"SPIRIT_KIND_UNSPECIFIED":     0,
		"SPIRIT_KIND_WHISKY":          1,
		"SPIRIT_KIND_CANADIAN_WHISKY": 2,
		"SPIRIT_KIND_RYE_WHISKY":      3,
		"SPIRIT_KIND_GIN":             4,
		"SPIRIT_KIND_VODKA":           5,
		"SPIRIT_KIND_RUM":             6,
		"SPIRIT_KIND_BRANDY":          7,
		"SPIRIT_KIND_LIQUEUR":         8,
		"SPIRIT_KIND_OTHER":           9,
	}
)

func (x SpiritKind) Enum() *SpiritKind {
	p := new(SpiritKind)
	*p = x
	return p
}

func (x SpiritKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpiritKind) Descriptor() protoreflect.EnumDescriptor {
	return file_stillhouse_v1_recipe_proto_enumTypes[0].Descriptor()
}

func (SpiritKind) Type() protoreflect.EnumType {
	return &file_stillhouse_v1_recipe_proto_enumTypes[0]
}

func (x SpiritKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpiritKind.Descriptor instead.
func (SpiritKind) EnumDescriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{0}
}

type Recipe struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SpiritKind       SpiritKind             `protobuf:"varint,4,opt,name=spirit_kind,json=spiritKind,proto3,enum=stillhouse.v1.SpiritKind" json:"spirit_kind,omitempty"`
	Archived         bool                   `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	CurrentVersionId string                 `protobuf:"bytes,6,opt,name=current_version_id,json=currentVersionId,proto3" json:"current_version_id,omitempty"` // empty until first version saved
	Notes            string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *Recipe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipe) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Recipe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipe) GetSpiritKind() SpiritKind {
	if x != nil {
		return x.SpiritKind
	}
	return SpiritKind_SPIRIT_KIND_UNSPECIFIED
}

func (x *Recipe) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Recipe) GetCurrentVersionId() string {
	if x != nil {
		return x.CurrentVersionId
	}
	return ""
}

func (x *Recipe) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Recipe) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Recipe) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RecipeVersion struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId                string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RecipeId                string                 `protobuf:"bytes,3,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	VersionNo               int32                  `protobuf:"varint,4,opt,name=version_no,json=versionNo,proto3" json:"version_no,omitempty"`
	Notes                   string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	MashEfficiencyPct       float64                `protobuf:"fixed64,6,opt,name=mash_efficiency_pct,json=mashEfficiencyPct,proto3" json:"mash_efficiency_pct,omitempty"`
	FermentEfficiencyPct    float64                `protobuf:"fixed64,7,opt,name=ferment_efficiency_pct,json=fermentEfficiencyPct,proto3" json:"ferment_efficiency_pct,omitempty"`
	DistillationRecoveryPct float64                `protobuf:"fixed64,8,opt,name=distillation_recovery_pct,json=distillationRecoveryPct,proto3" json:"distillation_recovery_pct,omitempty"`
	TargetWaterL            float64                `protobuf:"fixed64,9,opt,name=target_water_l,json=targetWaterL,proto3" json:"target_water_l,omitempty"`
	TargetWaterLSet         bool                   `protobuf:"varint,10,opt,name=target_water_l_set,json=targetWaterLSet,proto3" json:"target_water_l_set,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ingredients             []*RecipeIngredient    `protobuf:"bytes,12,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RecipeVersion) Reset() {
	*x = RecipeVersion{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeVersion) ProtoMessage() {}

func (x *RecipeVersion) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeVersion.ProtoReflect.Descriptor instead.
func (*RecipeVersion) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *RecipeVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeVersion) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecipeVersion) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *RecipeVersion) GetVersionNo() int32 {
	if x != nil {
		return x.VersionNo
	}
	return 0
}

func (x *RecipeVersion) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RecipeVersion) GetMashEfficiencyPct() float64 {
	if x != nil {
		return x.MashEfficiencyPct
	}
	return 0
}

func (x *RecipeVersion) GetFermentEfficiencyPct() float64 {
	if x != nil {
		return x.FermentEfficiencyPct
	}
	return 0
}

func (x *RecipeVersion) GetDistillationRecoveryPct() float64 {
	if x != nil {
		return x.DistillationRecoveryPct
	}
	return 0
}

func (x *RecipeVersion) GetTargetWaterL() float64 {
	if x != nil {
		return x.TargetWaterL
	}
	return 0
}

func (x *RecipeVersion) GetTargetWaterLSet() bool {
	if x != nil {
		return x.TargetWaterLSet
	}
	return false
}

func (x *RecipeVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecipeVersion) GetIngredients() []*RecipeIngredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type RecipeIngredient struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipeVersionId       string                 `protobuf:"bytes,2,opt,name=recipe_version_id,json=recipeVersionId,proto3" json:"recipe_version_id,omitempty"`
	MaterialId            string                 `protobuf:"bytes,3,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	MaterialName          string                 `protobuf:"bytes,4,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"` // denormalized for display
	MaterialKind          MaterialKind           `protobuf:"varint,5,opt,name=material_kind,json=materialKind,proto3,enum=stillhouse.v1.MaterialKind" json:"material_kind,omitempty"`
	MaterialExtractPct    float64                `protobuf:"fixed64,6,opt,name=material_extract_pct,json=materialExtractPct,proto3" json:"material_extract_pct,omitempty"` // 0 if not set
	MaterialExtractPctSet bool                   `protobuf:"varint,7,opt,name=material_extract_pct_set,json=materialExtractPctSet,proto3" json:"material_extract_pct_set,omitempty"`
	Quantity              float64                `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Uom                   string                 `protobuf:"bytes,9,opt,name=uom,proto3" json:"uom,omitempty"`
	Notes                 string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	SortOrder             int32                  `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RecipeIngredient) Reset() {
	*x = RecipeIngredient{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeIngredient) ProtoMessage() {}

func (x *RecipeIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeIngredient.ProtoReflect.Descriptor instead.
func (*RecipeIngredient) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *RecipeIngredient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeIngredient) GetRecipeVersionId() string {
	if x != nil {
		return x.RecipeVersionId
	}
	return ""
}

func (x *RecipeIngredient) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *RecipeIngredient) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *RecipeIngredient) GetMaterialKind() MaterialKind {
	if x != nil {
		return x.MaterialKind
	}
	return MaterialKind_MATERIAL_KIND_UNSPECIFIED
}

func (x *RecipeIngredient) GetMaterialExtractPct() float64 {
	if x != nil {
		return x.MaterialExtractPct
	}
	return 0
}

func (x *RecipeIngredient) GetMaterialExtractPctSet() bool {
	if x != nil {
		return x.MaterialExtractPctSet
	}
	return false
}

func (x *RecipeIngredient) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecipeIngredient) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

func (x *RecipeIngredient) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RecipeIngredient) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// Projection breakdown produced from a RecipeVersion + a per-stage efficiency
// set. Wash volume/ABV are only populated when target_water_l is set.
type RecipeProjection struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Lines                []*RecipeProjectionLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	TotalProjectedLaa    float64                 `protobuf:"fixed64,2,opt,name=total_projected_laa,json=totalProjectedLaa,proto3" json:"total_projected_laa,omitempty"`
	ProjectedWashVolumeL float64                 `protobuf:"fixed64,3,opt,name=projected_wash_volume_l,json=projectedWashVolumeL,proto3" json:"projected_wash_volume_l,omitempty"`
	ProjectedWashAbvPct  float64                 `protobuf:"fixed64,4,opt,name=projected_wash_abv_pct,json=projectedWashAbvPct,proto3" json:"projected_wash_abv_pct,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecipeProjection) Reset() {
	*x = RecipeProjection{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeProjection) ProtoMessage() {}

func (x *RecipeProjection) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeProjection.ProtoReflect.Descriptor instead.
func (*RecipeProjection) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *RecipeProjection) GetLines() []*RecipeProjectionLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *RecipeProjection) GetTotalProjectedLaa() float64 {
	if x != nil {
		return x.TotalProjectedLaa
	}
	return 0
}

func (x *RecipeProjection) GetProjectedWashVolumeL() float64 {
	if x != nil {
		return x.ProjectedWashVolumeL
	}
	return 0
}

func (x *RecipeProjection) GetProjectedWashAbvPct() float64 {
	if x != nil {
		return x.ProjectedWashAbvPct
	}
	return 0
}

type RecipeProjectionLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaterialId     string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	MaterialName   string                 `protobuf:"bytes,2,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	Quantity       float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Uom            string                 `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	FermentableKg  float64                `protobuf:"fixed64,5,opt,name=fermentable_kg,json=fermentableKg,proto3" json:"fermentable_kg,omitempty"`
	ExtractFreedKg float64                `protobuf:"fixed64,6,opt,name=extract_freed_kg,json=extractFreedKg,proto3" json:"extract_freed_kg,omitempty"`
	EthanolMassKg  float64                `protobuf:"fixed64,7,opt,name=ethanol_mass_kg,json=ethanolMassKg,proto3" json:"ethanol_mass_kg,omitempty"`
	EthanolVolumeL float64                `protobuf:"fixed64,8,opt,name=ethanol_volume_l,json=ethanolVolumeL,proto3" json:"ethanol_volume_l,omitempty"`
	ProjectedLaa   float64                `protobuf:"fixed64,9,opt,name=projected_laa,json=projectedLaa,proto3" json:"projected_laa,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecipeProjectionLine) Reset() {
	*x = RecipeProjectionLine{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeProjectionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeProjectionLine) ProtoMessage() {}

func (x *RecipeProjectionLine) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeProjectionLine.ProtoReflect.Descriptor instead.
func (*RecipeProjectionLine) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *RecipeProjectionLine) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *RecipeProjectionLine) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *RecipeProjectionLine) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecipeProjectionLine) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

func (x *RecipeProjectionLine) GetFermentableKg() float64 {
	if x != nil {
		return x.FermentableKg
	}
	return 0
}

func (x *RecipeProjectionLine) GetExtractFreedKg() float64 {
	if x != nil {
		return x.ExtractFreedKg
	}
	return 0
}

func (x *RecipeProjectionLine) GetEthanolMassKg() float64 {
	if x != nil {
		return x.EthanolMassKg
	}
	return 0
}

func (x *RecipeProjectionLine) GetEthanolVolumeL() float64 {
	if x != nil {
		return x.EthanolVolumeL
	}
	return 0
}

func (x *RecipeProjectionLine) GetProjectedLaa() float64 {
	if x != nil {
		return x.ProjectedLaa
	}
	return 0
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SpiritKind    SpiritKind             `protobuf:"varint,2,opt,name=spirit_kind,json=spiritKind,proto3,enum=stillhouse.v1.SpiritKind" json:"spirit_kind,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRecipeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeRequest) GetSpiritKind() SpiritKind {
	if x != nil {
		return x.SpiritKind
	}
	return SpiritKind_SPIRIT_KIND_UNSPECIFIED
}

func (x *CreateRecipeRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeResponse) Reset() {
	*x = CreateRecipeResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeResponse) ProtoMessage() {}

func (x *CreateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeResponse.ProtoReflect.Descriptor instead.
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type ListRecipesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeArchived bool                   `protobuf:"varint,1,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRecipesRequest) Reset() {
	*x = ListRecipesRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest) ProtoMessage() {}

func (x *ListRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *ListRecipesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListRecipesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesResponse) Reset() {
	*x = ListRecipesResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesResponse) ProtoMessage() {}

func (x *ListRecipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesResponse.ProtoReflect.Descriptor instead.
func (*ListRecipesResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *ListRecipesResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRecipeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recipe         *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	CurrentVersion *RecipeVersion         `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // unset if no version yet
	Projection     *RecipeProjection      `protobuf:"bytes,3,opt,name=projection,proto3" json:"projection,omitempty"`                               // computed from current_version
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecipeResponse) Reset() {
	*x = GetRecipeResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeResponse) ProtoMessage() {}

func (x *GetRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *GetRecipeResponse) GetCurrentVersion() *RecipeVersion {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *GetRecipeResponse) GetProjection() *RecipeProjection {
	if x != nil {
		return x.Projection
	}
	return nil
}

type ArchiveRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Archived      bool                   `protobuf:"varint,2,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRecipeRequest) Reset() {
	*x = ArchiveRecipeRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRecipeRequest) ProtoMessage() {}

func (x *ArchiveRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRecipeRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRecipeRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{11}
}

func (x *ArchiveRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArchiveRecipeRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type ArchiveRecipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRecipeResponse) Reset() {
	*x = ArchiveRecipeResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRecipeResponse) ProtoMessage() {}

func (x *ArchiveRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRecipeResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRecipeResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{12}
}

func (x *ArchiveRecipeResponse) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type RecipeIngredientInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Uom           string                 `protobuf:"bytes,3,opt,name=uom,proto3" json:"uom,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeIngredientInput) Reset() {
	*x = RecipeIngredientInput{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeIngredientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeIngredientInput) ProtoMessage() {}

func (x *RecipeIngredientInput) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeIngredientInput.ProtoReflect.Descriptor instead.
func (*RecipeIngredientInput) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{13}
}

func (x *RecipeIngredientInput) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *RecipeIngredientInput) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecipeIngredientInput) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

func (x *RecipeIngredientInput) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RecipeIngredientInput) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type SaveRecipeVersionRequest struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	RecipeId                string                   `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Notes                   string                   `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	MashEfficiencyPct       float64                  `protobuf:"fixed64,3,opt,name=mash_efficiency_pct,json=mashEfficiencyPct,proto3" json:"mash_efficiency_pct,omitempty"`
	FermentEfficiencyPct    float64                  `protobuf:"fixed64,4,opt,name=ferment_efficiency_pct,json=fermentEfficiencyPct,proto3" json:"ferment_efficiency_pct,omitempty"`
	DistillationRecoveryPct float64                  `protobuf:"fixed64,5,opt,name=distillation_recovery_pct,json=distillationRecoveryPct,proto3" json:"distillation_recovery_pct,omitempty"`
	TargetWaterL            float64                  `protobuf:"fixed64,6,opt,name=target_water_l,json=targetWaterL,proto3" json:"target_water_l,omitempty"`
	TargetWaterLSet         bool                     `protobuf:"varint,7,opt,name=target_water_l_set,json=targetWaterLSet,proto3" json:"target_water_l_set,omitempty"`
	Ingredients             []*RecipeIngredientInput `protobuf:"bytes,8,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SaveRecipeVersionRequest) Reset() {
	*x = SaveRecipeVersionRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRecipeVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRecipeVersionRequest) ProtoMessage() {}

func (x *SaveRecipeVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRecipeVersionRequest.ProtoReflect.Descriptor instead.
func (*SaveRecipeVersionRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{14}
}

func (x *SaveRecipeVersionRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *SaveRecipeVersionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *SaveRecipeVersionRequest) GetMashEfficiencyPct() float64 {
	if x != nil {
		return x.MashEfficiencyPct
	}
	return 0
}

func (x *SaveRecipeVersionRequest) GetFermentEfficiencyPct() float64 {
	if x != nil {
		return x.FermentEfficiencyPct
	}
	return 0
}

func (x *SaveRecipeVersionRequest) GetDistillationRecoveryPct() float64 {
	if x != nil {
		return x.DistillationRecoveryPct
	}
	return 0
}

func (x *SaveRecipeVersionRequest) GetTargetWaterL() float64 {
	if x != nil {
		return x.TargetWaterL
	}
	return 0
}

func (x *SaveRecipeVersionRequest) GetTargetWaterLSet() bool {
	if x != nil {
		return x.TargetWaterLSet
	}
	return false
}

func (x *SaveRecipeVersionRequest) GetIngredients() []*RecipeIngredientInput {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type SaveRecipeVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *RecipeVersion         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Projection    *RecipeProjection      `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRecipeVersionResponse) Reset() {
	*x = SaveRecipeVersionResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRecipeVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRecipeVersionResponse) ProtoMessage() {}

func (x *SaveRecipeVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRecipeVersionResponse.ProtoReflect.Descriptor instead.
func (*SaveRecipeVersionResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{15}
}

func (x *SaveRecipeVersionResponse) GetVersion() *RecipeVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SaveRecipeVersionResponse) GetProjection() *RecipeProjection {
	if x != nil {
		return x.Projection
	}
	return nil
}

type ListRecipeVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipeVersionsRequest) Reset() {
	*x = ListRecipeVersionsRequest{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipeVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeVersionsRequest) ProtoMessage() {}

func (x *ListRecipeVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListRecipeVersionsRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{16}
}

func (x *ListRecipeVersionsRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

type ListRecipeVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*RecipeVersion       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipeVersionsResponse) Reset() {
	*x = ListRecipeVersionsResponse{}
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipeVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipeVersionsResponse) ProtoMessage() {}

func (x *ListRecipeVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_recipe_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipeVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListRecipeVersionsResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_recipe_proto_rawDescGZIP(), []int{17}
}

func (x *ListRecipeVersionsResponse) GetVersions() []*RecipeVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_stillhouse_v1_recipe_proto protoreflect.FileDescriptor

const file_stillhouse_v1_recipe_proto_rawDesc = "" +
	"\n" +
	"\x1astillhouse/v1/recipe.proto\x12\rstillhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cstillhouse/v1/material.proto\"\xdb\x02\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12:\n" +
	"\vspirit_kind\x18\x04 \x01(\x0e2\x19.stillhouse.v1.SpiritKindR\n" +
	"spiritKind\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x12,\n" +
	"\x12current_version_id\x18\x06 \x01(\tR\x10currentVersionId\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x04\n" +
	"\rRecipeVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\trecipe_id\x18\x03 \x01(\tR\brecipeId\x12\x1d\n" +
	"\n" +
	"version_no\x18\x04 \x01(\x05R\tversionNo\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12.\n" +
	"\x13mash_efficiency_pct\x18\x06 \x01(\x01R\x11mashEfficiencyPct\x124\n" +
	"\x16ferment_efficiency_pct\x18\a \x01(\x01R\x14fermentEfficiencyPct\x12:\n" +
	"\x19distillation_recovery_pct\x18\b \x01(\x01R\x17distillationRecoveryPct\x12$\n" +
	"\x0etarget_water_l\x18\t \x01(\x01R\ftargetWaterL\x12+\n" +
	"\x12target_water_l_set\x18\n" +
	" \x01(\bR\x0ftargetWaterLSet\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\vingredients\x18\f \x03(\v2\x1f.stillhouse.v1.RecipeIngredientR\vingredients\"\xa4\x03\n" +
	"\x10RecipeIngredient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11recipe_version_id\x18\x02 \x01(\tR\x0frecipeVersionId\x12\x1f\n" +
	"\vmaterial_id\x18\x03 \x01(\tR\n" +
	"materialId\x12#\n" +
	"\rmaterial_name\x18\x04 \x01(\tR\fmaterialName\x12@\n" +
	"\rmaterial_kind\x18\x05 \x01(\x0e2\x1b.stillhouse.v1.MaterialKindR\fmaterialKind\x120\n" +
	"\x14material_extract_pct\x18\x06 \x01(\x01R\x12materialExtractPct\x127\n" +
	"\x18material_extract_pct_set\x18\a \x01(\bR\x15materialExtractPctSet\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12\x10\n" +
	"\x03uom\x18\t \x01(\tR\x03uom\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\x05R\tsortOrder\"\xe9\x01\n" +
	"\x10RecipeProjection\x129\n" +
	"\x05lines\x18\x01 \x03(\v2#.stillhouse.v1.RecipeProjectionLineR\x05lines\x12.\n" +
	"\x13total_projected_laa\x18\x02 \x01(\x01R\x11totalProjectedLaa\x125\n" +
	"\x17projected_wash_volume_l\x18\x03 \x01(\x01R\x14projectedWashVolumeL\x123\n" +
	"\x16projected_wash_abv_pct\x18\x04 \x01(\x01R\x13projectedWashAbvPct\"\xd2\x02\n" +
	"\x14RecipeProjectionLine\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12#\n" +
	"\rmaterial_name\x18\x02 \x01(\tR\fmaterialName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x10\n" +
	"\x03uom\x18\x04 \x01(\tR\x03uom\x12%\n" +
	"\x0efermentable_kg\x18\x05 \x01(\x01R\rfermentableKg\x12(\n" +
	"\x10extract_freed_kg\x18\x06 \x01(\x01R\x0eextractFreedKg\x12&\n" +
	"\x0fethanol_mass_kg\x18\a \x01(\x01R\rethanolMassKg\x12(\n" +
	"\x10ethanol_volume_l\x18\b \x01(\x01R\x0eethanolVolumeL\x12#\n" +
	"\rprojected_laa\x18\t \x01(\x01R\fprojectedLaa\"{\n" +
	"\x13CreateRecipeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\vspirit_kind\x18\x02 \x01(\x0e2\x19.stillhouse.v1.SpiritKindR\n" +
	"spiritKind\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"E\n" +
	"\x14CreateRecipeResponse\x12-\n" +
	"\x06recipe\x18\x01 \x01(\v2\x15.stillhouse.v1.RecipeR\x06recipe\"?\n" +
	"\x12ListRecipesRequest\x12)\n" +
	"\x10include_archived\x18\x01 \x01(\bR\x0fincludeArchived\"F\n" +
	"\x13ListRecipesResponse\x12/\n" +
	"\arecipes\x18\x01 \x03(\v2\x15.stillhouse.v1.RecipeR\arecipes\"\"\n" +
	"\x10GetRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xca\x01\n" +
	"\x11GetRecipeResponse\x12-\n" +
	"\x06recipe\x18\x01 \x01(\v2\x15.stillhouse.v1.RecipeR\x06recipe\x12E\n" +
	"\x0fcurrent_version\x18\x02 \x01(\v2\x1c.stillhouse.v1.RecipeVersionR\x0ecurrentVersion\x12?\n" +
	"\n" +
	"projection\x18\x03 \x01(\v2\x1f.stillhouse.v1.RecipeProjectionR\n" +
	"projection\"B\n" +
	"\x14ArchiveRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\"F\n" +
	"\x15ArchiveRecipeResponse\x12-\n" +
	"\x06recipe\x18\x01 \x01(\v2\x15.stillhouse.v1.RecipeR\x06recipe\"\x9b\x01\n" +
	"\x15RecipeIngredientInput\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x10\n" +
	"\x03uom\x18\x03 \x01(\tR\x03uom\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"\x8a\x03\n" +
	"\x18SaveRecipeVersionRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\x12.\n" +
	"\x13mash_efficiency_pct\x18\x03 \x01(\x01R\x11mashEfficiencyPct\x124\n" +
	"\x16ferment_efficiency_pct\x18\x04 \x01(\x01R\x14fermentEfficiencyPct\x12:\n" +
	"\x19distillation_recovery_pct\x18\x05 \x01(\x01R\x17distillationRecoveryPct\x12$\n" +
	"\x0etarget_water_l\x18\x06 \x01(\x01R\ftargetWaterL\x12+\n" +
	"\x12target_water_l_set\x18\a \x01(\bR\x0ftargetWaterLSet\x12F\n" +
	"\vingredients\x18\b \x03(\v2$.stillhouse.v1.RecipeIngredientInputR\vingredients\"\x94\x01\n" +
	"\x19SaveRecipeVersionResponse\x126\n" +
	"\aversion\x18\x01 \x01(\v2\x1c.stillhouse.v1.RecipeVersionR\aversion\x12?\n" +
	"\n" +
	"projection\x18\x02 \x01(\v2\x1f.stillhouse.v1.RecipeProjectionR\n" +
	"projection\"8\n" +
	"\x19ListRecipeVersionsRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\"V\n" +
	"\x1aListRecipeVersionsResponse\x128\n" +
	"\bversions\x18\x01 \x03(\v2\x1c.stillhouse.v1.RecipeVersionR\bversions*\x87\x02\n" +
	"\n" +
	"SpiritKind\x12\x1b\n" +
	"\x17SPIRIT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SPIRIT_KIND_WHISKY\x10\x01\x12\x1f\n" +
	"\x1bSPIRIT_KIND_CANADIAN_WHISKY\x10\x02\x12\x1a\n" +
	"\x16SPIRIT_KIND_RYE_WHISKY\x10\x03\x12\x13\n" +
	"\x0fSPIRIT_KIND_GIN\x10\x04\x12\x15\n" +
	"\x11SPIRIT_KIND_VODKA\x10\x05\x12\x13\n" +
	"\x0fSPIRIT_KIND_RUM\x10\x06\x12\x16\n" +
	"\x12SPIRIT_KIND_BRANDY\x10\a\x12\x17\n" +
	"\x13SPIRIT_KIND_LIQUEUR\x10\b\x12\x15\n" +
	"\x11SPIRIT_KIND_OTHER\x10\t2\xbd\x04\n" +
	"\rRecipeService\x12W\n" +
	"\fCreateRecipe\x12\".stillhouse.v1.CreateRecipeRequest\x1a#.stillhouse.v1.CreateRecipeResponse\x12T\n" +
	"\vListRecipes\x12!.stillhouse.v1.ListRecipesRequest\x1a\".stillhouse.v1.ListRecipesResponse\x12N\n" +
	"\tGetRecipe\x12\x1f.stillhouse.v1.GetRecipeRequest\x1a .stillhouse.v1.GetRecipeResponse\x12Z\n" +
	"\rArchiveRecipe\x12#.stillhouse.v1.ArchiveRecipeRequest\x1a$.stillhouse.v1.ArchiveRecipeResponse\x12f\n" +
	"\x11SaveRecipeVersion\x12'.stillhouse.v1.SaveRecipeVersionRequest\x1a(.stillhouse.v1.SaveRecipeVersionResponse\x12i\n" +
	"\x12ListRecipeVersions\x12(.stillhouse.v1.ListRecipeVersionsRequest\x1a).stillhouse.v1.ListRecipeVersionsResponseB\xcf\x01\n" +
	"\x11com.stillhouse.v1B\vRecipeProtoP\x01ZXgithub.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1;stillhousev1\xa2\x02\x03SXX\xaa\x02\rStillhouse.V1\xca\x02\rStillhouse\\V1\xe2\x02\x19Stillhouse\\V1\\GPBMetadata\xea\x02\x0eStillhouse::V1b\x06proto3"

var (
	file_stillhouse_v1_recipe_proto_rawDescOnce sync.Once
	file_stillhouse_v1_recipe_proto_rawDescData []byte
)

func file_stillhouse_v1_recipe_proto_rawDescGZIP() []byte {
	file_stillhouse_v1_recipe_proto_rawDescOnce.Do(func() {
		file_stillhouse_v1_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillhouse_v1_recipe_proto_rawDesc), len(file_stillhouse_v1_recipe_proto_rawDesc)))
	})
	return file_stillhouse_v1_recipe_proto_rawDescData
}

var file_stillhouse_v1_recipe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stillhouse_v1_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_stillhouse_v1_recipe_proto_goTypes = []any{
	(SpiritKind)(0),                    // 0: stillhouse.v1.SpiritKind
	(*Recipe)(nil),                     // 1: stillhouse.v1.Recipe
	(*RecipeVersion)(nil),              // 2: stillhouse.v1.RecipeVersion
	(*RecipeIngredient)(nil),           // 3: stillhouse.v1.RecipeIngredient
	(*RecipeProjection)(nil),           // 4: stillhouse.v1.RecipeProjection
	(*RecipeProjectionLine)(nil),       // 5: stillhouse.v1.RecipeProjectionLine
	(*CreateRecipeRequest)(nil),        // 6: stillhouse.v1.CreateRecipeRequest
	(*CreateRecipeResponse)(nil),       // 7: stillhouse.v1.CreateRecipeResponse
	(*ListRecipesRequest)(nil),         // 8: stillhouse.v1.ListRecipesRequest
	(*ListRecipesResponse)(nil),        // 9: stillhouse.v1.ListRecipesResponse
	(*GetRecipeRequest)(nil),           // 10: stillhouse.v1.GetRecipeRequest
	(*GetRecipeResponse)(nil),          // 11: stillhouse.v1.GetRecipeResponse
	(*ArchiveRecipeRequest)(nil),       // 12: stillhouse.v1.ArchiveRecipeRequest
	(*ArchiveRecipeResponse)(nil),      // 13: stillhouse.v1.ArchiveRecipeResponse
	(*RecipeIngredientInput)(nil),      // 14: stillhouse.v1.RecipeIngredientInput
	(*SaveRecipeVersionRequest)(nil),   // 15: stillhouse.v1.SaveRecipeVersionRequest
	(*SaveRecipeVersionResponse)(nil),  // 16: stillhouse.v1.SaveRecipeVersionResponse
	(*ListRecipeVersionsRequest)(nil),  // 17: stillhouse.v1.ListRecipeVersionsRequest
	(*ListRecipeVersionsResponse)(nil), // 18: stillhouse.v1.ListRecipeVersionsResponse
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
	(MaterialKind)(0),                  // 20: stillhouse.v1.MaterialKind
}
var file_stillhouse_v1_recipe_proto_depIdxs = []int32{
	0,  // 0: stillhouse.v1.Recipe.spirit_kind:type_name -> stillhouse.v1.SpiritKind
	19, // 1: stillhouse.v1.Recipe.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: stillhouse.v1.Recipe.updated_at:type_name -> google.protobuf.Timestamp
	19, // 3: stillhouse.v1.RecipeVersion.created_at:type_name -> google.protobuf.Timestamp
	3,  // 4: stillhouse.v1.RecipeVersion.ingredients:type_name -> stillhouse.v1.RecipeIngredient
	20, // 5: stillhouse.v1.RecipeIngredient.material_kind:type_name -> stillhouse.v1.MaterialKind
	5,  // 6: stillhouse.v1.RecipeProjection.lines:type_name -> stillhouse.v1.RecipeProjectionLine
	0,  // 7: stillhouse.v1.CreateRecipeRequest.spirit_kind:type_name -> stillhouse.v1.SpiritKind
	1,  // 8: stillhouse.v1.CreateRecipeResponse.recipe:type_name -> stillhouse.v1.Recipe
	1,  // 9: stillhouse.v1.ListRecipesResponse.recipes:type_name -> stillhouse.v1.Recipe
	1,  // 10: stillhouse.v1.GetRecipeResponse.recipe:type_name -> stillhouse.v1.Recipe
	2,  // 11: stillhouse.v1.GetRecipeResponse.current_version:type_name -> stillhouse.v1.RecipeVersion
	4,  // 12: stillhouse.v1.GetRecipeResponse.projection:type_name -> stillhouse.v1.RecipeProjection
	1,  // 13: stillhouse.v1.ArchiveRecipeResponse.recipe:type_name -> stillhouse.v1.Recipe
	14, // 14: stillhouse.v1.SaveRecipeVersionRequest.ingredients:type_name -> stillhouse.v1.RecipeIngredientInput
	2,  // 15: stillhouse.v1.SaveRecipeVersionResponse.version:type_name -> stillhouse.v1.RecipeVersion
	4,  // 16: stillhouse.v1.SaveRecipeVersionResponse.projection:type_name -> stillhouse.v1.RecipeProjection
	2,  // 17: stillhouse.v1.ListRecipeVersionsResponse.versions:type_name -> stillhouse.v1.RecipeVersion
	6,  // 18: stillhouse.v1.RecipeService.CreateRecipe:input_type -> stillhouse.v1.CreateRecipeRequest
	8,  // 19: stillhouse.v1.RecipeService.ListRecipes:input_type -> stillhouse.v1.ListRecipesRequest
	10, // 20: stillhouse.v1.RecipeService.GetRecipe:input_type -> stillhouse.v1.GetRecipeRequest
	12, // 21: stillhouse.v1.RecipeService.ArchiveRecipe:input_type -> stillhouse.v1.ArchiveRecipeRequest
	15, // 22: stillhouse.v1.RecipeService.SaveRecipeVersion:input_type -> stillhouse.v1.SaveRecipeVersionRequest
	17, // 23: stillhouse.v1.RecipeService.ListRecipeVersions:input_type -> stillhouse.v1.ListRecipeVersionsRequest
	7,  // 24: stillhouse.v1.RecipeService.CreateRecipe:output_type -> stillhouse.v1.CreateRecipeResponse
	9,  // 25: stillhouse.v1.RecipeService.ListRecipes:output_type -> stillhouse.v1.ListRecipesResponse
	11, // 26: stillhouse.v1.RecipeService.GetRecipe:output_type -> stillhouse.v1.GetRecipeResponse
	13, // 27: stillhouse.v1.RecipeService.ArchiveRecipe:output_type -> stillhouse.v1.ArchiveRecipeResponse
	16, // 28: stillhouse.v1.RecipeService.SaveRecipeVersion:output_type -> stillhouse.v1.SaveRecipeVersionResponse
	18, // 29: stillhouse.v1.RecipeService.ListRecipeVersions:output_type -> stillhouse.v1.ListRecipeVersionsResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_stillhouse_v1_recipe_proto_init() }
func file_stillhouse_v1_recipe_proto_init() {
	if File_stillhouse_v1_recipe_proto != nil {
		return
	}
	file_stillhouse_v1_material_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillhouse_v1_recipe_proto_rawDesc), len(file_stillhouse_v1_recipe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stillhouse_v1_recipe_proto_goTypes,
		DependencyIndexes: file_stillhouse_v1_recipe_proto_depIdxs,
		EnumInfos:         file_stillhouse_v1_recipe_proto_enumTypes,
		MessageInfos:      file_stillhouse_v1_recipe_proto_msgTypes,
	}.Build()
	File_stillhouse_v1_recipe_proto = out.File
	file_stillhouse_v1_recipe_proto_goTypes = nil
	file_stillhouse_v1_recipe_proto_depIdxs = nil
}
