// What needs making, and whether the plant can make it.
//
// Driven by actual demand — confirmed, unshipped order lines — rather
// than by a forecast. Stillhouse has no forecast, and a plan built on an
// invented one looks exactly as authoritative as a plan built on orders.
// PLAN F7 is where a forecast would go; until it exists this says what it
// is working from, on the page, every time.
//
// The other half of honesty here is the plant. A piece of equipment with
// no recorded capacity or no recorded run time cannot be planned against,
// and is returned with the reason rather than dropped — an empty schedule
// and a schedule that silently omitted half the still house look
// identical from the outside.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: stillhouse/v1/scheduling.proto

package stillhousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemandLine struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProductId    string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName  string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	BottleSizeMl int32                  `protobuf:"varint,3,opt,name=bottle_size_ml,json=bottleSizeMl,proto3" json:"bottle_size_ml,omitempty"`
	BottleAbvPct float64                `protobuf:"fixed64,4,opt,name=bottle_abv_pct,json=bottleAbvPct,proto3" json:"bottle_abv_pct,omitempty"`
	// Confirmed and unshipped. A real commitment, not a projection.
	BottlesOwed      int32  `protobuf:"varint,5,opt,name=bottles_owed,json=bottlesOwed,proto3" json:"bottles_owed,omitempty"`
	EarliestRequired string `protobuf:"bytes,6,opt,name=earliest_required,json=earliestRequired,proto3" json:"earliest_required,omitempty"` // ISO date; empty if no order gave one
	// Ours, here, released and not already picked onto an open shipment.
	BottlesOnHand    int32 `protobuf:"varint,7,opt,name=bottles_on_hand,json=bottlesOnHand,proto3" json:"bottles_on_hand,omitempty"`
	BottlesPicked    int32 `protobuf:"varint,8,opt,name=bottles_picked,json=bottlesPicked,proto3" json:"bottles_picked,omitempty"`
	BottlesAvailable int32 `protobuf:"varint,9,opt,name=bottles_available,json=bottlesAvailable,proto3" json:"bottles_available,omitempty"`
	// What is missing. Zero when stock covers the orders.
	Shortfall int32 `protobuf:"varint,10,opt,name=shortfall,proto3" json:"shortfall,omitempty"`
	// The alcohol that shortfall would need, so it can be compared against
	// what is actually in the tanks.
	ShortfallLaa float64 `protobuf:"fixed64,11,opt,name=shortfall_laa,json=shortfallLaa,proto3" json:"shortfall_laa,omitempty"`
	// True when the earliest required date has already passed and the
	// stock is not there.
	Late          bool `protobuf:"varint,12,opt,name=late,proto3" json:"late,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandLine) Reset() {
	*x = DemandLine{}
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandLine) ProtoMessage() {}

func (x *DemandLine) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandLine.ProtoReflect.Descriptor instead.
func (*DemandLine) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_scheduling_proto_rawDescGZIP(), []int{0}
}

func (x *DemandLine) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DemandLine) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *DemandLine) GetBottleSizeMl() int32 {
	if x != nil {
		return x.BottleSizeMl
	}
	return 0
}

func (x *DemandLine) GetBottleAbvPct() float64 {
	if x != nil {
		return x.BottleAbvPct
	}
	return 0
}

func (x *DemandLine) GetBottlesOwed() int32 {
	if x != nil {
		return x.BottlesOwed
	}
	return 0
}

func (x *DemandLine) GetEarliestRequired() string {
	if x != nil {
		return x.EarliestRequired
	}
	return ""
}

func (x *DemandLine) GetBottlesOnHand() int32 {
	if x != nil {
		return x.BottlesOnHand
	}
	return 0
}

func (x *DemandLine) GetBottlesPicked() int32 {
	if x != nil {
		return x.BottlesPicked
	}
	return 0
}

func (x *DemandLine) GetBottlesAvailable() int32 {
	if x != nil {
		return x.BottlesAvailable
	}
	return 0
}

func (x *DemandLine) GetShortfall() int32 {
	if x != nil {
		return x.Shortfall
	}
	return 0
}

func (x *DemandLine) GetShortfallLaa() float64 {
	if x != nil {
		return x.ShortfallLaa
	}
	return 0
}

func (x *DemandLine) GetLate() bool {
	if x != nil {
		return x.Late
	}
	return false
}

type PlannableEquipment struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind         EquipmentKind          `protobuf:"varint,3,opt,name=kind,proto3,enum=stillhouse.v1.EquipmentKind" json:"kind,omitempty"`
	Status       EquipmentStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=stillhouse.v1.EquipmentStatus" json:"status,omitempty"`
	CapacityL    float64                `protobuf:"fixed64,5,opt,name=capacity_l,json=capacityL,proto3" json:"capacity_l,omitempty"`
	CapacityLSet bool                   `protobuf:"varint,6,opt,name=capacity_l_set,json=capacityLSet,proto3" json:"capacity_l_set,omitempty"`
	// Observed from work orders that recorded a start and a finish; the
	// median, so one run left going over a weekend does not move it.
	ObservedMedianHours float64 `protobuf:"fixed64,7,opt,name=observed_median_hours,json=observedMedianHours,proto3" json:"observed_median_hours,omitempty"`
	ObservedRuns        int32   `protobuf:"varint,8,opt,name=observed_runs,json=observedRuns,proto3" json:"observed_runs,omitempty"`
	TypicalRunHours     float64 `protobuf:"fixed64,9,opt,name=typical_run_hours,json=typicalRunHours,proto3" json:"typical_run_hours,omitempty"`
	TypicalRunHoursSet  bool    `protobuf:"varint,10,opt,name=typical_run_hours_set,json=typicalRunHoursSet,proto3" json:"typical_run_hours_set,omitempty"`
	// Whether this can be planned against at all, and why not.
	Plannable bool   `protobuf:"varint,11,opt,name=plannable,proto3" json:"plannable,omitempty"`
	WhyNot    string `protobuf:"bytes,12,opt,name=why_not,json=whyNot,proto3" json:"why_not,omitempty"`
	// Work already on the board in the window.
	Scheduled []*ScheduledWork `protobuf:"bytes,13,rep,name=scheduled,proto3" json:"scheduled,omitempty"`
	// Hours the scheduled work is expected to take, from the observed
	// median where there is one and the recorded typical run otherwise.
	ScheduledHours float64 `protobuf:"fixed64,14,opt,name=scheduled_hours,json=scheduledHours,proto3" json:"scheduled_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlannableEquipment) Reset() {
	*x = PlannableEquipment{}
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlannableEquipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlannableEquipment) ProtoMessage() {}

func (x *PlannableEquipment) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlannableEquipment.ProtoReflect.Descriptor instead.
func (*PlannableEquipment) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_scheduling_proto_rawDescGZIP(), []int{1}
}

func (x *PlannableEquipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlannableEquipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlannableEquipment) GetKind() EquipmentKind {
	if x != nil {
		return x.Kind
	}
	return EquipmentKind_EQUIPMENT_KIND_UNSPECIFIED
}

func (x *PlannableEquipment) GetStatus() EquipmentStatus {
	if x != nil {
		return x.Status
	}
	return EquipmentStatus_EQUIPMENT_STATUS_UNSPECIFIED
}

func (x *PlannableEquipment) GetCapacityL() float64 {
	if x != nil {
		return x.CapacityL
	}
	return 0
}

func (x *PlannableEquipment) GetCapacityLSet() bool {
	if x != nil {
		return x.CapacityLSet
	}
	return false
}

func (x *PlannableEquipment) GetObservedMedianHours() float64 {
	if x != nil {
		return x.ObservedMedianHours
	}
	return 0
}

func (x *PlannableEquipment) GetObservedRuns() int32 {
	if x != nil {
		return x.ObservedRuns
	}
	return 0
}

func (x *PlannableEquipment) GetTypicalRunHours() float64 {
	if x != nil {
		return x.TypicalRunHours
	}
	return 0
}

func (x *PlannableEquipment) GetTypicalRunHoursSet() bool {
	if x != nil {
		return x.TypicalRunHoursSet
	}
	return false
}

func (x *PlannableEquipment) GetPlannable() bool {
	if x != nil {
		return x.Plannable
	}
	return false
}

func (x *PlannableEquipment) GetWhyNot() string {
	if x != nil {
		return x.WhyNot
	}
	return ""
}

func (x *PlannableEquipment) GetScheduled() []*ScheduledWork {
	if x != nil {
		return x.Scheduled
	}
	return nil
}

func (x *PlannableEquipment) GetScheduledHours() float64 {
	if x != nil {
		return x.ScheduledHours
	}
	return 0
}

type ScheduledWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkOrderId   string                 `protobuf:"bytes,1,opt,name=work_order_id,json=workOrderId,proto3" json:"work_order_id,omitempty"`
	WorkOrderNo   int32                  `protobuf:"varint,2,opt,name=work_order_no,json=workOrderNo,proto3" json:"work_order_no,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledFor  string                 `protobuf:"bytes,4,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"` // ISO date
	DueOn         string                 `protobuf:"bytes,5,opt,name=due_on,json=dueOn,proto3" json:"due_on,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledWork) Reset() {
	*x = ScheduledWork{}
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledWork) ProtoMessage() {}

func (x *ScheduledWork) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledWork.ProtoReflect.Descriptor instead.
func (*ScheduledWork) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_scheduling_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduledWork) GetWorkOrderId() string {
	if x != nil {
		return x.WorkOrderId
	}
	return ""
}

func (x *ScheduledWork) GetWorkOrderNo() int32 {
	if x != nil {
		return x.WorkOrderNo
	}
	return 0
}

func (x *ScheduledWork) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduledWork) GetScheduledFor() string {
	if x != nil {
		return x.ScheduledFor
	}
	return ""
}

func (x *ScheduledWork) GetDueOn() string {
	if x != nil {
		return x.DueOn
	}
	return ""
}

func (x *ScheduledWork) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProductionPlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The window the board covers. Empty defaults to the next four weeks.
	From          string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // ISO date
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`     // ISO date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionPlanRequest) Reset() {
	*x = ProductionPlanRequest{}
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionPlanRequest) ProtoMessage() {}

func (x *ProductionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionPlanRequest.ProtoReflect.Descriptor instead.
func (*ProductionPlanRequest) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_scheduling_proto_rawDescGZIP(), []int{3}
}

func (x *ProductionPlanRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ProductionPlanRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ProductionPlanResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Demand    []*DemandLine          `protobuf:"bytes,1,rep,name=demand,proto3" json:"demand,omitempty"`
	Equipment []*PlannableEquipment  `protobuf:"bytes,2,rep,name=equipment,proto3" json:"equipment,omitempty"`
	From      string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To        string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Total alcohol the shortfalls need, and what is actually available to
	// bottle: ours, here, and not in somebody else's cask.
	ShortfallLaa float64 `protobuf:"fixed64,5,opt,name=shortfall_laa,json=shortfallLaa,proto3" json:"shortfall_laa,omitempty"`
	AvailableLaa float64 `protobuf:"fixed64,6,opt,name=available_laa,json=availableLaa,proto3" json:"available_laa,omitempty"`
	// True when the shortfalls need more alcohol than there is. The one
	// number worth putting in front of somebody before they promise a date.
	ShortOfAlcohol bool `protobuf:"varint,7,opt,name=short_of_alcohol,json=shortOfAlcohol,proto3" json:"short_of_alcohol,omitempty"`
	// What this plan is working from, said on the page. Never empty.
	Basis string `protobuf:"bytes,8,opt,name=basis,proto3" json:"basis,omitempty"`
	// Things the plan could not take into account — plant with no capacity
	// recorded, orders with no required-by date. Named rather than dropped.
	BlindSpots    []string `protobuf:"bytes,9,rep,name=blind_spots,json=blindSpots,proto3" json:"blind_spots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionPlanResponse) Reset() {
	*x = ProductionPlanResponse{}
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionPlanResponse) ProtoMessage() {}

func (x *ProductionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stillhouse_v1_scheduling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionPlanResponse.ProtoReflect.Descriptor instead.
func (*ProductionPlanResponse) Descriptor() ([]byte, []int) {
	return file_stillhouse_v1_scheduling_proto_rawDescGZIP(), []int{4}
}

func (x *ProductionPlanResponse) GetDemand() []*DemandLine {
	if x != nil {
		return x.Demand
	}
	return nil
}

func (x *ProductionPlanResponse) GetEquipment() []*PlannableEquipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *ProductionPlanResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ProductionPlanResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ProductionPlanResponse) GetShortfallLaa() float64 {
	if x != nil {
		return x.ShortfallLaa
	}
	return 0
}

func (x *ProductionPlanResponse) GetAvailableLaa() float64 {
	if x != nil {
		return x.AvailableLaa
	}
	return 0
}

func (x *ProductionPlanResponse) GetShortOfAlcohol() bool {
	if x != nil {
		return x.ShortOfAlcohol
	}
	return false
}

func (x *ProductionPlanResponse) GetBasis() string {
	if x != nil {
		return x.Basis
	}
	return ""
}

func (x *ProductionPlanResponse) GetBlindSpots() []string {
	if x != nil {
		return x.BlindSpots
	}
	return nil
}

var File_stillhouse_v1_scheduling_proto protoreflect.FileDescriptor

const file_stillhouse_v1_scheduling_proto_rawDesc = "" +
	"\n" +
	"\x1estillhouse/v1/scheduling.proto\x12\rstillhouse.v1\x1a\x1dstillhouse/v1/equipment.proto\"\xbd\x03\n" +
	"\n" +
	"DemandLine\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12$\n" +
	"\x0ebottle_size_ml\x18\x03 \x01(\x05R\fbottleSizeMl\x12$\n" +
	"\x0ebottle_abv_pct\x18\x04 \x01(\x01R\fbottleAbvPct\x12!\n" +
	"\fbottles_owed\x18\x05 \x01(\x05R\vbottlesOwed\x12+\n" +
	"\x11earliest_required\x18\x06 \x01(\tR\x10earliestRequired\x12&\n" +
	"\x0fbottles_on_hand\x18\a \x01(\x05R\rbottlesOnHand\x12%\n" +
	"\x0ebottles_picked\x18\b \x01(\x05R\rbottlesPicked\x12+\n" +
	"\x11bottles_available\x18\t \x01(\x05R\x10bottlesAvailable\x12\x1c\n" +
	"\tshortfall\x18\n" +
	" \x01(\x05R\tshortfall\x12#\n" +
	"\rshortfall_laa\x18\v \x01(\x01R\fshortfallLaa\x12\x12\n" +
	"\x04late\x18\f \x01(\bR\x04late\"\xbb\x04\n" +
	"\x12PlannableEquipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.stillhouse.v1.EquipmentKindR\x04kind\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.stillhouse.v1.EquipmentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"capacity_l\x18\x05 \x01(\x01R\tcapacityL\x12$\n" +
	"\x0ecapacity_l_set\x18\x06 \x01(\bR\fcapacityLSet\x122\n" +
	"\x15observed_median_hours\x18\a \x01(\x01R\x13observedMedianHours\x12#\n" +
	"\robserved_runs\x18\b \x01(\x05R\fobservedRuns\x12*\n" +
	"\x11typical_run_hours\x18\t \x01(\x01R\x0ftypicalRunHours\x121\n" +
	"\x15typical_run_hours_set\x18\n" +
	" \x01(\bR\x12typicalRunHoursSet\x12\x1c\n" +
	"\tplannable\x18\v \x01(\bR\tplannable\x12\x17\n" +
	"\awhy_not\x18\f \x01(\tR\x06whyNot\x12:\n" +
	"\tscheduled\x18\r \x03(\v2\x1c.stillhouse.v1.ScheduledWorkR\tscheduled\x12'\n" +
	"\x0fscheduled_hours\x18\x0e \x01(\x01R\x0escheduledHours\"\xc1\x01\n" +
	"\rScheduledWork\x12\"\n" +
	"\rwork_order_id\x18\x01 \x01(\tR\vworkOrderId\x12\"\n" +
	"\rwork_order_no\x18\x02 \x01(\x05R\vworkOrderNo\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12#\n" +
	"\rscheduled_for\x18\x04 \x01(\tR\fscheduledFor\x12\x15\n" +
	"\x06due_on\x18\x05 \x01(\tR\x05dueOn\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\";\n" +
	"\x15ProductionPlanRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xdb\x02\n" +
	"\x16ProductionPlanResponse\x121\n" +
	"\x06demand\x18\x01 \x03(\v2\x19.stillhouse.v1.DemandLineR\x06demand\x12?\n" +
	"\tequipment\x18\x02 \x03(\v2!.stillhouse.v1.PlannableEquipmentR\tequipment\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12#\n" +
	"\rshortfall_laa\x18\x05 \x01(\x01R\fshortfallLaa\x12#\n" +
	"\ravailable_laa\x18\x06 \x01(\x01R\favailableLaa\x12(\n" +
	"\x10short_of_alcohol\x18\a \x01(\bR\x0eshortOfAlcohol\x12\x14\n" +
	"\x05basis\x18\b \x01(\tR\x05basis\x12\x1f\n" +
	"\vblind_spots\x18\t \x03(\tR\n" +
	"blindSpots2r\n" +
	"\x11SchedulingService\x12]\n" +
	"\x0eProductionPlan\x12$.stillhouse.v1.ProductionPlanRequest\x1a%.stillhouse.v1.ProductionPlanResponseB\xd3\x01\n" +
	"\x11com.stillhouse.v1B\x0fSchedulingProtoP\x01ZXgithub.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1;stillhousev1\xa2\x02\x03SXX\xaa\x02\rStillhouse.V1\xca\x02\rStillhouse\\V1\xe2\x02\x19Stillhouse\\V1\\GPBMetadata\xea\x02\x0eStillhouse::V1b\x06proto3"

var (
	file_stillhouse_v1_scheduling_proto_rawDescOnce sync.Once
	file_stillhouse_v1_scheduling_proto_rawDescData []byte
)

func file_stillhouse_v1_scheduling_proto_rawDescGZIP() []byte {
	file_stillhouse_v1_scheduling_proto_rawDescOnce.Do(func() {
		file_stillhouse_v1_scheduling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stillhouse_v1_scheduling_proto_rawDesc), len(file_stillhouse_v1_scheduling_proto_rawDesc)))
	})
	return file_stillhouse_v1_scheduling_proto_rawDescData
}

var file_stillhouse_v1_scheduling_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stillhouse_v1_scheduling_proto_goTypes = []any{
	(*DemandLine)(nil),             // 0: stillhouse.v1.DemandLine
	(*PlannableEquipment)(nil),     // 1: stillhouse.v1.PlannableEquipment
	(*ScheduledWork)(nil),          // 2: stillhouse.v1.ScheduledWork
	(*ProductionPlanRequest)(nil),  // 3: stillhouse.v1.ProductionPlanRequest
	(*ProductionPlanResponse)(nil), // 4: stillhouse.v1.ProductionPlanResponse
	(EquipmentKind)(0),             // 5: stillhouse.v1.EquipmentKind
	(EquipmentStatus)(0),           // 6: stillhouse.v1.EquipmentStatus
}
var file_stillhouse_v1_scheduling_proto_depIdxs = []int32{
	5, // 0: stillhouse.v1.PlannableEquipment.kind:type_name -> stillhouse.v1.EquipmentKind
	6, // 1: stillhouse.v1.PlannableEquipment.status:type_name -> stillhouse.v1.EquipmentStatus
	2, // 2: stillhouse.v1.PlannableEquipment.scheduled:type_name -> stillhouse.v1.ScheduledWork
	0, // 3: stillhouse.v1.ProductionPlanResponse.demand:type_name -> stillhouse.v1.DemandLine
	1, // 4: stillhouse.v1.ProductionPlanResponse.equipment:type_name -> stillhouse.v1.PlannableEquipment
	3, // 5: stillhouse.v1.SchedulingService.ProductionPlan:input_type -> stillhouse.v1.ProductionPlanRequest
	4, // 6: stillhouse.v1.SchedulingService.ProductionPlan:output_type -> stillhouse.v1.ProductionPlanResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stillhouse_v1_scheduling_proto_init() }
func file_stillhouse_v1_scheduling_proto_init() {
	if File_stillhouse_v1_scheduling_proto != nil {
		return
	}
	file_stillhouse_v1_equipment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stillhouse_v1_scheduling_proto_rawDesc), len(file_stillhouse_v1_scheduling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stillhouse_v1_scheduling_proto_goTypes,
		DependencyIndexes: file_stillhouse_v1_scheduling_proto_depIdxs,
		MessageInfos:      file_stillhouse_v1_scheduling_proto_msgTypes,
	}.Build()
	File_stillhouse_v1_scheduling_proto = out.File
	file_stillhouse_v1_scheduling_proto_goTypes = nil
	file_stillhouse_v1_scheduling_proto_depIdxs = nil
}
