ALTER TABLE recipe_ingredients NO FORCE ROW LEVEL SECURITY;
ALTER TABLE recipe_versions    NO FORCE ROW LEVEL SECURITY;
ALTER TABLE recipes            NO FORCE ROW LEVEL SECURITY;
ALTER TABLE material_lots      NO FORCE ROW LEVEL SECURITY;
ALTER TABLE materials          NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events       NO FORCE ROW LEVEL SECURITY;
