// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: b266.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const b266PeriodCoveringDate = `-- name: B266PeriodCoveringDate :one
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods
WHERE status = 'submitted'
  AND period_start <= $1
  AND period_end   >= $1
LIMIT 1
`

// Returns a submitted period that covers the given date, if any. Mutations
// whose effective date lands in such a period should be rejected — the
// snapshot has already been filed with CRA and backdating would create
// a live-vs-filed discrepancy.
func (q *Queries) B266PeriodCoveringDate(ctx context.Context, periodStart pgtype.Date) (B266Period, error) {
	row := q.db.QueryRow(ctx, b266PeriodCoveringDate, periodStart)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const b266PeriodsOverlapping = `-- name: B266PeriodsOverlapping :many
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods
WHERE period_start <= $1
  AND period_end   >= $2
  AND NOT (period_start = $2 AND period_end = $1)
ORDER BY period_start
`

type B266PeriodsOverlappingParams struct {
	RangeEnd   pgtype.Date `json:"range_end"`
	RangeStart pgtype.Date `json:"range_start"`
}

// Any period that shares a day with the given range and is not that exact
// range. Two returns covering the same day would report the same alcohol
// twice.
//
// Named parameters deliberately: with positional $1/$2, sqlc names the
// struct fields after the column each is compared against, so `period_end
// >= $1` made $1 "PeriodEnd" and the caller's PeriodStart silently landed
// in the wrong slot.
func (q *Queries) B266PeriodsOverlapping(ctx context.Context, arg B266PeriodsOverlappingParams) ([]B266Period, error) {
	rows, err := q.db.Query(ctx, b266PeriodsOverlapping, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []B266Period{}
	for rows.Next() {
		var i B266Period
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Snapshot,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueOn,
			&i.FilingAcknowledgedAt,
			&i.FilingAcknowledgedBy,
			&i.FilingAcknowledgement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkOwnershipSplitAsOf = `-- name: BulkOwnershipSplitAsOf :one
SELECT
    COALESCE(SUM(current_laa) FILTER (
        WHERE owner_customer_id IS NOT NULL AND possession = 'held'), 0)::double precision
        AS held_for_others_laa,
    COALESCE(SUM(current_laa) FILTER (
        WHERE owner_customer_id IS NULL AND possession = 'held_elsewhere'), 0)::double precision
        AS held_elsewhere_laa,
    COALESCE(SUM(current_laa) FILTER (
        WHERE owner_customer_id IS NOT NULL AND possession = 'held_elsewhere'), 0)::double precision
        AS third_party_elsewhere_laa
FROM bulk_containers
WHERE NOT archived
`

type BulkOwnershipSplitAsOfRow struct {
	HeldForOthersLaa       float64 `json:"held_for_others_laa"`
	HeldElsewhereLaa       float64 `json:"held_elsewhere_laa"`
	ThirdPartyElsewhereLaa float64 `json:"third_party_elsewhere_laa"`
}

// What the closing balance is made of. Not a line on the form: EDM10-1-7
// page 3 asks for everything in our possession and nothing else. It is
// here because a licensee signing a return that includes a customer's
// casks should be able to see that it does, and one whose own casks are
// at a partner's warehouse should be able to see why they are absent.
//
// Deliberately read as at now rather than walked back to the period end.
// Ownership and possession are current facts with no ledger behind them
// yet, so a walk would be a fiction; the figures are labelled as current
// wherever they are shown. Getting this wrong in the other direction —
// presenting a walked figure that was never computed — is how a return
// becomes internally consistent and factually wrong.
func (q *Queries) BulkOwnershipSplitAsOf(ctx context.Context) (BulkOwnershipSplitAsOfRow, error) {
	row := q.db.QueryRow(ctx, bulkOwnershipSplitAsOf)
	var i BulkOwnershipSplitAsOfRow
	err := row.Scan(&i.HeldForOthersLaa, &i.HeldElsewhereLaa, &i.ThirdPartyElsewhereLaa)
	return i, err
}

const getB266Period = `-- name: GetB266Period :one
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods WHERE id = $1
`

func (q *Queries) GetB266Period(ctx context.Context, id uuid.UUID) (B266Period, error) {
	row := q.db.QueryRow(ctx, getB266Period, id)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const getB266PeriodByDates = `-- name: GetB266PeriodByDates :one
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods
WHERE period_start = $1 AND period_end = $2
`

type GetB266PeriodByDatesParams struct {
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

func (q *Queries) GetB266PeriodByDates(ctx context.Context, arg GetB266PeriodByDatesParams) (B266Period, error) {
	row := q.db.QueryRow(ctx, getB266PeriodByDates, arg.PeriodStart, arg.PeriodEnd)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const getB266PeriodWithAcknowledger = `-- name: GetB266PeriodWithAcknowledger :one
SELECT p.id, p.tenant_id, p.period_start, p.period_end, p.status, p.snapshot, p.submitted_at, p.submitted_by, p.notes, p.created_at, p.updated_at, p.due_on, p.filing_acknowledged_at, p.filing_acknowledged_by, p.filing_acknowledgement, COALESCE(u.display_name, '')::text AS acknowledged_by_name
FROM b266_periods p
LEFT JOIN users u ON u.id = p.filing_acknowledged_by
WHERE p.id = $1
`

type GetB266PeriodWithAcknowledgerRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	PeriodStart           pgtype.Date        `json:"period_start"`
	PeriodEnd             pgtype.Date        `json:"period_end"`
	Status                B266Status         `json:"status"`
	Snapshot              []byte             `json:"snapshot"`
	SubmittedAt           pgtype.Timestamptz `json:"submitted_at"`
	SubmittedBy           uuid.NullUUID      `json:"submitted_by"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DueOn                 pgtype.Date        `json:"due_on"`
	FilingAcknowledgedAt  pgtype.Timestamptz `json:"filing_acknowledged_at"`
	FilingAcknowledgedBy  uuid.NullUUID      `json:"filing_acknowledged_by"`
	FilingAcknowledgement string             `json:"filing_acknowledgement"`
	AcknowledgedByName    string             `json:"acknowledged_by_name"`
}

// The period plus the name of whoever confirmed the figures, for the
// screens that show the trail rather than act on it.
func (q *Queries) GetB266PeriodWithAcknowledger(ctx context.Context, id uuid.UUID) (GetB266PeriodWithAcknowledgerRow, error) {
	row := q.db.QueryRow(ctx, getB266PeriodWithAcknowledger, id)
	var i GetB266PeriodWithAcknowledgerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
		&i.AcknowledgedByName,
	)
	return i, err
}

const listB266Periods = `-- name: ListB266Periods :many
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods
ORDER BY period_start DESC
`

func (q *Queries) ListB266Periods(ctx context.Context) ([]B266Period, error) {
	rows, err := q.db.Query(ctx, listB266Periods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []B266Period{}
	for rows.Next() {
		var i B266Period
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.Snapshot,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueOn,
			&i.FilingAcknowledgedAt,
			&i.FilingAcknowledgedBy,
			&i.FilingAcknowledgement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackdatedBulkMovements = `-- name: ListBackdatedBulkMovements :many
SELECT m.id, m.reason, m.laa, m.occurred_at, m.created_at, m.notes,
       COALESCE(c.name, '')::text AS container_name,
       (  CASE WHEN m.destination_container_id IS NOT NULL THEN m.laa ELSE 0 END
        - CASE WHEN m.source_container_id      IS NOT NULL THEN m.laa ELSE 0 END
       )::double precision AS net_laa
FROM bulk_movements m
LEFT JOIN bulk_containers c
       ON c.id = COALESCE(m.destination_container_id, m.source_container_id)
WHERE m.occurred_at::date >= $1::date
  AND m.occurred_at::date <= $2::date
  AND m.created_at > $3::timestamptz
ORDER BY ABS(  CASE WHEN m.destination_container_id IS NOT NULL THEN m.laa ELSE 0 END
             - CASE WHEN m.source_container_id      IS NOT NULL THEN m.laa ELSE 0 END) DESC,
         m.occurred_at DESC
LIMIT $4::int
`

type ListBackdatedBulkMovementsParams struct {
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	FiledAt     pgtype.Timestamptz `json:"filed_at"`
	RowLimit    int32              `json:"row_limit"`
}

type ListBackdatedBulkMovementsRow struct {
	ID            uuid.UUID          `json:"id"`
	Reason        BulkMovementReason `json:"reason"`
	Laa           float64            `json:"laa"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Notes         string             `json:"notes"`
	ContainerName string             `json:"container_name"`
	NetLaa        float64            `json:"net_laa"`
}

// Movements booked into an already-filed span but entered after it was
// filed. occurred_at decides which return a movement belongs to;
// created_at is when the row appeared. A row where the second is later
// than the filing is one the filed return could not have counted.
//
// net_laa is the movement's effect on total bulk on hand, spelled exactly
// as SumBulkOnHandAsOf spells it: in adds, out subtracts, and an internal
// move with both ends set nets to zero. That expression is the definition
// of the closing balance, so using anything else here would explain a
// discrepancy with arithmetic that did not cause it.
//
// Ordered by the size of that effect, largest first, so the biggest
// contributor to a break is named first. Capped by the caller.
func (q *Queries) ListBackdatedBulkMovements(ctx context.Context, arg ListBackdatedBulkMovementsParams) ([]ListBackdatedBulkMovementsRow, error) {
	rows, err := q.db.Query(ctx, listBackdatedBulkMovements,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.FiledAt,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackdatedBulkMovementsRow{}
	for rows.Next() {
		var i ListBackdatedBulkMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reason,
			&i.Laa,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.Notes,
			&i.ContainerName,
			&i.NetLaa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priorFiledB266Period = `-- name: PriorFiledB266Period :one
SELECT id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement FROM b266_periods
WHERE status = 'submitted'
  AND period_end < $1::date
ORDER BY period_end DESC
LIMIT 1
`

// The most recent period that was actually filed and ends before this one
// starts. Drafts are excluded on purpose: a draft's closing balance is
// recomputed every time it is generated, so comparing against one would
// compare a figure against itself and always agree.
func (q *Queries) PriorFiledB266Period(ctx context.Context, periodStart pgtype.Date) (B266Period, error) {
	row := q.db.QueryRow(ctx, priorFiledB266Period, periodStart)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const reopenB266Period = `-- name: ReopenB266Period :one
UPDATE b266_periods
SET status = 'draft'
WHERE id = $1 AND status = 'submitted'
RETURNING id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement
`

// Flips a submitted period back to draft. Snapshot stays in place for
// audit (auditors can compare frozen vs. live after the reopen). The
// WHERE status = 'submitted' guard makes this a no-op on already-draft
// periods, returning no rows.
func (q *Queries) ReopenB266Period(ctx context.Context, id uuid.UUID) (B266Period, error) {
	row := q.db.QueryRow(ctx, reopenB266Period, id)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const submitB266Period = `-- name: SubmitB266Period :one
UPDATE b266_periods
SET status                 = 'submitted',
    snapshot               = $2,
    submitted_at           = NOW(),
    submitted_by           = $3,
    filing_acknowledged_at = NOW(),
    filing_acknowledged_by = $3,
    filing_acknowledgement = $4
WHERE id = $1
  AND status = 'draft'
RETURNING id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement
`

type SubmitB266PeriodParams struct {
	ID                    uuid.UUID     `json:"id"`
	Snapshot              []byte        `json:"snapshot"`
	SubmittedBy           uuid.NullUUID `json:"submitted_by"`
	FilingAcknowledgement string        `json:"filing_acknowledgement"`
}

// The acknowledgement is written in the same statement that sets the
// status, so a submitted period can never exist without one. The table's
// CHECK holds the other half of that guarantee for any path that is not
// this one.
func (q *Queries) SubmitB266Period(ctx context.Context, arg SubmitB266PeriodParams) (B266Period, error) {
	row := q.db.QueryRow(ctx, submitB266Period,
		arg.ID,
		arg.Snapshot,
		arg.SubmittedBy,
		arg.FilingAcknowledgement,
	)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}

const sumBackdatedBulkMovements = `-- name: SumBackdatedBulkMovements :one
SELECT COUNT(*)::int AS n,
       COALESCE(SUM(
           CASE WHEN m.destination_container_id IS NOT NULL THEN m.laa ELSE 0 END
         - CASE WHEN m.source_container_id      IS NOT NULL THEN m.laa ELSE 0 END
       ), 0)::double precision AS net_laa
FROM bulk_movements m
WHERE m.occurred_at::date >= $1::date
  AND m.occurred_at::date <= $2::date
  AND m.created_at > $3::timestamptz
`

type SumBackdatedBulkMovementsParams struct {
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	FiledAt     pgtype.Timestamptz `json:"filed_at"`
}

type SumBackdatedBulkMovementsRow struct {
	N      int32   `json:"n"`
	NetLaa float64 `json:"net_laa"`
}

// The whole set, not the capped page: how many there are and what they do
// to the closing balance in total. Same expression as above.
func (q *Queries) SumBackdatedBulkMovements(ctx context.Context, arg SumBackdatedBulkMovementsParams) (SumBackdatedBulkMovementsRow, error) {
	row := q.db.QueryRow(ctx, sumBackdatedBulkMovements, arg.PeriodStart, arg.PeriodEnd, arg.FiledAt)
	var i SumBackdatedBulkMovementsRow
	err := row.Scan(&i.N, &i.NetLaa)
	return i, err
}

const sumBottlingDutyInPeriod = `-- name: SumBottlingDutyInPeriod :one
SELECT COALESCE(SUM(br.duty_amount_cad), 0)::double precision AS total_duty,
       COALESCE(SUM(br.bottle_count) FILTER (WHERE p.target_abv_pct > 7), 0)::int
           AS over7_bottles,
       COALESCE(SUM(br.bottle_count * p.bottle_size_ml / 1000.0 * p.target_abv_pct / 100.0)
                FILTER (WHERE p.target_abv_pct > 7), 0)::double precision
           AS over7_laa,
       COALESCE(SUM(br.duty_amount_cad) FILTER (WHERE p.target_abv_pct > 7), 0)::double precision
           AS over7_duty,
       COALESCE(SUM(br.bottle_count) FILTER (WHERE p.target_abv_pct <= 7), 0)::int
           AS under7_bottles,
       COALESCE(SUM(br.bottle_count * p.bottle_size_ml / 1000.0)
                FILTER (WHERE p.target_abv_pct <= 7), 0)::double precision
           AS under7_litres,
       COALESCE(SUM(br.duty_amount_cad) FILTER (WHERE p.target_abv_pct <= 7), 0)::double precision
           AS under7_duty,
       -- Bottles and LAA packaged as duty-paid: everything with a duty
       -- amount on it. The complement — packaged non-duty-paid — is the
       -- rest of the period's bottling, and the projection takes the
       -- difference rather than running a second scan.
       COALESCE(SUM(br.bottle_count), 0)::int AS duty_paid_bottles,
       COALESCE(SUM(br.bottle_count * p.bottle_size_ml / 1000.0 * p.target_abv_pct / 100.0),
                0)::double precision AS duty_paid_laa
FROM bottling_runs br
JOIN products p ON p.id = br.product_id
WHERE br.bottling_date >= $1 AND br.bottling_date < $2
  AND br.voided_at IS NULL
  AND br.duty_amount_cad IS NOT NULL
`

type SumBottlingDutyInPeriodParams struct {
	BottlingDate   pgtype.Date `json:"bottling_date"`
	BottlingDate_2 pgtype.Date `json:"bottling_date_2"`
}

type SumBottlingDutyInPeriodRow struct {
	TotalDuty       float64 `json:"total_duty"`
	Over7Bottles    int32   `json:"over7_bottles"`
	Over7Laa        float64 `json:"over7_laa"`
	Over7Duty       float64 `json:"over7_duty"`
	Under7Bottles   int32   `json:"under7_bottles"`
	Under7Litres    float64 `json:"under7_litres"`
	Under7Duty      float64 `json:"under7_duty"`
	DutyPaidBottles int32   `json:"duty_paid_bottles"`
	DutyPaidLaa     float64 `json:"duty_paid_laa"`
}

// Duty that crystallised at packaging during the period, split by the two
// rate bands, because they are not charged in the same unit: above 7% ABV
// per litre of absolute alcohol, at or below 7% per litre of product. The
// mirror of SumRemovalsInPeriod, and it exists for the same reason — a
// return that quotes one blended rate against a mixed total fails its own
// arithmetic.
//
// Only runs carrying a duty amount count. A run with NULL duty is not a
// duty event: either the tenant pays at removal, or the run predates the
// tenant's duty-point cutover and its stock is dutied on its way out
// instead.
func (q *Queries) SumBottlingDutyInPeriod(ctx context.Context, arg SumBottlingDutyInPeriodParams) (SumBottlingDutyInPeriodRow, error) {
	row := q.db.QueryRow(ctx, sumBottlingDutyInPeriod, arg.BottlingDate, arg.BottlingDate_2)
	var i SumBottlingDutyInPeriodRow
	err := row.Scan(
		&i.TotalDuty,
		&i.Over7Bottles,
		&i.Over7Laa,
		&i.Over7Duty,
		&i.Under7Bottles,
		&i.Under7Litres,
		&i.Under7Duty,
		&i.DutyPaidBottles,
		&i.DutyPaidLaa,
	)
	return i, err
}

const sumBottlingRunsInPeriod = `-- name: SumBottlingRunsInPeriod :one
SELECT COALESCE(SUM(br.tank_gauge_laa), 0)::double precision AS total_laa,
       COALESCE(SUM(br.bottle_count * p.bottle_size_ml / 1000.0 * p.target_abv_pct / 100.0),
                0)::double precision AS packaged_laa,
       COALESCE(SUM(br.bottling_loss_l * p.target_abv_pct / 100.0),
                0)::double precision AS loss_laa,
       COUNT(*)::int AS run_count,
       COALESCE(SUM(br.bottle_count), 0)::int AS total_bottles
FROM bottling_runs br
JOIN products p ON p.id = br.product_id
WHERE br.bottling_date >= $1 AND br.bottling_date < $2
  AND br.voided_at IS NULL
`

type SumBottlingRunsInPeriodParams struct {
	BottlingDate   pgtype.Date `json:"bottling_date"`
	BottlingDate_2 pgtype.Date `json:"bottling_date_2"`
}

type SumBottlingRunsInPeriodRow struct {
	TotalLaa     float64 `json:"total_laa"`
	PackagedLaa  float64 `json:"packaged_laa"`
	LossLaa      float64 `json:"loss_laa"`
	RunCount     int32   `json:"run_count"`
	TotalBottles int32   `json:"total_bottles"`
}

// SumBottlingRunsInPeriod excludes voided runs; voided runs are reversed in
// packaged_inventory and bulk separately, so they shouldn't count toward
// either the packaging or production lines on B266.
// Three different quantities, and conflating them puts a negative opening
// balance on the return:
//
//	drawn_laa    — what left bulk (the tank gauge)
//	packaged_laa — what became sealed bottles
//	loss_laa     — the difference, spilled or left in the filler
//
// Packaged inventory only ever received packaged_laa, so that is the line
// that closes against it; the bulk side's transfer-to-packaging figure is
// drawn_laa, and the loss is what reconciles the two.
func (q *Queries) SumBottlingRunsInPeriod(ctx context.Context, arg SumBottlingRunsInPeriodParams) (SumBottlingRunsInPeriodRow, error) {
	row := q.db.QueryRow(ctx, sumBottlingRunsInPeriod, arg.BottlingDate, arg.BottlingDate_2)
	var i SumBottlingRunsInPeriodRow
	err := row.Scan(
		&i.TotalLaa,
		&i.PackagedLaa,
		&i.LossLaa,
		&i.RunCount,
		&i.TotalBottles,
	)
	return i, err
}

const sumBulkMovementsByReason = `-- name: SumBulkMovementsByReason :many

SELECT bm.reason::text AS reason,
       SUM(bm.laa)::double precision AS total_laa,
       COUNT(*)::int AS count
FROM bulk_movements bm
LEFT JOIN distillation_runs dr
       ON bm.reason = 'production_gauge'
      AND bm.reference_type = 'distillation_run'
      AND dr.id = bm.reference_id
WHERE bm.occurred_at >= $1 AND bm.occurred_at < $2
  AND (dr.id IS NULL OR dr.voided_at IS NULL)
  AND bm.reference_type NOT IN ('distillation_run_void', 'bottling_run_void')
GROUP BY bm.reason
ORDER BY bm.reason
`

type SumBulkMovementsByReasonParams struct {
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type SumBulkMovementsByReasonRow struct {
	Reason   string  `json:"reason"`
	TotalLaa float64 `json:"total_laa"`
	Count    int32   `json:"count"`
}

// Aggregation queries for generating B266 sections.
// Excludes production_gauge movements whose underlying distillation_run is
// voided (so voiding a run removes its production LAA from B266). Also
// excludes regauge_correction movements that reference a void event — those
// exist purely to balance the ledger and shouldn't show up as their own line.
func (q *Queries) SumBulkMovementsByReason(ctx context.Context, arg SumBulkMovementsByReasonParams) ([]SumBulkMovementsByReasonRow, error) {
	rows, err := q.db.Query(ctx, sumBulkMovementsByReason, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumBulkMovementsByReasonRow{}
	for rows.Next() {
		var i SumBulkMovementsByReasonRow
		if err := rows.Scan(&i.Reason, &i.TotalLaa, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumBulkOnHandAsOf = `-- name: SumBulkOnHandAsOf :one
WITH running AS (
    SELECT COALESCE(SUM(current_laa), 0)::double precision AS total_laa
    FROM bulk_containers
    WHERE NOT archived
      AND possession = 'held'
), moved_after AS (
    SELECT COALESCE(SUM(
        CASE WHEN destination_container_id IS NOT NULL THEN laa ELSE 0 END
      - CASE WHEN source_container_id      IS NOT NULL THEN laa ELSE 0 END
    ), 0)::double precision AS net_laa
    FROM bulk_movements
    WHERE occurred_at >= $1
)
SELECT (running.total_laa - moved_after.net_laa)::double precision AS total_laa
FROM running, moved_after
`

// Bulk LAA on hand as at a moment, not right now.
//
// This used to sum current_laa with no date at all, and its own comment
// conceded that was "fine if generated promptly after period close".
// Generating May's return in August therefore reported August's balance as
// May's closing figure — and because the opening balance is reverse-walked
// from the closing one, both ends moved together and the arithmetic still
// tied out. A return that is internally consistent and factually wrong is
// the worst shape for an error, because nothing looks off.
//
// The walk goes backwards from the running total rather than forwards from
// zero, deliberately: when as_of is now, the "after" set is empty and this
// returns exactly what the old query did, so a promptly-generated return
// does not move. Only movements between the period end and now are
// subtracted, so nothing depends on the ledger being complete back to the
// distillery's first day.
//
// Net effect on total on-hand: a movement into a container adds, a movement
// out subtracts, and one with both ends set — a barrel fill, a blend — is
// internal and nets to zero. Void corrections carry their own offsetting
// row (see VoidDistillationRun), so including everything is what makes the
// walk reconcile.
//
// Known edge: a container archived after as_of is excluded from the running
// total but held alcohol at as_of. Archiving requires an empty container,
// so the LAA involved is zero.
//
// Possession, not ownership. EDM10-1-7 page 3 asks for all bulk spirits in
// our possession whatever anyone owns, so a customer's cask maturing in
// our rackhouse is here and a parcel of our own whisky at a partner's
// bonded warehouse is not.
//
// The filter is on the running total only, and the movement side is left
// alone deliberately. Filtering both would be the obvious thing and would
// be wrong: the walk needs the movements a departing container made while
// it was still ours to report. It works out because a possession change
// writes a movement for the whole balance (rpc.SetBulkPossession), and
// nothing else may be recorded against a container held elsewhere:
//
//	left after as_of     excluded from running; its exit movement is
//	                     subtracted, adding the balance back — which is
//	                     what was on hand at as_of.
//	returned after as_of included in running; its return movement is
//	                     subtracted, taking it back out.
//	never here          cannot happen: a container is created and adopted
//	                     in our possession and reaches held_elsewhere only
//	                     through the transition above, so there is always
//	                     a movement to reconcile against.
func (q *Queries) SumBulkOnHandAsOf(ctx context.Context, asOf pgtype.Timestamptz) (float64, error) {
	row := q.db.QueryRow(ctx, sumBulkOnHandAsOf, asOf)
	var total_laa float64
	err := row.Scan(&total_laa)
	return total_laa, err
}

const sumPackagedAdjustmentsInPeriod = `-- name: SumPackagedAdjustmentsInPeriod :one
SELECT COALESCE(SUM(laa_delta), 0)::double precision AS net_laa,
       COALESCE(SUM(laa_delta) FILTER (WHERE laa_delta > 0), 0)::double precision AS increase_laa,
       COALESCE(-SUM(laa_delta) FILTER (WHERE laa_delta < 0), 0)::double precision AS decrease_laa,
       COALESCE(SUM(bottles_delta), 0)::int AS net_bottles,
       COUNT(*)::int AS adjustment_count
FROM packaged_adjustments
WHERE occurred_on >= $1::date
  AND occurred_on <  $2::date
`

type SumPackagedAdjustmentsInPeriodParams struct {
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type SumPackagedAdjustmentsInPeriodRow struct {
	NetLaa          float64 `json:"net_laa"`
	IncreaseLaa     float64 `json:"increase_laa"`
	DecreaseLaa     float64 `json:"decrease_laa"`
	NetBottles      int32   `json:"net_bottles"`
	AdjustmentCount int32   `json:"adjustment_count"`
}

// Line D's packaged half: reason-coded reconciliation of packaged stock
// to physical. Signed net, with each direction also reported, for the
// same reason the bulk one is — a period that found a case in one lot and
// lost one in another nets to zero, and a line showing only the net says
// nothing happened.
func (q *Queries) SumPackagedAdjustmentsInPeriod(ctx context.Context, arg SumPackagedAdjustmentsInPeriodParams) (SumPackagedAdjustmentsInPeriodRow, error) {
	row := q.db.QueryRow(ctx, sumPackagedAdjustmentsInPeriod, arg.PeriodStart, arg.PeriodEnd)
	var i SumPackagedAdjustmentsInPeriodRow
	err := row.Scan(
		&i.NetLaa,
		&i.IncreaseLaa,
		&i.DecreaseLaa,
		&i.NetBottles,
		&i.AdjustmentCount,
	)
	return i, err
}

const sumPackagedOnHandAsOf = `-- name: SumPackagedOnHandAsOf :one
WITH running AS (
    SELECT COALESCE(SUM(pi.bottles_on_hand * p.bottle_size_ml * p.target_abv_pct / 100000.0), 0)::double precision AS total_laa,
           COALESCE(SUM(pi.bottles_on_hand), 0)::int AS total_bottles
    FROM packaged_inventory pi
    JOIN products p ON p.id = pi.product_id
), packaged_after AS (
    SELECT COALESCE(SUM(br.bottle_count * p.bottle_size_ml / 1000.0 * p.target_abv_pct / 100.0), 0)::double precision AS laa,
           COALESCE(SUM(br.bottle_count), 0)::int AS bottles
    FROM bottling_runs br
    JOIN products p ON p.id = br.product_id
    WHERE br.bottling_date >= $1 AND br.voided_at IS NULL
), removed_after AS (
    SELECT COALESCE(SUM(total_laa), 0)::double precision AS laa,
           COALESCE(SUM(bottles_removed), 0)::int AS bottles
    FROM packaging_removals
    WHERE removal_date >= $1 AND voided_at IS NULL
), adjusted_after AS (
    -- Stage 186. Until it, packaged inventory only ever gained from a
    -- run and lost to a removal, and this walk relied on that. A count
    -- that found a case missing now writes a row here, and the row is
    -- undone the same way the other two are — a balance that changed
    -- with nothing in the ledger to undo would silently restate a period
    -- already filed.
    SELECT COALESCE(SUM(laa_delta), 0)::double precision AS laa,
           COALESCE(SUM(bottles_delta), 0)::int AS bottles
    FROM packaged_adjustments
    WHERE occurred_on >= $1
)
SELECT (running.total_laa     - packaged_after.laa     + removed_after.laa
        - adjusted_after.laa)::double precision AS total_laa,
       (running.total_bottles - packaged_after.bottles + removed_after.bottles
        - adjusted_after.bottles)::int          AS total_bottles
FROM running, packaged_after, removed_after, adjusted_after
`

type SumPackagedOnHandAsOfRow struct {
	TotalLaa     float64 `json:"total_laa"`
	TotalBottles int32   `json:"total_bottles"`
}

// Packaged LAA and bottles on hand as at a moment. Same reverse walk as
// SumBulkOnHandAsOf and for the same reason: packaged inventory only ever
// receives bottling runs and only ever loses removals, so undoing both back
// to the period end recovers the balance that was actually on hand then.
//
// LAA is the same approximation the packaged section has always used:
// bottles × bottle_size × target_abv. Removals carry their own total_laa,
// computed the same way at the time, so the two sides subtract cleanly.
//
// Known edge: a run or removal dated inside the period but voided after it
// is treated as never having happened, which is how the reason sums above
// already treat voids. The period lock stops that arising for a period
// already filed.
func (q *Queries) SumPackagedOnHandAsOf(ctx context.Context, asOf pgtype.Date) (SumPackagedOnHandAsOfRow, error) {
	row := q.db.QueryRow(ctx, sumPackagedOnHandAsOf, asOf)
	var i SumPackagedOnHandAsOfRow
	err := row.Scan(&i.TotalLaa, &i.TotalBottles)
	return i, err
}

const sumRemovalsInPeriod = `-- name: SumRemovalsInPeriod :one
SELECT COALESCE(SUM(total_laa), 0)::double precision       AS total_laa,
       COALESCE(SUM(duty_amount_cad), 0)::double precision AS total_duty,
       COALESCE(SUM(bottles_removed), 0)::int              AS total_bottles,
       COUNT(*)::int                                       AS removal_count,
       COALESCE(SUM(total_laa) FILTER (WHERE bottle_abv_pct > 7), 0)::double precision
           AS over7_laa,
       COALESCE(SUM(duty_amount_cad) FILTER (WHERE bottle_abv_pct > 7), 0)::double precision
           AS over7_duty,
       COALESCE(SUM(bottles_removed) FILTER (WHERE bottle_abv_pct > 7), 0)::int
           AS over7_bottles,
       COALESCE(SUM(total_litres) FILTER (WHERE bottle_abv_pct <= 7), 0)::double precision
           AS under7_litres,
       COALESCE(SUM(duty_amount_cad) FILTER (WHERE bottle_abv_pct <= 7), 0)::double precision
           AS under7_duty,
       COALESCE(SUM(bottles_removed) FILTER (WHERE bottle_abv_pct <= 7), 0)::int
           AS under7_bottles
FROM packaging_removals
WHERE removal_date >= $1 AND removal_date < $2
  AND voided_at IS NULL
`

type SumRemovalsInPeriodParams struct {
	RemovalDate   pgtype.Date `json:"removal_date"`
	RemovalDate_2 pgtype.Date `json:"removal_date_2"`
}

type SumRemovalsInPeriodRow struct {
	TotalLaa      float64 `json:"total_laa"`
	TotalDuty     float64 `json:"total_duty"`
	TotalBottles  int32   `json:"total_bottles"`
	RemovalCount  int32   `json:"removal_count"`
	Over7Laa      float64 `json:"over7_laa"`
	Over7Duty     float64 `json:"over7_duty"`
	Over7Bottles  int32   `json:"over7_bottles"`
	Under7Litres  float64 `json:"under7_litres"`
	Under7Duty    float64 `json:"under7_duty"`
	Under7Bottles int32   `json:"under7_bottles"`
}

// Split by rate band, because the two bands are not taxed in the same
// unit: spirits above 7% ABV pay per litre of absolute alcohol, at or
// below 7% pay per litre of product. Reporting one blended "rate per LAA"
// against a total LAA made the return fail its own arithmetic as soon as a
// period contained both — 7.775 LAA at a stated $14.117 is $109.76, while
// the duty actually owed was $97.41. The B266 has separate lines for the
// two bands for exactly this reason.
func (q *Queries) SumRemovalsInPeriod(ctx context.Context, arg SumRemovalsInPeriodParams) (SumRemovalsInPeriodRow, error) {
	row := q.db.QueryRow(ctx, sumRemovalsInPeriod, arg.RemovalDate, arg.RemovalDate_2)
	var i SumRemovalsInPeriodRow
	err := row.Scan(
		&i.TotalLaa,
		&i.TotalDuty,
		&i.TotalBottles,
		&i.RemovalCount,
		&i.Over7Laa,
		&i.Over7Duty,
		&i.Over7Bottles,
		&i.Under7Litres,
		&i.Under7Duty,
		&i.Under7Bottles,
	)
	return i, err
}

const upsertB266PeriodDraft = `-- name: UpsertB266PeriodDraft :one
INSERT INTO b266_periods (tenant_id, period_start, period_end, status, due_on)
VALUES ($1, $2, $3, 'draft', $4)
ON CONFLICT (tenant_id, period_start, period_end) DO UPDATE
SET updated_at = NOW(),
    due_on     = COALESCE(b266_periods.due_on, EXCLUDED.due_on)
RETURNING id, tenant_id, period_start, period_end, status, snapshot, submitted_at, submitted_by, notes, created_at, updated_at, due_on, filing_acknowledged_at, filing_acknowledged_by, filing_acknowledgement
`

type UpsertB266PeriodDraftParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	DueOn       pgtype.Date `json:"due_on"`
}

// due_on is set on first generation and left alone afterwards: a change of
// fiscal-month election must not silently restate when a past return was
// due. COALESCE keeps whatever the row already had.
func (q *Queries) UpsertB266PeriodDraft(ctx context.Context, arg UpsertB266PeriodDraftParams) (B266Period, error) {
	row := q.db.QueryRow(ctx, upsertB266PeriodDraft,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DueOn,
	)
	var i B266Period
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.Snapshot,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueOn,
		&i.FilingAcknowledgedAt,
		&i.FilingAcknowledgedBy,
		&i.FilingAcknowledgement,
	)
	return i, err
}
