// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redistillation.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const alertOpenRedistillations = `-- name: AlertOpenRedistillations :many
SELECT r.id, r.taken_on, r.laa_taken, bc.name AS source_container_name
FROM redistillations r
JOIN bulk_containers bc ON bc.id = r.source_container_id
WHERE r.laa_produced IS NULL
  AND r.taken_on < $1::DATE
`

type AlertOpenRedistillationsRow struct {
	ID                  uuid.UUID   `json:"id"`
	TakenOn             pgtype.Date `json:"taken_on"`
	LaaTaken            float64     `json:"laa_taken"`
	SourceContainerName string      `json:"source_container_name"`
}

// Spirit that left stock into the still and has no output recorded after
// long enough that it should have. Alcohol off the books is the one
// shape of gap a period-end reconciliation cannot explain.
func (q *Queries) AlertOpenRedistillations(ctx context.Context, cutoff pgtype.Date) ([]AlertOpenRedistillationsRow, error) {
	rows, err := q.db.Query(ctx, alertOpenRedistillations, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertOpenRedistillationsRow{}
	for rows.Next() {
		var i AlertOpenRedistillationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TakenOn,
			&i.LaaTaken,
			&i.SourceContainerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRedistillation = `-- name: CreateRedistillation :one
INSERT INTO redistillations (
    tenant_id, source_container_id, bulk_movement_id, reason, taken_on,
    volume_taken_l, abv_taken_pct, laa_taken, notes, recorded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, source_container_id, bulk_movement_id, reason, taken_on, volume_taken_l, abv_taken_pct, laa_taken, distillation_run_id, laa_produced, produced_on, loss_laa, loss_classified_at, notes, recorded_by, created_at, updated_at
`

type CreateRedistillationParams struct {
	TenantID          uuid.UUID            `json:"tenant_id"`
	SourceContainerID uuid.UUID            `json:"source_container_id"`
	BulkMovementID    uuid.NullUUID        `json:"bulk_movement_id"`
	Reason            RedistillationReason `json:"reason"`
	TakenOn           pgtype.Date          `json:"taken_on"`
	VolumeTakenL      float64              `json:"volume_taken_l"`
	AbvTakenPct       float64              `json:"abv_taken_pct"`
	LaaTaken          float64              `json:"laa_taken"`
	Notes             string               `json:"notes"`
	RecordedBy        uuid.UUID            `json:"recorded_by"`
}

func (q *Queries) CreateRedistillation(ctx context.Context, arg CreateRedistillationParams) (Redistillation, error) {
	row := q.db.QueryRow(ctx, createRedistillation,
		arg.TenantID,
		arg.SourceContainerID,
		arg.BulkMovementID,
		arg.Reason,
		arg.TakenOn,
		arg.VolumeTakenL,
		arg.AbvTakenPct,
		arg.LaaTaken,
		arg.Notes,
		arg.RecordedBy,
	)
	var i Redistillation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceContainerID,
		&i.BulkMovementID,
		&i.Reason,
		&i.TakenOn,
		&i.VolumeTakenL,
		&i.AbvTakenPct,
		&i.LaaTaken,
		&i.DistillationRunID,
		&i.LaaProduced,
		&i.ProducedOn,
		&i.LossLaa,
		&i.LossClassifiedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedistillation = `-- name: GetRedistillation :one
SELECT id, tenant_id, source_container_id, bulk_movement_id, reason, taken_on, volume_taken_l, abv_taken_pct, laa_taken, distillation_run_id, laa_produced, produced_on, loss_laa, loss_classified_at, notes, recorded_by, created_at, updated_at FROM redistillations WHERE id = $1
`

func (q *Queries) GetRedistillation(ctx context.Context, id uuid.UUID) (Redistillation, error) {
	row := q.db.QueryRow(ctx, getRedistillation, id)
	var i Redistillation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceContainerID,
		&i.BulkMovementID,
		&i.Reason,
		&i.TakenOn,
		&i.VolumeTakenL,
		&i.AbvTakenPct,
		&i.LaaTaken,
		&i.DistillationRunID,
		&i.LaaProduced,
		&i.ProducedOn,
		&i.LossLaa,
		&i.LossClassifiedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRedistillations = `-- name: ListRedistillations :many
SELECT r.id, r.tenant_id, r.source_container_id, r.bulk_movement_id, r.reason, r.taken_on, r.volume_taken_l, r.abv_taken_pct, r.laa_taken, r.distillation_run_id, r.laa_produced, r.produced_on, r.loss_laa, r.loss_classified_at, r.notes, r.recorded_by, r.created_at, r.updated_at,
       bc.name AS source_container_name,
       COALESCE(dr.run_no, 0)::INTEGER AS distillation_run_no,
       COALESCE(u.display_name, '') AS recorded_by_name
FROM redistillations r
JOIN bulk_containers bc ON bc.id = r.source_container_id
LEFT JOIN distillation_runs dr ON dr.id = r.distillation_run_id
LEFT JOIN users u ON u.id = r.recorded_by
WHERE ($1::BOOLEAN = FALSE OR r.laa_produced IS NULL)
ORDER BY r.taken_on DESC, r.created_at DESC
LIMIT $2
`

type ListRedistillationsParams struct {
	OpenOnly bool  `json:"open_only"`
	RowLimit int32 `json:"row_limit"`
}

type ListRedistillationsRow struct {
	ID                  uuid.UUID            `json:"id"`
	TenantID            uuid.UUID            `json:"tenant_id"`
	SourceContainerID   uuid.UUID            `json:"source_container_id"`
	BulkMovementID      uuid.NullUUID        `json:"bulk_movement_id"`
	Reason              RedistillationReason `json:"reason"`
	TakenOn             pgtype.Date          `json:"taken_on"`
	VolumeTakenL        float64              `json:"volume_taken_l"`
	AbvTakenPct         float64              `json:"abv_taken_pct"`
	LaaTaken            float64              `json:"laa_taken"`
	DistillationRunID   uuid.NullUUID        `json:"distillation_run_id"`
	LaaProduced         pgtype.Float8        `json:"laa_produced"`
	ProducedOn          pgtype.Date          `json:"produced_on"`
	LossLaa             pgtype.Float8        `json:"loss_laa"`
	LossClassifiedAt    pgtype.Timestamptz   `json:"loss_classified_at"`
	Notes               string               `json:"notes"`
	RecordedBy          uuid.UUID            `json:"recorded_by"`
	CreatedAt           pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz   `json:"updated_at"`
	SourceContainerName string               `json:"source_container_name"`
	DistillationRunNo   int32                `json:"distillation_run_no"`
	RecordedByName      string               `json:"recorded_by_name"`
}

func (q *Queries) ListRedistillations(ctx context.Context, arg ListRedistillationsParams) ([]ListRedistillationsRow, error) {
	rows, err := q.db.Query(ctx, listRedistillations, arg.OpenOnly, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRedistillationsRow{}
	for rows.Next() {
		var i ListRedistillationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceContainerID,
			&i.BulkMovementID,
			&i.Reason,
			&i.TakenOn,
			&i.VolumeTakenL,
			&i.AbvTakenPct,
			&i.LaaTaken,
			&i.DistillationRunID,
			&i.LaaProduced,
			&i.ProducedOn,
			&i.LossLaa,
			&i.LossClassifiedAt,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceContainerName,
			&i.DistillationRunNo,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRedistillationLossClassified = `-- name: MarkRedistillationLossClassified :one
UPDATE redistillations SET loss_classified_at = NOW() WHERE id = $1 RETURNING id, tenant_id, source_container_id, bulk_movement_id, reason, taken_on, volume_taken_l, abv_taken_pct, laa_taken, distillation_run_id, laa_produced, produced_on, loss_laa, loss_classified_at, notes, recorded_by, created_at, updated_at
`

func (q *Queries) MarkRedistillationLossClassified(ctx context.Context, id uuid.UUID) (Redistillation, error) {
	row := q.db.QueryRow(ctx, markRedistillationLossClassified, id)
	var i Redistillation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceContainerID,
		&i.BulkMovementID,
		&i.Reason,
		&i.TakenOn,
		&i.VolumeTakenL,
		&i.AbvTakenPct,
		&i.LaaTaken,
		&i.DistillationRunID,
		&i.LaaProduced,
		&i.ProducedOn,
		&i.LossLaa,
		&i.LossClassifiedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordRedistillationOutput = `-- name: RecordRedistillationOutput :one
UPDATE redistillations
SET distillation_run_id = $2,
    laa_produced        = $3,
    produced_on         = $4
WHERE id = $1 AND laa_produced IS NULL
RETURNING id, tenant_id, source_container_id, bulk_movement_id, reason, taken_on, volume_taken_l, abv_taken_pct, laa_taken, distillation_run_id, laa_produced, produced_on, loss_laa, loss_classified_at, notes, recorded_by, created_at, updated_at
`

type RecordRedistillationOutputParams struct {
	ID                uuid.UUID     `json:"id"`
	DistillationRunID uuid.NullUUID `json:"distillation_run_id"`
	LaaProduced       pgtype.Float8 `json:"laa_produced"`
	ProducedOn        pgtype.Date   `json:"produced_on"`
}

// Closes the loop. laa_produced and produced_on are set together — the
// CHECK enforces it — so a run can never be half-recorded, and loss_laa
// becomes computable at exactly the moment both halves are known.
func (q *Queries) RecordRedistillationOutput(ctx context.Context, arg RecordRedistillationOutputParams) (Redistillation, error) {
	row := q.db.QueryRow(ctx, recordRedistillationOutput,
		arg.ID,
		arg.DistillationRunID,
		arg.LaaProduced,
		arg.ProducedOn,
	)
	var i Redistillation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceContainerID,
		&i.BulkMovementID,
		&i.Reason,
		&i.TakenOn,
		&i.VolumeTakenL,
		&i.AbvTakenPct,
		&i.LaaTaken,
		&i.DistillationRunID,
		&i.LaaProduced,
		&i.ProducedOn,
		&i.LossLaa,
		&i.LossClassifiedAt,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const redistillationPeriodSummary = `-- name: RedistillationPeriodSummary :one
SELECT
    COUNT(*)::INTEGER                                        AS event_count,
    COALESCE(SUM(laa_taken), 0)::DOUBLE PRECISION            AS laa_taken,
    COALESCE(SUM(laa_produced), 0)::DOUBLE PRECISION         AS laa_produced,
    COALESCE(SUM(loss_laa), 0)::DOUBLE PRECISION             AS loss_laa,
    COUNT(*) FILTER (WHERE laa_produced IS NULL)::INTEGER    AS still_open
FROM redistillations
WHERE taken_on >= $1::DATE
  AND taken_on <= $2::DATE
`

type RedistillationPeriodSummaryParams struct {
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type RedistillationPeriodSummaryRow struct {
	EventCount  int32   `json:"event_count"`
	LaaTaken    float64 `json:"laa_taken"`
	LaaProduced float64 `json:"laa_produced"`
	LossLaa     float64 `json:"loss_laa"`
	StillOpen   int32   `json:"still_open"`
}

// What went back through the still in a period, and what it cost. The
// figures EDM3-1-1 para 41 asks to be kept.
func (q *Queries) RedistillationPeriodSummary(ctx context.Context, arg RedistillationPeriodSummaryParams) (RedistillationPeriodSummaryRow, error) {
	row := q.db.QueryRow(ctx, redistillationPeriodSummary, arg.PeriodStart, arg.PeriodEnd)
	var i RedistillationPeriodSummaryRow
	err := row.Scan(
		&i.EventCount,
		&i.LaaTaken,
		&i.LaaProduced,
		&i.LossLaa,
		&i.StillOpen,
	)
	return i, err
}
