// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSalesOrderLine = `-- name: AddSalesOrderLine :one
INSERT INTO sales_order_lines (
    tenant_id, sales_order_id, product_id, bottles_ordered, unit_price, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, sales_order_id, product_id, bottles_ordered, bottles_shipped, unit_price, notes, created_at, updated_at
`

type AddSalesOrderLineParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	SalesOrderID   uuid.UUID      `json:"sales_order_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	BottlesOrdered int32          `json:"bottles_ordered"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Notes          string         `json:"notes"`
}

func (q *Queries) AddSalesOrderLine(ctx context.Context, arg AddSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, addSalesOrderLine,
		arg.TenantID,
		arg.SalesOrderID,
		arg.ProductID,
		arg.BottlesOrdered,
		arg.UnitPrice,
		arg.Notes,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.ProductID,
		&i.BottlesOrdered,
		&i.BottlesShipped,
		&i.UnitPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addShipmentLine = `-- name: AddShipmentLine :one
INSERT INTO shipment_lines (
    tenant_id, shipment_id, sales_order_line_id, packaged_inventory_id, bottles, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, shipment_id, sales_order_line_id, packaged_inventory_id, bottles, packaging_removal_id, notes, created_at
`

type AddShipmentLineParams struct {
	TenantID            uuid.UUID     `json:"tenant_id"`
	ShipmentID          uuid.UUID     `json:"shipment_id"`
	SalesOrderLineID    uuid.NullUUID `json:"sales_order_line_id"`
	PackagedInventoryID uuid.UUID     `json:"packaged_inventory_id"`
	Bottles             int32         `json:"bottles"`
	Notes               string        `json:"notes"`
}

func (q *Queries) AddShipmentLine(ctx context.Context, arg AddShipmentLineParams) (ShipmentLine, error) {
	row := q.db.QueryRow(ctx, addShipmentLine,
		arg.TenantID,
		arg.ShipmentID,
		arg.SalesOrderLineID,
		arg.PackagedInventoryID,
		arg.Bottles,
		arg.Notes,
	)
	var i ShipmentLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentID,
		&i.SalesOrderLineID,
		&i.PackagedInventoryID,
		&i.Bottles,
		&i.PackagingRemovalID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const bottlesPickedFromLot = `-- name: BottlesPickedFromLot :one
SELECT COALESCE(SUM(sl.bottles), 0)::INTEGER AS picked
FROM shipment_lines sl
JOIN shipments s ON s.id = sl.shipment_id
WHERE sl.packaged_inventory_id = $1
  AND s.status = 'picking'
`

// Bottles spoken for on shipments that are still being picked. Picking
// does not decrement the lot — stock leaves once, at the shipment — so
// this is what stands between two pickers promising the same bottles.
func (q *Queries) BottlesPickedFromLot(ctx context.Context, packagedInventoryID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bottlesPickedFromLot, packagedInventoryID)
	var picked int32
	err := row.Scan(&picked)
	return picked, err
}

const cancelShipment = `-- name: CancelShipment :one
UPDATE shipments
SET status = 'cancelled', cancelled_at = NOW(), cancel_reason = $2
WHERE id = $1 AND status = 'picking'
RETURNING id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type CancelShipmentParams struct {
	ID           uuid.UUID `json:"id"`
	CancelReason string    `json:"cancel_reason"`
}

func (q *Queries) CancelShipment(ctx context.Context, arg CancelShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, cancelShipment, arg.ID, arg.CancelReason)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (
    tenant_id, customer_id, order_no, ordered_on, required_by,
    customer_reference, price_list_id, location_id, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, customer_id, order_no, status, ordered_on, required_by, customer_reference, price_list_id, location_id, notes, confirmed_at, confirmed_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type CreateSalesOrderParams struct {
	TenantID          uuid.UUID     `json:"tenant_id"`
	CustomerID        uuid.UUID     `json:"customer_id"`
	OrderNo           int32         `json:"order_no"`
	OrderedOn         pgtype.Date   `json:"ordered_on"`
	RequiredBy        pgtype.Date   `json:"required_by"`
	CustomerReference string        `json:"customer_reference"`
	PriceListID       uuid.NullUUID `json:"price_list_id"`
	LocationID        uuid.NullUUID `json:"location_id"`
	Notes             string        `json:"notes"`
	CreatedBy         uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.TenantID,
		arg.CustomerID,
		arg.OrderNo,
		arg.OrderedOn,
		arg.RequiredBy,
		arg.CustomerReference,
		arg.PriceListID,
		arg.LocationID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNo,
		&i.Status,
		&i.OrderedOn,
		&i.RequiredBy,
		&i.CustomerReference,
		&i.PriceListID,
		&i.LocationID,
		&i.Notes,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    tenant_id, sales_order_id, customer_id, shipment_no, location_id,
    ship_date, carrier, tracking_ref, bol_reference, notes, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type CreateShipmentParams struct {
	TenantID     uuid.UUID     `json:"tenant_id"`
	SalesOrderID uuid.NullUUID `json:"sales_order_id"`
	CustomerID   uuid.UUID     `json:"customer_id"`
	ShipmentNo   int32         `json:"shipment_no"`
	LocationID   uuid.NullUUID `json:"location_id"`
	ShipDate     pgtype.Date   `json:"ship_date"`
	Carrier      string        `json:"carrier"`
	TrackingRef  string        `json:"tracking_ref"`
	BolReference string        `json:"bol_reference"`
	Notes        string        `json:"notes"`
	CreatedBy    uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.TenantID,
		arg.SalesOrderID,
		arg.CustomerID,
		arg.ShipmentNo,
		arg.LocationID,
		arg.ShipDate,
		arg.Carrier,
		arg.TrackingRef,
		arg.BolReference,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSalesOrderLine = `-- name: DeleteSalesOrderLine :exec
DELETE FROM sales_order_lines WHERE id = $1
`

func (q *Queries) DeleteSalesOrderLine(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderLine, id)
	return err
}

const deleteShipmentLine = `-- name: DeleteShipmentLine :exec
DELETE FROM shipment_lines WHERE id = $1
`

func (q *Queries) DeleteShipmentLine(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShipmentLine, id)
	return err
}

const getPriceListEntryForProduct = `-- name: GetPriceListEntryForProduct :one
SELECT id, tenant_id, price_list_id, product_id, unit_price, case_size, created_at, updated_at FROM price_list_entries WHERE price_list_id = $1 AND product_id = $2
`

type GetPriceListEntryForProductParams struct {
	PriceListID uuid.UUID `json:"price_list_id"`
	ProductID   uuid.UUID `json:"product_id"`
}

func (q *Queries) GetPriceListEntryForProduct(ctx context.Context, arg GetPriceListEntryForProductParams) (PriceListEntry, error) {
	row := q.db.QueryRow(ctx, getPriceListEntryForProduct, arg.PriceListID, arg.ProductID)
	var i PriceListEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PriceListID,
		&i.ProductID,
		&i.UnitPrice,
		&i.CaseSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, tenant_id, customer_id, order_no, status, ordered_on, required_by, customer_reference, price_list_id, location_id, notes, confirmed_at, confirmed_by, cancelled_at, cancel_reason, created_by, created_at, updated_at FROM sales_orders WHERE id = $1
`

func (q *Queries) GetSalesOrder(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNo,
		&i.Status,
		&i.OrderedOn,
		&i.RequiredBy,
		&i.CustomerReference,
		&i.PriceListID,
		&i.LocationID,
		&i.Notes,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderLineForUpdate = `-- name: GetSalesOrderLineForUpdate :one
SELECT id, tenant_id, sales_order_id, product_id, bottles_ordered, bottles_shipped, unit_price, notes, created_at, updated_at FROM sales_order_lines WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSalesOrderLineForUpdate(ctx context.Context, id uuid.UUID) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, getSalesOrderLineForUpdate, id)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.ProductID,
		&i.BottlesOrdered,
		&i.BottlesShipped,
		&i.UnitPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at FROM shipments WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipmentForUpdate = `-- name: GetShipmentForUpdate :one
SELECT id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at FROM shipments WHERE id = $1 FOR UPDATE
`

// Locked before shipping: shipping twice would write two sets of
// removals against one pallet and double the duty on the return.
func (q *Queries) GetShipmentForUpdate(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentForUpdate, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipmentLine = `-- name: GetShipmentLine :one
SELECT id, tenant_id, shipment_id, sales_order_line_id, packaged_inventory_id, bottles, packaging_removal_id, notes, created_at FROM shipment_lines WHERE id = $1
`

func (q *Queries) GetShipmentLine(ctx context.Context, id uuid.UUID) (ShipmentLine, error) {
	row := q.db.QueryRow(ctx, getShipmentLine, id)
	var i ShipmentLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShipmentID,
		&i.SalesOrderLineID,
		&i.PackagedInventoryID,
		&i.Bottles,
		&i.PackagingRemovalID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const incrementSalesOrderLineShipped = `-- name: IncrementSalesOrderLineShipped :one
UPDATE sales_order_lines
SET bottles_shipped = bottles_shipped + $2
WHERE id = $1
RETURNING id, tenant_id, sales_order_id, product_id, bottles_ordered, bottles_shipped, unit_price, notes, created_at, updated_at
`

type IncrementSalesOrderLineShippedParams struct {
	ID             uuid.UUID `json:"id"`
	BottlesShipped int32     `json:"bottles_shipped"`
}

func (q *Queries) IncrementSalesOrderLineShipped(ctx context.Context, arg IncrementSalesOrderLineShippedParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, incrementSalesOrderLineShipped, arg.ID, arg.BottlesShipped)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.ProductID,
		&i.BottlesOrdered,
		&i.BottlesShipped,
		&i.UnitPrice,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkShipmentLineRemoval = `-- name: LinkShipmentLineRemoval :exec
UPDATE shipment_lines SET packaging_removal_id = $2 WHERE id = $1
`

type LinkShipmentLineRemovalParams struct {
	ID                 uuid.UUID     `json:"id"`
	PackagingRemovalID uuid.NullUUID `json:"packaging_removal_id"`
}

func (q *Queries) LinkShipmentLineRemoval(ctx context.Context, arg LinkShipmentLineRemovalParams) error {
	_, err := q.db.Exec(ctx, linkShipmentLineRemoval, arg.ID, arg.PackagingRemovalID)
	return err
}

const listSalesOrderLines = `-- name: ListSalesOrderLines :many
SELECT l.id, l.tenant_id, l.sales_order_id, l.product_id, l.bottles_ordered, l.bottles_shipped, l.unit_price, l.notes, l.created_at, l.updated_at, p.name AS product_name, p.bottle_size_ml, p.target_abv_pct
FROM sales_order_lines l
JOIN products p ON p.id = l.product_id
WHERE l.sales_order_id = $1
ORDER BY p.name
`

type ListSalesOrderLinesRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	SalesOrderID   uuid.UUID          `json:"sales_order_id"`
	ProductID      uuid.UUID          `json:"product_id"`
	BottlesOrdered int32              `json:"bottles_ordered"`
	BottlesShipped int32              `json:"bottles_shipped"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProductName    string             `json:"product_name"`
	BottleSizeMl   int32              `json:"bottle_size_ml"`
	TargetAbvPct   float64            `json:"target_abv_pct"`
}

func (q *Queries) ListSalesOrderLines(ctx context.Context, salesOrderID uuid.UUID) ([]ListSalesOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLines, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrderLinesRow{}
	for rows.Next() {
		var i ListSalesOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SalesOrderID,
			&i.ProductID,
			&i.BottlesOrdered,
			&i.BottlesShipped,
			&i.UnitPrice,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.BottleSizeMl,
			&i.TargetAbvPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT so.id, so.tenant_id, so.customer_id, so.order_no, so.status, so.ordered_on, so.required_by, so.customer_reference, so.price_list_id, so.location_id, so.notes, so.confirmed_at, so.confirmed_by, so.cancelled_at, so.cancel_reason, so.created_by, so.created_at, so.updated_at, c.name AS customer_name,
       COUNT(l.id)::INTEGER AS line_count,
       COALESCE(SUM(l.bottles_ordered), 0)::INTEGER AS bottles_ordered,
       COALESCE(SUM(l.bottles_shipped), 0)::INTEGER AS bottles_shipped
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
LEFT JOIN sales_order_lines l ON l.sales_order_id = so.id
WHERE ($1::BOOLEAN = FALSE
       OR so.status IN ('draft', 'confirmed', 'partially_shipped'))
GROUP BY so.id, c.name
ORDER BY so.required_by NULLS LAST, so.order_no DESC
`

type ListSalesOrdersRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	OrderNo           int32              `json:"order_no"`
	Status            SalesOrderStatus   `json:"status"`
	OrderedOn         pgtype.Date        `json:"ordered_on"`
	RequiredBy        pgtype.Date        `json:"required_by"`
	CustomerReference string             `json:"customer_reference"`
	PriceListID       uuid.NullUUID      `json:"price_list_id"`
	LocationID        uuid.NullUUID      `json:"location_id"`
	Notes             string             `json:"notes"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedBy       uuid.NullUUID      `json:"confirmed_by"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason      string             `json:"cancel_reason"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CustomerName      string             `json:"customer_name"`
	LineCount         int32              `json:"line_count"`
	BottlesOrdered    int32              `json:"bottles_ordered"`
	BottlesShipped    int32              `json:"bottles_shipped"`
}

func (q *Queries) ListSalesOrders(ctx context.Context, openOnly bool) ([]ListSalesOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, openOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrdersRow{}
	for rows.Next() {
		var i ListSalesOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.OrderNo,
			&i.Status,
			&i.OrderedOn,
			&i.RequiredBy,
			&i.CustomerReference,
			&i.PriceListID,
			&i.LocationID,
			&i.Notes,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.LineCount,
			&i.BottlesOrdered,
			&i.BottlesShipped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentLines = `-- name: ListShipmentLines :many
SELECT sl.id, sl.tenant_id, sl.shipment_id, sl.sales_order_line_id, sl.packaged_inventory_id, sl.bottles, sl.packaging_removal_id, sl.notes, sl.created_at, pi.lot_code, pi.jurisdiction, pi.bottles_on_hand,
       p.name AS product_name, p.bottle_size_ml, p.target_abv_pct,
       pi.released_at, pi.held_at
FROM shipment_lines sl
JOIN packaged_inventory pi ON pi.id = sl.packaged_inventory_id
JOIN products p            ON p.id = pi.product_id
WHERE sl.shipment_id = $1
ORDER BY p.name, pi.lot_code
`

type ListShipmentLinesRow struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	ShipmentID          uuid.UUID          `json:"shipment_id"`
	SalesOrderLineID    uuid.NullUUID      `json:"sales_order_line_id"`
	PackagedInventoryID uuid.UUID          `json:"packaged_inventory_id"`
	Bottles             int32              `json:"bottles"`
	PackagingRemovalID  uuid.NullUUID      `json:"packaging_removal_id"`
	Notes               string             `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	LotCode             string             `json:"lot_code"`
	Jurisdiction        string             `json:"jurisdiction"`
	BottlesOnHand       int32              `json:"bottles_on_hand"`
	ProductName         string             `json:"product_name"`
	BottleSizeMl        int32              `json:"bottle_size_ml"`
	TargetAbvPct        float64            `json:"target_abv_pct"`
	ReleasedAt          pgtype.Timestamptz `json:"released_at"`
	HeldAt              pgtype.Timestamptz `json:"held_at"`
}

func (q *Queries) ListShipmentLines(ctx context.Context, shipmentID uuid.UUID) ([]ListShipmentLinesRow, error) {
	rows, err := q.db.Query(ctx, listShipmentLines, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentLinesRow{}
	for rows.Next() {
		var i ListShipmentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShipmentID,
			&i.SalesOrderLineID,
			&i.PackagedInventoryID,
			&i.Bottles,
			&i.PackagingRemovalID,
			&i.Notes,
			&i.CreatedAt,
			&i.LotCode,
			&i.Jurisdiction,
			&i.BottlesOnHand,
			&i.ProductName,
			&i.BottleSizeMl,
			&i.TargetAbvPct,
			&i.ReleasedAt,
			&i.HeldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT s.id, s.tenant_id, s.sales_order_id, s.customer_id, s.shipment_no, s.status, s.location_id, s.ship_date, s.carrier, s.tracking_ref, s.bol_reference, s.notes, s.shipped_at, s.shipped_by, s.cancelled_at, s.cancel_reason, s.created_by, s.created_at, s.updated_at, c.name AS customer_name,
       COALESCE(so.order_no, 0)::INTEGER AS order_no,
       COUNT(sl.id)::INTEGER AS line_count,
       COALESCE(SUM(sl.bottles), 0)::INTEGER AS bottles
FROM shipments s
JOIN customers c ON c.id = s.customer_id
LEFT JOIN sales_orders so ON so.id = s.sales_order_id
LEFT JOIN shipment_lines sl ON sl.shipment_id = s.id
WHERE ($1::BOOLEAN = FALSE OR s.status = 'picking')
GROUP BY s.id, c.name, so.order_no
ORDER BY s.ship_date NULLS LAST, s.shipment_no DESC
`

type ListShipmentsRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	SalesOrderID uuid.NullUUID      `json:"sales_order_id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	ShipmentNo   int32              `json:"shipment_no"`
	Status       ShipmentStatus     `json:"status"`
	LocationID   uuid.NullUUID      `json:"location_id"`
	ShipDate     pgtype.Date        `json:"ship_date"`
	Carrier      string             `json:"carrier"`
	TrackingRef  string             `json:"tracking_ref"`
	BolReference string             `json:"bol_reference"`
	Notes        string             `json:"notes"`
	ShippedAt    pgtype.Timestamptz `json:"shipped_at"`
	ShippedBy    uuid.NullUUID      `json:"shipped_by"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason string             `json:"cancel_reason"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CustomerName string             `json:"customer_name"`
	OrderNo      int32              `json:"order_no"`
	LineCount    int32              `json:"line_count"`
	Bottles      int32              `json:"bottles"`
}

func (q *Queries) ListShipments(ctx context.Context, openOnly bool) ([]ListShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listShipments, openOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentsRow{}
	for rows.Next() {
		var i ListShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SalesOrderID,
			&i.CustomerID,
			&i.ShipmentNo,
			&i.Status,
			&i.LocationID,
			&i.ShipDate,
			&i.Carrier,
			&i.TrackingRef,
			&i.BolReference,
			&i.Notes,
			&i.ShippedAt,
			&i.ShippedBy,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.OrderNo,
			&i.LineCount,
			&i.Bottles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShipmentShipped = `-- name: MarkShipmentShipped :one
UPDATE shipments
SET status = 'shipped', shipped_at = NOW(), shipped_by = $2,
    ship_date = COALESCE(ship_date, CURRENT_DATE)
WHERE id = $1 AND status = 'picking'
RETURNING id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type MarkShipmentShippedParams struct {
	ID        uuid.UUID     `json:"id"`
	ShippedBy uuid.NullUUID `json:"shipped_by"`
}

func (q *Queries) MarkShipmentShipped(ctx context.Context, arg MarkShipmentShippedParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, markShipmentShipped, arg.ID, arg.ShippedBy)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextSalesOrderNo = `-- name: NextSalesOrderNo :one
SELECT COALESCE(MAX(order_no), 0)::INTEGER + 1 AS next FROM sales_orders
`

func (q *Queries) NextSalesOrderNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextSalesOrderNo)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const nextShipmentNo = `-- name: NextShipmentNo :one
SELECT COALESCE(MAX(shipment_no), 0)::INTEGER + 1 AS next FROM shipments
`

func (q *Queries) NextShipmentNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextShipmentNo)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const reservedBottlesForProduct = `-- name: ReservedBottlesForProduct :one
SELECT COALESCE(SUM(l.bottles_ordered - l.bottles_shipped), 0)::INTEGER AS reserved
FROM sales_order_lines l
JOIN sales_orders so ON so.id = l.sales_order_id
WHERE l.product_id = $1
  AND so.status IN ('confirmed', 'partially_shipped')
  AND l.bottles_shipped < l.bottles_ordered
`

// What is spoken for on confirmed, unshipped order lines. Deliberately a
// read rather than a decrement: the alcohol has not moved, and a B266
// built on promises rather than movements would be wrong. This tells the
// screen; it does not tell the ledger.
func (q *Queries) ReservedBottlesForProduct(ctx context.Context, productID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, reservedBottlesForProduct, productID)
	var reserved int32
	err := row.Scan(&reserved)
	return reserved, err
}

const salesOrderOutstanding = `-- name: SalesOrderOutstanding :one
SELECT
    COUNT(*) FILTER (WHERE l.bottles_shipped < l.bottles_ordered)::INTEGER AS lines_outstanding,
    COUNT(*) FILTER (WHERE l.bottles_shipped > 0)::INTEGER                 AS lines_started
FROM sales_order_lines l
WHERE l.sales_order_id = $1
`

type SalesOrderOutstandingRow struct {
	LinesOutstanding int32 `json:"lines_outstanding"`
	LinesStarted     int32 `json:"lines_started"`
}

func (q *Queries) SalesOrderOutstanding(ctx context.Context, salesOrderID uuid.UUID) (SalesOrderOutstandingRow, error) {
	row := q.db.QueryRow(ctx, salesOrderOutstanding, salesOrderID)
	var i SalesOrderOutstandingRow
	err := row.Scan(&i.LinesOutstanding, &i.LinesStarted)
	return i, err
}

const setRemovalShipment = `-- name: SetRemovalShipment :exec
UPDATE packaging_removals SET shipment_id = $2 WHERE id = $1
`

type SetRemovalShipmentParams struct {
	ID         uuid.UUID     `json:"id"`
	ShipmentID uuid.NullUUID `json:"shipment_id"`
}

func (q *Queries) SetRemovalShipment(ctx context.Context, arg SetRemovalShipmentParams) error {
	_, err := q.db.Exec(ctx, setRemovalShipment, arg.ID, arg.ShipmentID)
	return err
}

const setSalesOrderStatus = `-- name: SetSalesOrderStatus :one
UPDATE sales_orders SET
    status       = $1::sales_order_status,
    confirmed_at = CASE WHEN $1::sales_order_status = 'confirmed'
                         AND confirmed_at IS NULL THEN NOW() ELSE confirmed_at END,
    confirmed_by = CASE WHEN $1::sales_order_status = 'confirmed'
                         AND confirmed_by IS NULL THEN $2::UUID ELSE confirmed_by END,
    cancelled_at = CASE WHEN $1::sales_order_status = 'cancelled'
                        THEN NOW() ELSE cancelled_at END,
    cancel_reason = CASE WHEN $1::sales_order_status = 'cancelled'
                         THEN $3::TEXT ELSE cancel_reason END
WHERE id = $4
RETURNING id, tenant_id, customer_id, order_no, status, ordered_on, required_by, customer_reference, price_list_id, location_id, notes, confirmed_at, confirmed_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type SetSalesOrderStatusParams struct {
	Status       SalesOrderStatus `json:"status"`
	Actor        uuid.NullUUID    `json:"actor"`
	CancelReason string           `json:"cancel_reason"`
	ID           uuid.UUID        `json:"id"`
}

func (q *Queries) SetSalesOrderStatus(ctx context.Context, arg SetSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, setSalesOrderStatus,
		arg.Status,
		arg.Actor,
		arg.CancelReason,
		arg.ID,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.OrderNo,
		&i.Status,
		&i.OrderedOn,
		&i.RequiredBy,
		&i.CustomerReference,
		&i.PriceListID,
		&i.LocationID,
		&i.Notes,
		&i.ConfirmedAt,
		&i.ConfirmedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setShipmentShipDate = `-- name: SetShipmentShipDate :one
UPDATE shipments SET ship_date = $2 WHERE id = $1 RETURNING id, tenant_id, sales_order_id, customer_id, shipment_no, status, location_id, ship_date, carrier, tracking_ref, bol_reference, notes, shipped_at, shipped_by, cancelled_at, cancel_reason, created_by, created_at, updated_at
`

type SetShipmentShipDateParams struct {
	ID       uuid.UUID   `json:"id"`
	ShipDate pgtype.Date `json:"ship_date"`
}

func (q *Queries) SetShipmentShipDate(ctx context.Context, arg SetShipmentShipDateParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, setShipmentShipDate, arg.ID, arg.ShipDate)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SalesOrderID,
		&i.CustomerID,
		&i.ShipmentNo,
		&i.Status,
		&i.LocationID,
		&i.ShipDate,
		&i.Carrier,
		&i.TrackingRef,
		&i.BolReference,
		&i.Notes,
		&i.ShippedAt,
		&i.ShippedBy,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shipmentLotBreakdown = `-- name: ShipmentLotBreakdown :many
SELECT sl.bottles, p.bottle_size_ml, p.target_abv_pct
FROM shipment_lines sl
JOIN packaged_inventory pi ON pi.id = sl.packaged_inventory_id
JOIN products p            ON p.id = pi.product_id
WHERE sl.shipment_id = $1
`

type ShipmentLotBreakdownRow struct {
	Bottles      int32   `json:"bottles"`
	BottleSizeMl int32   `json:"bottle_size_ml"`
	TargetAbvPct float64 `json:"target_abv_pct"`
}

// What a picker is about to put on the return, per lot, before they
// commit to it.
func (q *Queries) ShipmentLotBreakdown(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentLotBreakdownRow, error) {
	rows, err := q.db.Query(ctx, shipmentLotBreakdown, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShipmentLotBreakdownRow{}
	for rows.Next() {
		var i ShipmentLotBreakdownRow
		if err := rows.Scan(&i.Bottles, &i.BottleSizeMl, &i.TargetAbvPct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stockCommitments = `-- name: StockCommitments :many
SELECT
    p.id   AS product_id,
    p.name AS product_name,
    p.bottle_size_ml,
    p.target_abv_pct,
    COALESCE(SUM(pi.bottles_on_hand), 0)::INTEGER AS bottles_on_hand,
    COALESCE((
        SELECT SUM(l.bottles_ordered - l.bottles_shipped)
        FROM sales_order_lines l
        JOIN sales_orders so ON so.id = l.sales_order_id
        WHERE l.product_id = p.id
          AND so.status IN ('confirmed', 'partially_shipped')
          AND l.bottles_shipped < l.bottles_ordered
    ), 0)::INTEGER AS bottles_reserved,
    COALESCE((
        SELECT SUM(sl.bottles)
        FROM shipment_lines sl
        JOIN shipments s          ON s.id = sl.shipment_id
        JOIN packaged_inventory q ON q.id = sl.packaged_inventory_id
        WHERE q.product_id = p.id
          AND s.status = 'picking'
    ), 0)::INTEGER AS bottles_picked
FROM products p
LEFT JOIN packaged_inventory pi ON pi.product_id = p.id
GROUP BY p.id, p.name, p.bottle_size_ml, p.target_abv_pct
HAVING COALESCE(SUM(pi.bottles_on_hand), 0) > 0
    OR COALESCE((
        SELECT SUM(l.bottles_ordered - l.bottles_shipped)
        FROM sales_order_lines l
        JOIN sales_orders so ON so.id = l.sales_order_id
        WHERE l.product_id = p.id
          AND so.status IN ('confirmed', 'partially_shipped')
          AND l.bottles_shipped < l.bottles_ordered
    ), 0) > 0
ORDER BY p.name
`

type StockCommitmentsRow struct {
	ProductID       uuid.UUID `json:"product_id"`
	ProductName     string    `json:"product_name"`
	BottleSizeMl    int32     `json:"bottle_size_ml"`
	TargetAbvPct    float64   `json:"target_abv_pct"`
	BottlesOnHand   int32     `json:"bottles_on_hand"`
	BottlesReserved int32     `json:"bottles_reserved"`
	BottlesPicked   int32     `json:"bottles_picked"`
}

// On hand, spoken for, picked and free — per product.
//
// The three middle columns are the reason reservation can stay soft. The
// alcohol has not moved, so nothing is decremented and the B266 is built
// from movements only; but the screen still tells an operator that the
// cases in front of them are already promised to somebody.
func (q *Queries) StockCommitments(ctx context.Context) ([]StockCommitmentsRow, error) {
	rows, err := q.db.Query(ctx, stockCommitments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockCommitmentsRow{}
	for rows.Next() {
		var i StockCommitmentsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.BottleSizeMl,
			&i.TargetAbvPct,
			&i.BottlesOnHand,
			&i.BottlesReserved,
			&i.BottlesPicked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
