// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traceability.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const barrelDumpsForContainerFill = `-- name: BarrelDumpsForContainerFill :many
SELECT bm.id AS movement_id, bm.occurred_at,
       barrel.id AS barrel_id, barrel.name AS barrel_name,
       ba.cooperage_supplier, ba.fill_date, ba.days_aged_at_dump
FROM bulk_movements bm
JOIN bulk_containers barrel       ON barrel.id = bm.source_container_id
LEFT JOIN barrel_attributes ba    ON ba.container_id = barrel.id
WHERE bm.id = $1
  AND barrel.kind = 'barrel'
`

type BarrelDumpsForContainerFillRow struct {
	MovementID        uuid.UUID          `json:"movement_id"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	BarrelID          uuid.UUID          `json:"barrel_id"`
	BarrelName        string             `json:"barrel_name"`
	CooperageSupplier pgtype.Text        `json:"cooperage_supplier"`
	FillDate          pgtype.Date        `json:"fill_date"`
	DaysAgedAtDump    pgtype.Int4        `json:"days_aged_at_dump"`
}

// For a barrel_dump-tagged bulk_movement, return the barrel + its fill
// history (so we can include the original distillation behind the fill).
func (q *Queries) BarrelDumpsForContainerFill(ctx context.Context, id uuid.UUID) ([]BarrelDumpsForContainerFillRow, error) {
	rows, err := q.db.Query(ctx, barrelDumpsForContainerFill, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BarrelDumpsForContainerFillRow{}
	for rows.Next() {
		var i BarrelDumpsForContainerFillRow
		if err := rows.Scan(
			&i.MovementID,
			&i.OccurredAt,
			&i.BarrelID,
			&i.BarrelName,
			&i.CooperageSupplier,
			&i.FillDate,
			&i.DaysAgedAtDump,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bottlingRunChainFeeds = `-- name: BottlingRunChainFeeds :many
SELECT bm.id, bm.tenant_id, bm.source_container_id, bm.destination_container_id, bm.volume_l, bm.abv_pct, bm.laa, bm.reason, bm.reference_type, bm.reference_id, bm.notes, bm.occurred_at, bm.created_at, bm.counterparty_name, bm.counterparty_licence_no, bm.document_reference, bm.temperature_c, bm.observed_volume_l, bm.observed_density_kg_m3, bm.volume_factor_c, bm.strength_source, bm.volume_instrument_id, bm.strength_instrument_id, bm.temperature_instrument_id, bm.recorded_by, bm.packaged_inventory_id, bm.bottles_unpackaged, bm.loss_duty_treatment, bm.loss_treatment_authority, bm.loss_classified_by, bm.loss_classified_at,
       src.name AS source_name,
       dst.name AS destination_name
FROM bulk_movements bm
LEFT JOIN bulk_containers src ON src.id = bm.source_container_id
LEFT JOIN bulk_containers dst ON dst.id = bm.destination_container_id
WHERE bm.destination_container_id = $1
  AND bm.occurred_at <= $2
  AND bm.occurred_at >= $2 - INTERVAL '365 days'
ORDER BY bm.occurred_at DESC
`

type BottlingRunChainFeedsParams struct {
	DestinationContainerID uuid.NullUUID      `json:"destination_container_id"`
	OccurredAt             pgtype.Timestamptz `json:"occurred_at"`
}

type BottlingRunChainFeedsRow struct {
	ID                      uuid.UUID          `json:"id"`
	TenantID                uuid.UUID          `json:"tenant_id"`
	SourceContainerID       uuid.NullUUID      `json:"source_container_id"`
	DestinationContainerID  uuid.NullUUID      `json:"destination_container_id"`
	VolumeL                 float64            `json:"volume_l"`
	AbvPct                  float64            `json:"abv_pct"`
	Laa                     float64            `json:"laa"`
	Reason                  BulkMovementReason `json:"reason"`
	ReferenceType           string             `json:"reference_type"`
	ReferenceID             uuid.NullUUID      `json:"reference_id"`
	Notes                   string             `json:"notes"`
	OccurredAt              pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CounterpartyName        string             `json:"counterparty_name"`
	CounterpartyLicenceNo   string             `json:"counterparty_licence_no"`
	DocumentReference       string             `json:"document_reference"`
	TemperatureC            pgtype.Float8      `json:"temperature_c"`
	ObservedVolumeL         pgtype.Float8      `json:"observed_volume_l"`
	ObservedDensityKgM3     pgtype.Float8      `json:"observed_density_kg_m3"`
	VolumeFactorC           float64            `json:"volume_factor_c"`
	StrengthSource          StrengthSource     `json:"strength_source"`
	VolumeInstrumentID      uuid.NullUUID      `json:"volume_instrument_id"`
	StrengthInstrumentID    uuid.NullUUID      `json:"strength_instrument_id"`
	TemperatureInstrumentID uuid.NullUUID      `json:"temperature_instrument_id"`
	RecordedBy              uuid.NullUUID      `json:"recorded_by"`
	PackagedInventoryID     uuid.NullUUID      `json:"packaged_inventory_id"`
	BottlesUnpackaged       pgtype.Int4        `json:"bottles_unpackaged"`
	LossDutyTreatment       LossDutyTreatment  `json:"loss_duty_treatment"`
	LossTreatmentAuthority  string             `json:"loss_treatment_authority"`
	LossClassifiedBy        uuid.NullUUID      `json:"loss_classified_by"`
	LossClassifiedAt        pgtype.Timestamptz `json:"loss_classified_at"`
	SourceName              pgtype.Text        `json:"source_name"`
	DestinationName         pgtype.Text        `json:"destination_name"`
}

// Given a bottling run, return the bulk_movements that fed into its source
// container in the 365 days leading up to the bottling date. Most useful
// when the source container is a blend tank or spirit receiver that
// collected from multiple barrels/distillations.
func (q *Queries) BottlingRunChainFeeds(ctx context.Context, arg BottlingRunChainFeedsParams) ([]BottlingRunChainFeedsRow, error) {
	rows, err := q.db.Query(ctx, bottlingRunChainFeeds, arg.DestinationContainerID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BottlingRunChainFeedsRow{}
	for rows.Next() {
		var i BottlingRunChainFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceContainerID,
			&i.DestinationContainerID,
			&i.VolumeL,
			&i.AbvPct,
			&i.Laa,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Notes,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CounterpartyName,
			&i.CounterpartyLicenceNo,
			&i.DocumentReference,
			&i.TemperatureC,
			&i.ObservedVolumeL,
			&i.ObservedDensityKgM3,
			&i.VolumeFactorC,
			&i.StrengthSource,
			&i.VolumeInstrumentID,
			&i.StrengthInstrumentID,
			&i.TemperatureInstrumentID,
			&i.RecordedBy,
			&i.PackagedInventoryID,
			&i.BottlesUnpackaged,
			&i.LossDutyTreatment,
			&i.LossTreatmentAuthority,
			&i.LossClassifiedBy,
			&i.LossClassifiedAt,
			&i.SourceName,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const distillationChainFromGauge = `-- name: DistillationChainFromGauge :many
SELECT dr.id AS distillation_run_id, dr.run_no AS distillation_run_no, dr.still_label,
       fr.id AS fermentation_run_id, fr.fermenter_label,
       fr.yeast_lot_id AS yeast_lot_id,
       yml.supplier_lot AS yeast_supplier_lot,
       ym.name          AS yeast_material_name,
       mr.id AS mash_run_id, mr.mash_no, mr.mash_date,
       rv.id AS recipe_version_id, rv.version_no AS recipe_version_no,
       r.id  AS recipe_id, r.name AS recipe_name,
       dc.charge_order AS charge_order
FROM production_gauges pg
JOIN distillation_runs dr      ON dr.id = pg.distillation_run_id
LEFT JOIN distillation_charges dc ON dc.distillation_run_id = dr.id
LEFT JOIN fermentation_runs fr    ON fr.id = dc.fermentation_run_id
LEFT JOIN material_lots yml       ON yml.id = fr.yeast_lot_id
LEFT JOIN materials ym            ON ym.id = fr.yeast_material_id
LEFT JOIN mash_runs mr            ON mr.id = fr.mash_run_id
LEFT JOIN recipe_versions rv      ON rv.id = mr.recipe_version_id
LEFT JOIN recipes r               ON r.id = rv.recipe_id
WHERE pg.bulk_movement_id = $1
ORDER BY dc.charge_order
`

type DistillationChainFromGaugeRow struct {
	DistillationRunID uuid.UUID     `json:"distillation_run_id"`
	DistillationRunNo int32         `json:"distillation_run_no"`
	StillLabel        string        `json:"still_label"`
	FermentationRunID uuid.NullUUID `json:"fermentation_run_id"`
	FermenterLabel    pgtype.Text   `json:"fermenter_label"`
	YeastLotID        uuid.NullUUID `json:"yeast_lot_id"`
	YeastSupplierLot  pgtype.Text   `json:"yeast_supplier_lot"`
	YeastMaterialName pgtype.Text   `json:"yeast_material_name"`
	MashRunID         uuid.NullUUID `json:"mash_run_id"`
	MashNo            pgtype.Int4   `json:"mash_no"`
	MashDate          pgtype.Date   `json:"mash_date"`
	RecipeVersionID   uuid.NullUUID `json:"recipe_version_id"`
	RecipeVersionNo   pgtype.Int4   `json:"recipe_version_no"`
	RecipeID          uuid.NullUUID `json:"recipe_id"`
	RecipeName        pgtype.Text   `json:"recipe_name"`
	ChargeOrder       pgtype.Int4   `json:"charge_order"`
}

// Pull the distillation run + every charge → ferment → mash → recipe
// subtree behind a production_gauge bulk_movement. One row per charge
// so multi-charge blends are fully represented in trace + cost rollups.
func (q *Queries) DistillationChainFromGauge(ctx context.Context, bulkMovementID uuid.UUID) ([]DistillationChainFromGaugeRow, error) {
	rows, err := q.db.Query(ctx, distillationChainFromGauge, bulkMovementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistillationChainFromGaugeRow{}
	for rows.Next() {
		var i DistillationChainFromGaugeRow
		if err := rows.Scan(
			&i.DistillationRunID,
			&i.DistillationRunNo,
			&i.StillLabel,
			&i.FermentationRunID,
			&i.FermenterLabel,
			&i.YeastLotID,
			&i.YeastSupplierLot,
			&i.YeastMaterialName,
			&i.MashRunID,
			&i.MashNo,
			&i.MashDate,
			&i.RecipeVersionID,
			&i.RecipeVersionNo,
			&i.RecipeID,
			&i.RecipeName,
			&i.ChargeOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallContainersFedBy = `-- name: RecallContainersFedBy :many
WITH RECURSIVE reached AS (
    SELECT m.destination_container_id AS container_id, 1 AS depth
    FROM bulk_movements m
    WHERE m.source_container_id = $1
      AND m.destination_container_id IS NOT NULL
      AND m.occurred_at >= $2::timestamptz
    UNION
    SELECT m.destination_container_id, r.depth + 1
    FROM bulk_movements m
    JOIN reached r ON r.container_id = m.source_container_id
    WHERE m.destination_container_id IS NOT NULL
      AND m.occurred_at >= $2::timestamptz
      AND r.depth < 10
)
SELECT r.container_id::uuid AS container_id,
       MIN(r.depth)::int AS depth,
       COALESCE(c.name, '')::text AS container_name
FROM reached r
LEFT JOIN bulk_containers c ON c.id = r.container_id
GROUP BY r.container_id, c.name
ORDER BY MIN(r.depth), c.name
`

type RecallContainersFedByParams struct {
	ContainerID uuid.NullUUID      `json:"container_id"`
	Since       pgtype.Timestamptz `json:"since"`
}

type RecallContainersFedByRow struct {
	ContainerID   uuid.UUID `json:"container_id"`
	Depth         int32     `json:"depth"`
	ContainerName string    `json:"container_name"`
}

// Every container the given one reached, following the movement graph
// forward. PLAN I5.
//
// Recursive because spirit does not move once. A cask is dumped into a
// vatting tank, the vatting tank feeds a bottling tank, and a walk that
// followed one hop would under-recall — which is the failure that leaves
// affected stock on a shelf. An unbounded walk over-recalls, so it is
// capped and the depth reached is reported: an operator told "followed 3
// moves" can judge whether that is the whole story, and one told nothing
// cannot.
//
// Only movements at or after the origin date count. Spirit that left a
// tank before the affected spirit arrived did not carry it.
func (q *Queries) RecallContainersFedBy(ctx context.Context, arg RecallContainersFedByParams) ([]RecallContainersFedByRow, error) {
	rows, err := q.db.Query(ctx, recallContainersFedBy, arg.ContainerID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallContainersFedByRow{}
	for rows.Next() {
		var i RecallContainersFedByRow
		if err := rows.Scan(&i.ContainerID, &i.Depth, &i.ContainerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallExactChainFromMaterialLot = `-- name: RecallExactChainFromMaterialLot :many
SELECT ml.id            AS material_lot_id,
       ml.supplier_lot,
       m.name           AS material_name,
       s.name           AS supplier_name,
       mr.id            AS mash_run_id,
       mr.mash_no,
       mr.mash_date,
       mu.quantity_used,
       mu.uom,
       fr.id            AS fermentation_run_id,
       fr.fermenter_label,
       dr.id            AS distillation_run_id,
       dr.run_no        AS distillation_run_no,
       dr.voided_at     AS distillation_voided_at,
       g.id             AS production_gauge_id,
       g.gauge_date,
       g.laa            AS gauge_laa,
       g.destination_container_id,
       bc.name          AS container_name
FROM material_lots ml
JOIN materials m               ON m.id = ml.material_id
LEFT JOIN suppliers s          ON s.id = ml.supplier_id
JOIN mash_ingredient_usage mu  ON mu.material_lot_id = ml.id
JOIN mash_runs mr              ON mr.id = mu.mash_run_id
LEFT JOIN fermentation_runs fr ON fr.mash_run_id = mr.id
LEFT JOIN distillation_charges dc ON dc.fermentation_run_id = fr.id
LEFT JOIN distillation_runs dr ON dr.id = dc.distillation_run_id
LEFT JOIN production_gauges g  ON g.distillation_run_id = dr.id
LEFT JOIN bulk_containers bc   ON bc.id = g.destination_container_id
WHERE ml.id = $1
ORDER BY mr.mash_date, mr.mash_no, fr.fermenter_label, dr.run_no
`

type RecallExactChainFromMaterialLotRow struct {
	MaterialLotID          uuid.UUID          `json:"material_lot_id"`
	SupplierLot            string             `json:"supplier_lot"`
	MaterialName           string             `json:"material_name"`
	SupplierName           pgtype.Text        `json:"supplier_name"`
	MashRunID              uuid.UUID          `json:"mash_run_id"`
	MashNo                 int32              `json:"mash_no"`
	MashDate               pgtype.Date        `json:"mash_date"`
	QuantityUsed           float64            `json:"quantity_used"`
	Uom                    string             `json:"uom"`
	FermentationRunID      uuid.NullUUID      `json:"fermentation_run_id"`
	FermenterLabel         pgtype.Text        `json:"fermenter_label"`
	DistillationRunID      uuid.NullUUID      `json:"distillation_run_id"`
	DistillationRunNo      pgtype.Int4        `json:"distillation_run_no"`
	DistillationVoidedAt   pgtype.Timestamptz `json:"distillation_voided_at"`
	ProductionGaugeID      uuid.NullUUID      `json:"production_gauge_id"`
	GaugeDate              pgtype.Timestamptz `json:"gauge_date"`
	GaugeLaa               pgtype.Float8      `json:"gauge_laa"`
	DestinationContainerID uuid.NullUUID      `json:"destination_container_id"`
	ContainerName          pgtype.Text        `json:"container_name"`
}

// Forward from a material lot to every production gauge it reached.
//
// This half of a recall is exact. A material lot goes into named mashes,
// those mashes into named fermentations, those into named distillation
// charges, and each run has one gauge. Every link is a recorded row and
// nothing is inferred.
//
// Where it stops is the point of the query. A gauge puts spirit into a
// container, and from there it is blended, transferred and vatted — after
// which "which mash is in this tank" is no longer a fact the ledger
// holds. Everything past the gauge is possible contact, not certainty,
// and is asked for separately so the two never get added together.
func (q *Queries) RecallExactChainFromMaterialLot(ctx context.Context, materialLotID uuid.UUID) ([]RecallExactChainFromMaterialLotRow, error) {
	rows, err := q.db.Query(ctx, recallExactChainFromMaterialLot, materialLotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallExactChainFromMaterialLotRow{}
	for rows.Next() {
		var i RecallExactChainFromMaterialLotRow
		if err := rows.Scan(
			&i.MaterialLotID,
			&i.SupplierLot,
			&i.MaterialName,
			&i.SupplierName,
			&i.MashRunID,
			&i.MashNo,
			&i.MashDate,
			&i.QuantityUsed,
			&i.Uom,
			&i.FermentationRunID,
			&i.FermenterLabel,
			&i.DistillationRunID,
			&i.DistillationRunNo,
			&i.DistillationVoidedAt,
			&i.ProductionGaugeID,
			&i.GaugeDate,
			&i.GaugeLaa,
			&i.DestinationContainerID,
			&i.ContainerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallPackagedLotOneDown = `-- name: RecallPackagedLotOneDown :many
SELECT r.id, r.removal_date, r.bottles_removed, r.destination_name,
       r.voided_at,
       COALESCE(c.name, '')::text AS customer_name,
       COALESCE(c.id::text, '')::text AS customer_id,
       pi.lot_code, pi.id AS packaged_inventory_id,
       pi.bottles_on_hand
FROM packaging_removals r
JOIN packaged_inventory pi ON pi.id = r.packaged_inventory_id
LEFT JOIN customers c      ON c.id = r.customer_id
WHERE pi.id = $1
ORDER BY r.removal_date, r.id
`

type RecallPackagedLotOneDownRow struct {
	ID                  uuid.UUID          `json:"id"`
	RemovalDate         pgtype.Date        `json:"removal_date"`
	BottlesRemoved      int32              `json:"bottles_removed"`
	DestinationName     string             `json:"destination_name"`
	VoidedAt            pgtype.Timestamptz `json:"voided_at"`
	CustomerName        string             `json:"customer_name"`
	CustomerID          string             `json:"customer_id"`
	LotCode             string             `json:"lot_code"`
	PackagedInventoryID uuid.UUID          `json:"packaged_inventory_id"`
	BottlesOnHand       int32              `json:"bottles_on_hand"`
}

// Who received a specific packaged lot. Exact, not possible contact: the
// lot code IS the thing being recalled, so there is no inference here at
// all — which is why a consumer complaint naming a lot code is the
// easiest recall to answer and the most common one to get.
func (q *Queries) RecallPackagedLotOneDown(ctx context.Context, packagedInventoryID uuid.UUID) ([]RecallPackagedLotOneDownRow, error) {
	rows, err := q.db.Query(ctx, recallPackagedLotOneDown, packagedInventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallPackagedLotOneDownRow{}
	for rows.Next() {
		var i RecallPackagedLotOneDownRow
		if err := rows.Scan(
			&i.ID,
			&i.RemovalDate,
			&i.BottlesRemoved,
			&i.DestinationName,
			&i.VoidedAt,
			&i.CustomerName,
			&i.CustomerID,
			&i.LotCode,
			&i.PackagedInventoryID,
			&i.BottlesOnHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallPackagedLotsFromContainerSet = `-- name: RecallPackagedLotsFromContainerSet :many
SELECT br.id            AS bottling_run_id,
       br.bottling_date AS bottled_on,
       br.bottle_count,
       br.voided_at     AS bottling_voided_at,
       br.source_container_id,
       bc.name          AS container_name,
       pi.id            AS packaged_inventory_id,
       pi.lot_code,
       pi.bottles_packaged,
       pi.bottles_on_hand,
       pi.bottles_removed,
       p.name           AS product_name
FROM bottling_runs br
JOIN bulk_containers bc        ON bc.id = br.source_container_id
LEFT JOIN packaged_inventory pi ON pi.bottling_run_id = br.id
LEFT JOIN products p           ON p.id = pi.product_id
WHERE br.source_container_id = ANY($1::uuid[])
  AND br.bottling_date >= $2::date
ORDER BY br.bottling_date, br.id
`

type RecallPackagedLotsFromContainerSetParams struct {
	ContainerIds []uuid.UUID `json:"container_ids"`
	Earliest     pgtype.Date `json:"earliest"`
}

type RecallPackagedLotsFromContainerSetRow struct {
	BottlingRunID       uuid.UUID          `json:"bottling_run_id"`
	BottledOn           pgtype.Date        `json:"bottled_on"`
	BottleCount         int32              `json:"bottle_count"`
	BottlingVoidedAt    pgtype.Timestamptz `json:"bottling_voided_at"`
	SourceContainerID   uuid.UUID          `json:"source_container_id"`
	ContainerName       string             `json:"container_name"`
	PackagedInventoryID uuid.NullUUID      `json:"packaged_inventory_id"`
	LotCode             pgtype.Text        `json:"lot_code"`
	BottlesPackaged     pgtype.Int4        `json:"bottles_packaged"`
	BottlesOnHand       pgtype.Int4        `json:"bottles_on_hand"`
	BottlesRemoved      pgtype.Int4        `json:"bottles_removed"`
	ProductName         pgtype.Text        `json:"product_name"`
}

// Bottling runs drawing from any of a set of containers, on or after the
// date affected spirit could have been in them.
func (q *Queries) RecallPackagedLotsFromContainerSet(ctx context.Context, arg RecallPackagedLotsFromContainerSetParams) ([]RecallPackagedLotsFromContainerSetRow, error) {
	rows, err := q.db.Query(ctx, recallPackagedLotsFromContainerSet, arg.ContainerIds, arg.Earliest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallPackagedLotsFromContainerSetRow{}
	for rows.Next() {
		var i RecallPackagedLotsFromContainerSetRow
		if err := rows.Scan(
			&i.BottlingRunID,
			&i.BottledOn,
			&i.BottleCount,
			&i.BottlingVoidedAt,
			&i.SourceContainerID,
			&i.ContainerName,
			&i.PackagedInventoryID,
			&i.LotCode,
			&i.BottlesPackaged,
			&i.BottlesOnHand,
			&i.BottlesRemoved,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallPackagedLotsFromContainers = `-- name: RecallPackagedLotsFromContainers :many
SELECT br.id            AS bottling_run_id,
       br.bottling_date AS bottled_on,
       br.bottle_count,
       br.voided_at     AS bottling_voided_at,
       br.source_container_id,
       bc.name          AS container_name,
       pi.id            AS packaged_inventory_id,
       pi.lot_code,
       pi.bottles_packaged,
       pi.bottles_on_hand,
       pi.bottles_removed,
       p.name           AS product_name
FROM bottling_runs br
JOIN bulk_containers bc        ON bc.id = br.source_container_id
LEFT JOIN packaged_inventory pi ON pi.bottling_run_id = br.id
LEFT JOIN products p           ON p.id = pi.product_id
WHERE br.source_container_id = ANY($1::uuid[])
  AND br.bottling_date >= $2::date
ORDER BY br.bottling_date, br.id
`

type RecallPackagedLotsFromContainersParams struct {
	ContainerIds []uuid.UUID `json:"container_ids"`
	Earliest     pgtype.Date `json:"earliest"`
}

type RecallPackagedLotsFromContainersRow struct {
	BottlingRunID       uuid.UUID          `json:"bottling_run_id"`
	BottledOn           pgtype.Date        `json:"bottled_on"`
	BottleCount         int32              `json:"bottle_count"`
	BottlingVoidedAt    pgtype.Timestamptz `json:"bottling_voided_at"`
	SourceContainerID   uuid.UUID          `json:"source_container_id"`
	ContainerName       string             `json:"container_name"`
	PackagedInventoryID uuid.NullUUID      `json:"packaged_inventory_id"`
	LotCode             pgtype.Text        `json:"lot_code"`
	BottlesPackaged     pgtype.Int4        `json:"bottles_packaged"`
	BottlesOnHand       pgtype.Int4        `json:"bottles_on_hand"`
	BottlesRemoved      pgtype.Int4        `json:"bottles_removed"`
	ProductName         pgtype.Text        `json:"product_name"`
}

// Bottling runs that drew from a container after affected spirit entered
// it, and the packaged lots they produced.
//
// Possible contact, not certainty, and the distinction is load-bearing in
// both directions: treating it as certainty recalls stock that was never
// affected, and ignoring it leaves affected stock on a shelf. Stillhouse
// reports the boundary and does not decide which side of it an operator
// should act on — that is a food-safety judgement with a cost attached,
// and it is theirs.
//
// "After" is by bottling date against the earliest affected gauge into
// that container. A run that bottled before the spirit arrived cannot
// contain it.
func (q *Queries) RecallPackagedLotsFromContainers(ctx context.Context, arg RecallPackagedLotsFromContainersParams) ([]RecallPackagedLotsFromContainersRow, error) {
	rows, err := q.db.Query(ctx, recallPackagedLotsFromContainers, arg.ContainerIds, arg.Earliest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallPackagedLotsFromContainersRow{}
	for rows.Next() {
		var i RecallPackagedLotsFromContainersRow
		if err := rows.Scan(
			&i.BottlingRunID,
			&i.BottledOn,
			&i.BottleCount,
			&i.BottlingVoidedAt,
			&i.SourceContainerID,
			&i.ContainerName,
			&i.PackagedInventoryID,
			&i.LotCode,
			&i.BottlesPackaged,
			&i.BottlesOnHand,
			&i.BottlesRemoved,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recallRemovalsForPackagedLots = `-- name: RecallRemovalsForPackagedLots :many
SELECT r.id,
       r.removal_date,
       r.bottles_removed,
       r.destination_name,
       r.voided_at,
       COALESCE(c.name, '')::text AS customer_name,
       COALESCE(c.id::text, '')::text AS customer_id,
       pi.lot_code,
       pi.id AS packaged_inventory_id
FROM packaging_removals r
JOIN packaged_inventory pi ON pi.id = r.packaged_inventory_id
LEFT JOIN customers c      ON c.id = r.customer_id
WHERE r.packaged_inventory_id = ANY($1::uuid[])
ORDER BY r.removal_date, r.id
`

type RecallRemovalsForPackagedLotsRow struct {
	ID                  uuid.UUID          `json:"id"`
	RemovalDate         pgtype.Date        `json:"removal_date"`
	BottlesRemoved      int32              `json:"bottles_removed"`
	DestinationName     string             `json:"destination_name"`
	VoidedAt            pgtype.Timestamptz `json:"voided_at"`
	CustomerName        string             `json:"customer_name"`
	CustomerID          string             `json:"customer_id"`
	LotCode             string             `json:"lot_code"`
	PackagedInventoryID uuid.UUID          `json:"packaged_inventory_id"`
}

// One down: every removal of an affected packaged lot, and who received
// it. This is the list a recall notice is written from.
//
// Voided removals are excluded — the stock did not leave — but a voided
// removal is not the same as one that never happened, so the caller is
// told the count separately rather than the rows just being absent.
func (q *Queries) RecallRemovalsForPackagedLots(ctx context.Context, packagedInventoryIds []uuid.UUID) ([]RecallRemovalsForPackagedLotsRow, error) {
	rows, err := q.db.Query(ctx, recallRemovalsForPackagedLots, packagedInventoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallRemovalsForPackagedLotsRow{}
	for rows.Next() {
		var i RecallRemovalsForPackagedLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.RemovalDate,
			&i.BottlesRemoved,
			&i.DestinationName,
			&i.VoidedAt,
			&i.CustomerName,
			&i.CustomerID,
			&i.LotCode,
			&i.PackagedInventoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
