// Personal access tokens for non-browser clients (MCP, scripts).
// Each user manages their own. The plaintext value is shown ONCE at
// issue time and never again — only the SHA-256 hash lives in the DB.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stillhouse/v1/api_token.proto

package stillhousev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// APITokenServiceName is the fully-qualified name of the APITokenService service.
	APITokenServiceName = "stillhouse.v1.APITokenService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// APITokenServiceIssueAPITokenProcedure is the fully-qualified name of the APITokenService's
	// IssueAPIToken RPC.
	APITokenServiceIssueAPITokenProcedure = "/stillhouse.v1.APITokenService/IssueAPIToken"
	// APITokenServiceListAPITokensProcedure is the fully-qualified name of the APITokenService's
	// ListAPITokens RPC.
	APITokenServiceListAPITokensProcedure = "/stillhouse.v1.APITokenService/ListAPITokens"
	// APITokenServiceRevokeAPITokenProcedure is the fully-qualified name of the APITokenService's
	// RevokeAPIToken RPC.
	APITokenServiceRevokeAPITokenProcedure = "/stillhouse.v1.APITokenService/RevokeAPIToken"
)

// APITokenServiceClient is a client for the stillhouse.v1.APITokenService service.
type APITokenServiceClient interface {
	IssueAPIToken(context.Context, *connect.Request[v1.IssueAPITokenRequest]) (*connect.Response[v1.IssueAPITokenResponse], error)
	ListAPITokens(context.Context, *connect.Request[v1.ListAPITokensRequest]) (*connect.Response[v1.ListAPITokensResponse], error)
	RevokeAPIToken(context.Context, *connect.Request[v1.RevokeAPITokenRequest]) (*connect.Response[v1.RevokeAPITokenResponse], error)
}

// NewAPITokenServiceClient constructs a client for the stillhouse.v1.APITokenService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAPITokenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) APITokenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	aPITokenServiceMethods := v1.File_stillhouse_v1_api_token_proto.Services().ByName("APITokenService").Methods()
	return &aPITokenServiceClient{
		issueAPIToken: connect.NewClient[v1.IssueAPITokenRequest, v1.IssueAPITokenResponse](
			httpClient,
			baseURL+APITokenServiceIssueAPITokenProcedure,
			connect.WithSchema(aPITokenServiceMethods.ByName("IssueAPIToken")),
			connect.WithClientOptions(opts...),
		),
		listAPITokens: connect.NewClient[v1.ListAPITokensRequest, v1.ListAPITokensResponse](
			httpClient,
			baseURL+APITokenServiceListAPITokensProcedure,
			connect.WithSchema(aPITokenServiceMethods.ByName("ListAPITokens")),
			connect.WithClientOptions(opts...),
		),
		revokeAPIToken: connect.NewClient[v1.RevokeAPITokenRequest, v1.RevokeAPITokenResponse](
			httpClient,
			baseURL+APITokenServiceRevokeAPITokenProcedure,
			connect.WithSchema(aPITokenServiceMethods.ByName("RevokeAPIToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// aPITokenServiceClient implements APITokenServiceClient.
type aPITokenServiceClient struct {
	issueAPIToken  *connect.Client[v1.IssueAPITokenRequest, v1.IssueAPITokenResponse]
	listAPITokens  *connect.Client[v1.ListAPITokensRequest, v1.ListAPITokensResponse]
	revokeAPIToken *connect.Client[v1.RevokeAPITokenRequest, v1.RevokeAPITokenResponse]
}

// IssueAPIToken calls stillhouse.v1.APITokenService.IssueAPIToken.
func (c *aPITokenServiceClient) IssueAPIToken(ctx context.Context, req *connect.Request[v1.IssueAPITokenRequest]) (*connect.Response[v1.IssueAPITokenResponse], error) {
	return c.issueAPIToken.CallUnary(ctx, req)
}

// ListAPITokens calls stillhouse.v1.APITokenService.ListAPITokens.
func (c *aPITokenServiceClient) ListAPITokens(ctx context.Context, req *connect.Request[v1.ListAPITokensRequest]) (*connect.Response[v1.ListAPITokensResponse], error) {
	return c.listAPITokens.CallUnary(ctx, req)
}

// RevokeAPIToken calls stillhouse.v1.APITokenService.RevokeAPIToken.
func (c *aPITokenServiceClient) RevokeAPIToken(ctx context.Context, req *connect.Request[v1.RevokeAPITokenRequest]) (*connect.Response[v1.RevokeAPITokenResponse], error) {
	return c.revokeAPIToken.CallUnary(ctx, req)
}

// APITokenServiceHandler is an implementation of the stillhouse.v1.APITokenService service.
type APITokenServiceHandler interface {
	IssueAPIToken(context.Context, *connect.Request[v1.IssueAPITokenRequest]) (*connect.Response[v1.IssueAPITokenResponse], error)
	ListAPITokens(context.Context, *connect.Request[v1.ListAPITokensRequest]) (*connect.Response[v1.ListAPITokensResponse], error)
	RevokeAPIToken(context.Context, *connect.Request[v1.RevokeAPITokenRequest]) (*connect.Response[v1.RevokeAPITokenResponse], error)
}

// NewAPITokenServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAPITokenServiceHandler(svc APITokenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aPITokenServiceMethods := v1.File_stillhouse_v1_api_token_proto.Services().ByName("APITokenService").Methods()
	aPITokenServiceIssueAPITokenHandler := connect.NewUnaryHandler(
		APITokenServiceIssueAPITokenProcedure,
		svc.IssueAPIToken,
		connect.WithSchema(aPITokenServiceMethods.ByName("IssueAPIToken")),
		connect.WithHandlerOptions(opts...),
	)
	aPITokenServiceListAPITokensHandler := connect.NewUnaryHandler(
		APITokenServiceListAPITokensProcedure,
		svc.ListAPITokens,
		connect.WithSchema(aPITokenServiceMethods.ByName("ListAPITokens")),
		connect.WithHandlerOptions(opts...),
	)
	aPITokenServiceRevokeAPITokenHandler := connect.NewUnaryHandler(
		APITokenServiceRevokeAPITokenProcedure,
		svc.RevokeAPIToken,
		connect.WithSchema(aPITokenServiceMethods.ByName("RevokeAPIToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/stillhouse.v1.APITokenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case APITokenServiceIssueAPITokenProcedure:
			aPITokenServiceIssueAPITokenHandler.ServeHTTP(w, r)
		case APITokenServiceListAPITokensProcedure:
			aPITokenServiceListAPITokensHandler.ServeHTTP(w, r)
		case APITokenServiceRevokeAPITokenProcedure:
			aPITokenServiceRevokeAPITokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAPITokenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAPITokenServiceHandler struct{}

func (UnimplementedAPITokenServiceHandler) IssueAPIToken(context.Context, *connect.Request[v1.IssueAPITokenRequest]) (*connect.Response[v1.IssueAPITokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.APITokenService.IssueAPIToken is not implemented"))
}

func (UnimplementedAPITokenServiceHandler) ListAPITokens(context.Context, *connect.Request[v1.ListAPITokensRequest]) (*connect.Response[v1.ListAPITokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.APITokenService.ListAPITokens is not implemented"))
}

func (UnimplementedAPITokenServiceHandler) RevokeAPIToken(context.Context, *connect.Request[v1.RevokeAPITokenRequest]) (*connect.Response[v1.RevokeAPITokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.APITokenService.RevokeAPIToken is not implemented"))
}
