// What a batch cost, beyond the grain.
//
// BottlingRunCost has been direct materials only, and said so honestly on
// every line. That is not a cost: a distillery whose cost of sales is the
// price of barley believes its whisky costs eight dollars a bottle, and
// prices it accordingly. Migration 000040 left two WIP journal kinds
// unemitted rather than invent a valuation, and wrote down what was
// needed first — labour, overhead absorption, and a WIP convention.
//
// The rates are the licensee's own policy. Nothing here has a default:
// an unset rate makes its component unavailable and says so, rather than
// absorbing zero and reporting a partial cost as a full one.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stillhouse/v1/costing.proto

package stillhousev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CostingServiceName is the fully-qualified name of the CostingService service.
	CostingServiceName = "stillhouse.v1.CostingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CostingServiceSaveCostRatesProcedure is the fully-qualified name of the CostingService's
	// SaveCostRates RPC.
	CostingServiceSaveCostRatesProcedure = "/stillhouse.v1.CostingService/SaveCostRates"
	// CostingServiceListCostRatesProcedure is the fully-qualified name of the CostingService's
	// ListCostRates RPC.
	CostingServiceListCostRatesProcedure = "/stillhouse.v1.CostingService/ListCostRates"
	// CostingServiceDeleteCostRatesProcedure is the fully-qualified name of the CostingService's
	// DeleteCostRates RPC.
	CostingServiceDeleteCostRatesProcedure = "/stillhouse.v1.CostingService/DeleteCostRates"
	// CostingServiceRecordLabourProcedure is the fully-qualified name of the CostingService's
	// RecordLabour RPC.
	CostingServiceRecordLabourProcedure = "/stillhouse.v1.CostingService/RecordLabour"
	// CostingServiceDeleteLabourEntryProcedure is the fully-qualified name of the CostingService's
	// DeleteLabourEntry RPC.
	CostingServiceDeleteLabourEntryProcedure = "/stillhouse.v1.CostingService/DeleteLabourEntry"
	// CostingServiceListLabourProcedure is the fully-qualified name of the CostingService's ListLabour
	// RPC.
	CostingServiceListLabourProcedure = "/stillhouse.v1.CostingService/ListLabour"
	// CostingServiceBottlingRunFullCostProcedure is the fully-qualified name of the CostingService's
	// BottlingRunFullCost RPC.
	CostingServiceBottlingRunFullCostProcedure = "/stillhouse.v1.CostingService/BottlingRunFullCost"
	// CostingServiceInventoryValueProcedure is the fully-qualified name of the CostingService's
	// InventoryValue RPC.
	CostingServiceInventoryValueProcedure = "/stillhouse.v1.CostingService/InventoryValue"
)

// CostingServiceClient is a client for the stillhouse.v1.CostingService service.
type CostingServiceClient interface {
	SaveCostRates(context.Context, *connect.Request[v1.SaveCostRatesRequest]) (*connect.Response[v1.SaveCostRatesResponse], error)
	ListCostRates(context.Context, *connect.Request[v1.ListCostRatesRequest]) (*connect.Response[v1.ListCostRatesResponse], error)
	DeleteCostRates(context.Context, *connect.Request[v1.DeleteCostRatesRequest]) (*connect.Response[v1.DeleteCostRatesResponse], error)
	RecordLabour(context.Context, *connect.Request[v1.RecordLabourRequest]) (*connect.Response[v1.RecordLabourResponse], error)
	DeleteLabourEntry(context.Context, *connect.Request[v1.DeleteLabourEntryRequest]) (*connect.Response[v1.DeleteLabourEntryResponse], error)
	ListLabour(context.Context, *connect.Request[v1.ListLabourRequest]) (*connect.Response[v1.ListLabourResponse], error)
	BottlingRunFullCost(context.Context, *connect.Request[v1.BottlingRunFullCostRequest]) (*connect.Response[v1.BottlingRunFullCostResponse], error)
	InventoryValue(context.Context, *connect.Request[v1.InventoryValueRequest]) (*connect.Response[v1.InventoryValueResponse], error)
}

// NewCostingServiceClient constructs a client for the stillhouse.v1.CostingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCostingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CostingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	costingServiceMethods := v1.File_stillhouse_v1_costing_proto.Services().ByName("CostingService").Methods()
	return &costingServiceClient{
		saveCostRates: connect.NewClient[v1.SaveCostRatesRequest, v1.SaveCostRatesResponse](
			httpClient,
			baseURL+CostingServiceSaveCostRatesProcedure,
			connect.WithSchema(costingServiceMethods.ByName("SaveCostRates")),
			connect.WithClientOptions(opts...),
		),
		listCostRates: connect.NewClient[v1.ListCostRatesRequest, v1.ListCostRatesResponse](
			httpClient,
			baseURL+CostingServiceListCostRatesProcedure,
			connect.WithSchema(costingServiceMethods.ByName("ListCostRates")),
			connect.WithClientOptions(opts...),
		),
		deleteCostRates: connect.NewClient[v1.DeleteCostRatesRequest, v1.DeleteCostRatesResponse](
			httpClient,
			baseURL+CostingServiceDeleteCostRatesProcedure,
			connect.WithSchema(costingServiceMethods.ByName("DeleteCostRates")),
			connect.WithClientOptions(opts...),
		),
		recordLabour: connect.NewClient[v1.RecordLabourRequest, v1.RecordLabourResponse](
			httpClient,
			baseURL+CostingServiceRecordLabourProcedure,
			connect.WithSchema(costingServiceMethods.ByName("RecordLabour")),
			connect.WithClientOptions(opts...),
		),
		deleteLabourEntry: connect.NewClient[v1.DeleteLabourEntryRequest, v1.DeleteLabourEntryResponse](
			httpClient,
			baseURL+CostingServiceDeleteLabourEntryProcedure,
			connect.WithSchema(costingServiceMethods.ByName("DeleteLabourEntry")),
			connect.WithClientOptions(opts...),
		),
		listLabour: connect.NewClient[v1.ListLabourRequest, v1.ListLabourResponse](
			httpClient,
			baseURL+CostingServiceListLabourProcedure,
			connect.WithSchema(costingServiceMethods.ByName("ListLabour")),
			connect.WithClientOptions(opts...),
		),
		bottlingRunFullCost: connect.NewClient[v1.BottlingRunFullCostRequest, v1.BottlingRunFullCostResponse](
			httpClient,
			baseURL+CostingServiceBottlingRunFullCostProcedure,
			connect.WithSchema(costingServiceMethods.ByName("BottlingRunFullCost")),
			connect.WithClientOptions(opts...),
		),
		inventoryValue: connect.NewClient[v1.InventoryValueRequest, v1.InventoryValueResponse](
			httpClient,
			baseURL+CostingServiceInventoryValueProcedure,
			connect.WithSchema(costingServiceMethods.ByName("InventoryValue")),
			connect.WithClientOptions(opts...),
		),
	}
}

// costingServiceClient implements CostingServiceClient.
type costingServiceClient struct {
	saveCostRates       *connect.Client[v1.SaveCostRatesRequest, v1.SaveCostRatesResponse]
	listCostRates       *connect.Client[v1.ListCostRatesRequest, v1.ListCostRatesResponse]
	deleteCostRates     *connect.Client[v1.DeleteCostRatesRequest, v1.DeleteCostRatesResponse]
	recordLabour        *connect.Client[v1.RecordLabourRequest, v1.RecordLabourResponse]
	deleteLabourEntry   *connect.Client[v1.DeleteLabourEntryRequest, v1.DeleteLabourEntryResponse]
	listLabour          *connect.Client[v1.ListLabourRequest, v1.ListLabourResponse]
	bottlingRunFullCost *connect.Client[v1.BottlingRunFullCostRequest, v1.BottlingRunFullCostResponse]
	inventoryValue      *connect.Client[v1.InventoryValueRequest, v1.InventoryValueResponse]
}

// SaveCostRates calls stillhouse.v1.CostingService.SaveCostRates.
func (c *costingServiceClient) SaveCostRates(ctx context.Context, req *connect.Request[v1.SaveCostRatesRequest]) (*connect.Response[v1.SaveCostRatesResponse], error) {
	return c.saveCostRates.CallUnary(ctx, req)
}

// ListCostRates calls stillhouse.v1.CostingService.ListCostRates.
func (c *costingServiceClient) ListCostRates(ctx context.Context, req *connect.Request[v1.ListCostRatesRequest]) (*connect.Response[v1.ListCostRatesResponse], error) {
	return c.listCostRates.CallUnary(ctx, req)
}

// DeleteCostRates calls stillhouse.v1.CostingService.DeleteCostRates.
func (c *costingServiceClient) DeleteCostRates(ctx context.Context, req *connect.Request[v1.DeleteCostRatesRequest]) (*connect.Response[v1.DeleteCostRatesResponse], error) {
	return c.deleteCostRates.CallUnary(ctx, req)
}

// RecordLabour calls stillhouse.v1.CostingService.RecordLabour.
func (c *costingServiceClient) RecordLabour(ctx context.Context, req *connect.Request[v1.RecordLabourRequest]) (*connect.Response[v1.RecordLabourResponse], error) {
	return c.recordLabour.CallUnary(ctx, req)
}

// DeleteLabourEntry calls stillhouse.v1.CostingService.DeleteLabourEntry.
func (c *costingServiceClient) DeleteLabourEntry(ctx context.Context, req *connect.Request[v1.DeleteLabourEntryRequest]) (*connect.Response[v1.DeleteLabourEntryResponse], error) {
	return c.deleteLabourEntry.CallUnary(ctx, req)
}

// ListLabour calls stillhouse.v1.CostingService.ListLabour.
func (c *costingServiceClient) ListLabour(ctx context.Context, req *connect.Request[v1.ListLabourRequest]) (*connect.Response[v1.ListLabourResponse], error) {
	return c.listLabour.CallUnary(ctx, req)
}

// BottlingRunFullCost calls stillhouse.v1.CostingService.BottlingRunFullCost.
func (c *costingServiceClient) BottlingRunFullCost(ctx context.Context, req *connect.Request[v1.BottlingRunFullCostRequest]) (*connect.Response[v1.BottlingRunFullCostResponse], error) {
	return c.bottlingRunFullCost.CallUnary(ctx, req)
}

// InventoryValue calls stillhouse.v1.CostingService.InventoryValue.
func (c *costingServiceClient) InventoryValue(ctx context.Context, req *connect.Request[v1.InventoryValueRequest]) (*connect.Response[v1.InventoryValueResponse], error) {
	return c.inventoryValue.CallUnary(ctx, req)
}

// CostingServiceHandler is an implementation of the stillhouse.v1.CostingService service.
type CostingServiceHandler interface {
	SaveCostRates(context.Context, *connect.Request[v1.SaveCostRatesRequest]) (*connect.Response[v1.SaveCostRatesResponse], error)
	ListCostRates(context.Context, *connect.Request[v1.ListCostRatesRequest]) (*connect.Response[v1.ListCostRatesResponse], error)
	DeleteCostRates(context.Context, *connect.Request[v1.DeleteCostRatesRequest]) (*connect.Response[v1.DeleteCostRatesResponse], error)
	RecordLabour(context.Context, *connect.Request[v1.RecordLabourRequest]) (*connect.Response[v1.RecordLabourResponse], error)
	DeleteLabourEntry(context.Context, *connect.Request[v1.DeleteLabourEntryRequest]) (*connect.Response[v1.DeleteLabourEntryResponse], error)
	ListLabour(context.Context, *connect.Request[v1.ListLabourRequest]) (*connect.Response[v1.ListLabourResponse], error)
	BottlingRunFullCost(context.Context, *connect.Request[v1.BottlingRunFullCostRequest]) (*connect.Response[v1.BottlingRunFullCostResponse], error)
	InventoryValue(context.Context, *connect.Request[v1.InventoryValueRequest]) (*connect.Response[v1.InventoryValueResponse], error)
}

// NewCostingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCostingServiceHandler(svc CostingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	costingServiceMethods := v1.File_stillhouse_v1_costing_proto.Services().ByName("CostingService").Methods()
	costingServiceSaveCostRatesHandler := connect.NewUnaryHandler(
		CostingServiceSaveCostRatesProcedure,
		svc.SaveCostRates,
		connect.WithSchema(costingServiceMethods.ByName("SaveCostRates")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceListCostRatesHandler := connect.NewUnaryHandler(
		CostingServiceListCostRatesProcedure,
		svc.ListCostRates,
		connect.WithSchema(costingServiceMethods.ByName("ListCostRates")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceDeleteCostRatesHandler := connect.NewUnaryHandler(
		CostingServiceDeleteCostRatesProcedure,
		svc.DeleteCostRates,
		connect.WithSchema(costingServiceMethods.ByName("DeleteCostRates")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceRecordLabourHandler := connect.NewUnaryHandler(
		CostingServiceRecordLabourProcedure,
		svc.RecordLabour,
		connect.WithSchema(costingServiceMethods.ByName("RecordLabour")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceDeleteLabourEntryHandler := connect.NewUnaryHandler(
		CostingServiceDeleteLabourEntryProcedure,
		svc.DeleteLabourEntry,
		connect.WithSchema(costingServiceMethods.ByName("DeleteLabourEntry")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceListLabourHandler := connect.NewUnaryHandler(
		CostingServiceListLabourProcedure,
		svc.ListLabour,
		connect.WithSchema(costingServiceMethods.ByName("ListLabour")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceBottlingRunFullCostHandler := connect.NewUnaryHandler(
		CostingServiceBottlingRunFullCostProcedure,
		svc.BottlingRunFullCost,
		connect.WithSchema(costingServiceMethods.ByName("BottlingRunFullCost")),
		connect.WithHandlerOptions(opts...),
	)
	costingServiceInventoryValueHandler := connect.NewUnaryHandler(
		CostingServiceInventoryValueProcedure,
		svc.InventoryValue,
		connect.WithSchema(costingServiceMethods.ByName("InventoryValue")),
		connect.WithHandlerOptions(opts...),
	)
	return "/stillhouse.v1.CostingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CostingServiceSaveCostRatesProcedure:
			costingServiceSaveCostRatesHandler.ServeHTTP(w, r)
		case CostingServiceListCostRatesProcedure:
			costingServiceListCostRatesHandler.ServeHTTP(w, r)
		case CostingServiceDeleteCostRatesProcedure:
			costingServiceDeleteCostRatesHandler.ServeHTTP(w, r)
		case CostingServiceRecordLabourProcedure:
			costingServiceRecordLabourHandler.ServeHTTP(w, r)
		case CostingServiceDeleteLabourEntryProcedure:
			costingServiceDeleteLabourEntryHandler.ServeHTTP(w, r)
		case CostingServiceListLabourProcedure:
			costingServiceListLabourHandler.ServeHTTP(w, r)
		case CostingServiceBottlingRunFullCostProcedure:
			costingServiceBottlingRunFullCostHandler.ServeHTTP(w, r)
		case CostingServiceInventoryValueProcedure:
			costingServiceInventoryValueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCostingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCostingServiceHandler struct{}

func (UnimplementedCostingServiceHandler) SaveCostRates(context.Context, *connect.Request[v1.SaveCostRatesRequest]) (*connect.Response[v1.SaveCostRatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.SaveCostRates is not implemented"))
}

func (UnimplementedCostingServiceHandler) ListCostRates(context.Context, *connect.Request[v1.ListCostRatesRequest]) (*connect.Response[v1.ListCostRatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.ListCostRates is not implemented"))
}

func (UnimplementedCostingServiceHandler) DeleteCostRates(context.Context, *connect.Request[v1.DeleteCostRatesRequest]) (*connect.Response[v1.DeleteCostRatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.DeleteCostRates is not implemented"))
}

func (UnimplementedCostingServiceHandler) RecordLabour(context.Context, *connect.Request[v1.RecordLabourRequest]) (*connect.Response[v1.RecordLabourResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.RecordLabour is not implemented"))
}

func (UnimplementedCostingServiceHandler) DeleteLabourEntry(context.Context, *connect.Request[v1.DeleteLabourEntryRequest]) (*connect.Response[v1.DeleteLabourEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.DeleteLabourEntry is not implemented"))
}

func (UnimplementedCostingServiceHandler) ListLabour(context.Context, *connect.Request[v1.ListLabourRequest]) (*connect.Response[v1.ListLabourResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.ListLabour is not implemented"))
}

func (UnimplementedCostingServiceHandler) BottlingRunFullCost(context.Context, *connect.Request[v1.BottlingRunFullCostRequest]) (*connect.Response[v1.BottlingRunFullCostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.BottlingRunFullCost is not implemented"))
}

func (UnimplementedCostingServiceHandler) InventoryValue(context.Context, *connect.Request[v1.InventoryValueRequest]) (*connect.Response[v1.InventoryValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.CostingService.InventoryValue is not implemented"))
}
