// Where, within a licensee.
//
// One tenant was one licence with no place inside it, so a distillery
// with a production site and a rackhouse across town had one
// undifferentiated pile of alcohol. That is a compliance limit before it
// is a convenience one: an excise warehouse licence can specify multiple
// premises, the 30% single-retail-store supply rule is computed per
// premises, and a separate return per branch needs something to divide
// by.
//
// A location is where something *is*, not who owns it. Row-level
// security stays keyed on tenant_id and nothing here narrows it —
// adding a second isolation boundary would double the number of ways to
// get isolation wrong for a gain nobody has asked for.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stillhouse/v1/location.proto

package stillhousev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LocationServiceName is the fully-qualified name of the LocationService service.
	LocationServiceName = "stillhouse.v1.LocationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LocationServiceListLocationsProcedure is the fully-qualified name of the LocationService's
	// ListLocations RPC.
	LocationServiceListLocationsProcedure = "/stillhouse.v1.LocationService/ListLocations"
	// LocationServiceSaveLocationProcedure is the fully-qualified name of the LocationService's
	// SaveLocation RPC.
	LocationServiceSaveLocationProcedure = "/stillhouse.v1.LocationService/SaveLocation"
	// LocationServiceSetContainerLocationProcedure is the fully-qualified name of the LocationService's
	// SetContainerLocation RPC.
	LocationServiceSetContainerLocationProcedure = "/stillhouse.v1.LocationService/SetContainerLocation"
	// LocationServiceRetailSupplyReportProcedure is the fully-qualified name of the LocationService's
	// RetailSupplyReport RPC.
	LocationServiceRetailSupplyReportProcedure = "/stillhouse.v1.LocationService/RetailSupplyReport"
)

// LocationServiceClient is a client for the stillhouse.v1.LocationService service.
type LocationServiceClient interface {
	ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error)
	SaveLocation(context.Context, *connect.Request[v1.SaveLocationRequest]) (*connect.Response[v1.SaveLocationResponse], error)
	SetContainerLocation(context.Context, *connect.Request[v1.SetContainerLocationRequest]) (*connect.Response[v1.SetContainerLocationResponse], error)
	RetailSupplyReport(context.Context, *connect.Request[v1.RetailSupplyReportRequest]) (*connect.Response[v1.RetailSupplyReportResponse], error)
}

// NewLocationServiceClient constructs a client for the stillhouse.v1.LocationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLocationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LocationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	locationServiceMethods := v1.File_stillhouse_v1_location_proto.Services().ByName("LocationService").Methods()
	return &locationServiceClient{
		listLocations: connect.NewClient[v1.ListLocationsRequest, v1.ListLocationsResponse](
			httpClient,
			baseURL+LocationServiceListLocationsProcedure,
			connect.WithSchema(locationServiceMethods.ByName("ListLocations")),
			connect.WithClientOptions(opts...),
		),
		saveLocation: connect.NewClient[v1.SaveLocationRequest, v1.SaveLocationResponse](
			httpClient,
			baseURL+LocationServiceSaveLocationProcedure,
			connect.WithSchema(locationServiceMethods.ByName("SaveLocation")),
			connect.WithClientOptions(opts...),
		),
		setContainerLocation: connect.NewClient[v1.SetContainerLocationRequest, v1.SetContainerLocationResponse](
			httpClient,
			baseURL+LocationServiceSetContainerLocationProcedure,
			connect.WithSchema(locationServiceMethods.ByName("SetContainerLocation")),
			connect.WithClientOptions(opts...),
		),
		retailSupplyReport: connect.NewClient[v1.RetailSupplyReportRequest, v1.RetailSupplyReportResponse](
			httpClient,
			baseURL+LocationServiceRetailSupplyReportProcedure,
			connect.WithSchema(locationServiceMethods.ByName("RetailSupplyReport")),
			connect.WithClientOptions(opts...),
		),
	}
}

// locationServiceClient implements LocationServiceClient.
type locationServiceClient struct {
	listLocations        *connect.Client[v1.ListLocationsRequest, v1.ListLocationsResponse]
	saveLocation         *connect.Client[v1.SaveLocationRequest, v1.SaveLocationResponse]
	setContainerLocation *connect.Client[v1.SetContainerLocationRequest, v1.SetContainerLocationResponse]
	retailSupplyReport   *connect.Client[v1.RetailSupplyReportRequest, v1.RetailSupplyReportResponse]
}

// ListLocations calls stillhouse.v1.LocationService.ListLocations.
func (c *locationServiceClient) ListLocations(ctx context.Context, req *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error) {
	return c.listLocations.CallUnary(ctx, req)
}

// SaveLocation calls stillhouse.v1.LocationService.SaveLocation.
func (c *locationServiceClient) SaveLocation(ctx context.Context, req *connect.Request[v1.SaveLocationRequest]) (*connect.Response[v1.SaveLocationResponse], error) {
	return c.saveLocation.CallUnary(ctx, req)
}

// SetContainerLocation calls stillhouse.v1.LocationService.SetContainerLocation.
func (c *locationServiceClient) SetContainerLocation(ctx context.Context, req *connect.Request[v1.SetContainerLocationRequest]) (*connect.Response[v1.SetContainerLocationResponse], error) {
	return c.setContainerLocation.CallUnary(ctx, req)
}

// RetailSupplyReport calls stillhouse.v1.LocationService.RetailSupplyReport.
func (c *locationServiceClient) RetailSupplyReport(ctx context.Context, req *connect.Request[v1.RetailSupplyReportRequest]) (*connect.Response[v1.RetailSupplyReportResponse], error) {
	return c.retailSupplyReport.CallUnary(ctx, req)
}

// LocationServiceHandler is an implementation of the stillhouse.v1.LocationService service.
type LocationServiceHandler interface {
	ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error)
	SaveLocation(context.Context, *connect.Request[v1.SaveLocationRequest]) (*connect.Response[v1.SaveLocationResponse], error)
	SetContainerLocation(context.Context, *connect.Request[v1.SetContainerLocationRequest]) (*connect.Response[v1.SetContainerLocationResponse], error)
	RetailSupplyReport(context.Context, *connect.Request[v1.RetailSupplyReportRequest]) (*connect.Response[v1.RetailSupplyReportResponse], error)
}

// NewLocationServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLocationServiceHandler(svc LocationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	locationServiceMethods := v1.File_stillhouse_v1_location_proto.Services().ByName("LocationService").Methods()
	locationServiceListLocationsHandler := connect.NewUnaryHandler(
		LocationServiceListLocationsProcedure,
		svc.ListLocations,
		connect.WithSchema(locationServiceMethods.ByName("ListLocations")),
		connect.WithHandlerOptions(opts...),
	)
	locationServiceSaveLocationHandler := connect.NewUnaryHandler(
		LocationServiceSaveLocationProcedure,
		svc.SaveLocation,
		connect.WithSchema(locationServiceMethods.ByName("SaveLocation")),
		connect.WithHandlerOptions(opts...),
	)
	locationServiceSetContainerLocationHandler := connect.NewUnaryHandler(
		LocationServiceSetContainerLocationProcedure,
		svc.SetContainerLocation,
		connect.WithSchema(locationServiceMethods.ByName("SetContainerLocation")),
		connect.WithHandlerOptions(opts...),
	)
	locationServiceRetailSupplyReportHandler := connect.NewUnaryHandler(
		LocationServiceRetailSupplyReportProcedure,
		svc.RetailSupplyReport,
		connect.WithSchema(locationServiceMethods.ByName("RetailSupplyReport")),
		connect.WithHandlerOptions(opts...),
	)
	return "/stillhouse.v1.LocationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LocationServiceListLocationsProcedure:
			locationServiceListLocationsHandler.ServeHTTP(w, r)
		case LocationServiceSaveLocationProcedure:
			locationServiceSaveLocationHandler.ServeHTTP(w, r)
		case LocationServiceSetContainerLocationProcedure:
			locationServiceSetContainerLocationHandler.ServeHTTP(w, r)
		case LocationServiceRetailSupplyReportProcedure:
			locationServiceRetailSupplyReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLocationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLocationServiceHandler struct{}

func (UnimplementedLocationServiceHandler) ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.LocationService.ListLocations is not implemented"))
}

func (UnimplementedLocationServiceHandler) SaveLocation(context.Context, *connect.Request[v1.SaveLocationRequest]) (*connect.Response[v1.SaveLocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.LocationService.SaveLocation is not implemented"))
}

func (UnimplementedLocationServiceHandler) SetContainerLocation(context.Context, *connect.Request[v1.SetContainerLocationRequest]) (*connect.Response[v1.SetContainerLocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.LocationService.SetContainerLocation is not implemented"))
}

func (UnimplementedLocationServiceHandler) RetailSupplyReport(context.Context, *connect.Request[v1.RetailSupplyReportRequest]) (*connect.Response[v1.RetailSupplyReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.LocationService.RetailSupplyReport is not implemented"))
}
