// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: stillhouse/v1/removal.proto

package stillhousev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gallowaysoftware/stillhouse/backend/internal/genpb/stillhouse/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RemovalServiceName is the fully-qualified name of the RemovalService service.
	RemovalServiceName = "stillhouse.v1.RemovalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RemovalServiceCreateRemovalProcedure is the fully-qualified name of the RemovalService's
	// CreateRemoval RPC.
	RemovalServiceCreateRemovalProcedure = "/stillhouse.v1.RemovalService/CreateRemoval"
	// RemovalServiceListRemovalsProcedure is the fully-qualified name of the RemovalService's
	// ListRemovals RPC.
	RemovalServiceListRemovalsProcedure = "/stillhouse.v1.RemovalService/ListRemovals"
	// RemovalServiceVoidRemovalProcedure is the fully-qualified name of the RemovalService's
	// VoidRemoval RPC.
	RemovalServiceVoidRemovalProcedure = "/stillhouse.v1.RemovalService/VoidRemoval"
	// RemovalServiceRecordPackagedReturnProcedure is the fully-qualified name of the RemovalService's
	// RecordPackagedReturn RPC.
	RemovalServiceRecordPackagedReturnProcedure = "/stillhouse.v1.RemovalService/RecordPackagedReturn"
	// RemovalServiceListPackagedReturnsProcedure is the fully-qualified name of the RemovalService's
	// ListPackagedReturns RPC.
	RemovalServiceListPackagedReturnsProcedure = "/stillhouse.v1.RemovalService/ListPackagedReturns"
	// RemovalServiceVoidPackagedReturnProcedure is the fully-qualified name of the RemovalService's
	// VoidPackagedReturn RPC.
	RemovalServiceVoidPackagedReturnProcedure = "/stillhouse.v1.RemovalService/VoidPackagedReturn"
)

// RemovalServiceClient is a client for the stillhouse.v1.RemovalService service.
type RemovalServiceClient interface {
	CreateRemoval(context.Context, *connect.Request[v1.CreateRemovalRequest]) (*connect.Response[v1.CreateRemovalResponse], error)
	ListRemovals(context.Context, *connect.Request[v1.ListRemovalsRequest]) (*connect.Response[v1.ListRemovalsResponse], error)
	VoidRemoval(context.Context, *connect.Request[v1.VoidRemovalRequest]) (*connect.Response[v1.VoidRemovalResponse], error)
	// Product coming back from the duty-paid market. It restocks and
	// credits; it does not relieve duty. See PackagedReturnCondition.
	RecordPackagedReturn(context.Context, *connect.Request[v1.RecordPackagedReturnRequest]) (*connect.Response[v1.RecordPackagedReturnResponse], error)
	ListPackagedReturns(context.Context, *connect.Request[v1.ListPackagedReturnsRequest]) (*connect.Response[v1.ListPackagedReturnsResponse], error)
	VoidPackagedReturn(context.Context, *connect.Request[v1.VoidPackagedReturnRequest]) (*connect.Response[v1.VoidPackagedReturnResponse], error)
}

// NewRemovalServiceClient constructs a client for the stillhouse.v1.RemovalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRemovalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RemovalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	removalServiceMethods := v1.File_stillhouse_v1_removal_proto.Services().ByName("RemovalService").Methods()
	return &removalServiceClient{
		createRemoval: connect.NewClient[v1.CreateRemovalRequest, v1.CreateRemovalResponse](
			httpClient,
			baseURL+RemovalServiceCreateRemovalProcedure,
			connect.WithSchema(removalServiceMethods.ByName("CreateRemoval")),
			connect.WithClientOptions(opts...),
		),
		listRemovals: connect.NewClient[v1.ListRemovalsRequest, v1.ListRemovalsResponse](
			httpClient,
			baseURL+RemovalServiceListRemovalsProcedure,
			connect.WithSchema(removalServiceMethods.ByName("ListRemovals")),
			connect.WithClientOptions(opts...),
		),
		voidRemoval: connect.NewClient[v1.VoidRemovalRequest, v1.VoidRemovalResponse](
			httpClient,
			baseURL+RemovalServiceVoidRemovalProcedure,
			connect.WithSchema(removalServiceMethods.ByName("VoidRemoval")),
			connect.WithClientOptions(opts...),
		),
		recordPackagedReturn: connect.NewClient[v1.RecordPackagedReturnRequest, v1.RecordPackagedReturnResponse](
			httpClient,
			baseURL+RemovalServiceRecordPackagedReturnProcedure,
			connect.WithSchema(removalServiceMethods.ByName("RecordPackagedReturn")),
			connect.WithClientOptions(opts...),
		),
		listPackagedReturns: connect.NewClient[v1.ListPackagedReturnsRequest, v1.ListPackagedReturnsResponse](
			httpClient,
			baseURL+RemovalServiceListPackagedReturnsProcedure,
			connect.WithSchema(removalServiceMethods.ByName("ListPackagedReturns")),
			connect.WithClientOptions(opts...),
		),
		voidPackagedReturn: connect.NewClient[v1.VoidPackagedReturnRequest, v1.VoidPackagedReturnResponse](
			httpClient,
			baseURL+RemovalServiceVoidPackagedReturnProcedure,
			connect.WithSchema(removalServiceMethods.ByName("VoidPackagedReturn")),
			connect.WithClientOptions(opts...),
		),
	}
}

// removalServiceClient implements RemovalServiceClient.
type removalServiceClient struct {
	createRemoval        *connect.Client[v1.CreateRemovalRequest, v1.CreateRemovalResponse]
	listRemovals         *connect.Client[v1.ListRemovalsRequest, v1.ListRemovalsResponse]
	voidRemoval          *connect.Client[v1.VoidRemovalRequest, v1.VoidRemovalResponse]
	recordPackagedReturn *connect.Client[v1.RecordPackagedReturnRequest, v1.RecordPackagedReturnResponse]
	listPackagedReturns  *connect.Client[v1.ListPackagedReturnsRequest, v1.ListPackagedReturnsResponse]
	voidPackagedReturn   *connect.Client[v1.VoidPackagedReturnRequest, v1.VoidPackagedReturnResponse]
}

// CreateRemoval calls stillhouse.v1.RemovalService.CreateRemoval.
func (c *removalServiceClient) CreateRemoval(ctx context.Context, req *connect.Request[v1.CreateRemovalRequest]) (*connect.Response[v1.CreateRemovalResponse], error) {
	return c.createRemoval.CallUnary(ctx, req)
}

// ListRemovals calls stillhouse.v1.RemovalService.ListRemovals.
func (c *removalServiceClient) ListRemovals(ctx context.Context, req *connect.Request[v1.ListRemovalsRequest]) (*connect.Response[v1.ListRemovalsResponse], error) {
	return c.listRemovals.CallUnary(ctx, req)
}

// VoidRemoval calls stillhouse.v1.RemovalService.VoidRemoval.
func (c *removalServiceClient) VoidRemoval(ctx context.Context, req *connect.Request[v1.VoidRemovalRequest]) (*connect.Response[v1.VoidRemovalResponse], error) {
	return c.voidRemoval.CallUnary(ctx, req)
}

// RecordPackagedReturn calls stillhouse.v1.RemovalService.RecordPackagedReturn.
func (c *removalServiceClient) RecordPackagedReturn(ctx context.Context, req *connect.Request[v1.RecordPackagedReturnRequest]) (*connect.Response[v1.RecordPackagedReturnResponse], error) {
	return c.recordPackagedReturn.CallUnary(ctx, req)
}

// ListPackagedReturns calls stillhouse.v1.RemovalService.ListPackagedReturns.
func (c *removalServiceClient) ListPackagedReturns(ctx context.Context, req *connect.Request[v1.ListPackagedReturnsRequest]) (*connect.Response[v1.ListPackagedReturnsResponse], error) {
	return c.listPackagedReturns.CallUnary(ctx, req)
}

// VoidPackagedReturn calls stillhouse.v1.RemovalService.VoidPackagedReturn.
func (c *removalServiceClient) VoidPackagedReturn(ctx context.Context, req *connect.Request[v1.VoidPackagedReturnRequest]) (*connect.Response[v1.VoidPackagedReturnResponse], error) {
	return c.voidPackagedReturn.CallUnary(ctx, req)
}

// RemovalServiceHandler is an implementation of the stillhouse.v1.RemovalService service.
type RemovalServiceHandler interface {
	CreateRemoval(context.Context, *connect.Request[v1.CreateRemovalRequest]) (*connect.Response[v1.CreateRemovalResponse], error)
	ListRemovals(context.Context, *connect.Request[v1.ListRemovalsRequest]) (*connect.Response[v1.ListRemovalsResponse], error)
	VoidRemoval(context.Context, *connect.Request[v1.VoidRemovalRequest]) (*connect.Response[v1.VoidRemovalResponse], error)
	// Product coming back from the duty-paid market. It restocks and
	// credits; it does not relieve duty. See PackagedReturnCondition.
	RecordPackagedReturn(context.Context, *connect.Request[v1.RecordPackagedReturnRequest]) (*connect.Response[v1.RecordPackagedReturnResponse], error)
	ListPackagedReturns(context.Context, *connect.Request[v1.ListPackagedReturnsRequest]) (*connect.Response[v1.ListPackagedReturnsResponse], error)
	VoidPackagedReturn(context.Context, *connect.Request[v1.VoidPackagedReturnRequest]) (*connect.Response[v1.VoidPackagedReturnResponse], error)
}

// NewRemovalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRemovalServiceHandler(svc RemovalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	removalServiceMethods := v1.File_stillhouse_v1_removal_proto.Services().ByName("RemovalService").Methods()
	removalServiceCreateRemovalHandler := connect.NewUnaryHandler(
		RemovalServiceCreateRemovalProcedure,
		svc.CreateRemoval,
		connect.WithSchema(removalServiceMethods.ByName("CreateRemoval")),
		connect.WithHandlerOptions(opts...),
	)
	removalServiceListRemovalsHandler := connect.NewUnaryHandler(
		RemovalServiceListRemovalsProcedure,
		svc.ListRemovals,
		connect.WithSchema(removalServiceMethods.ByName("ListRemovals")),
		connect.WithHandlerOptions(opts...),
	)
	removalServiceVoidRemovalHandler := connect.NewUnaryHandler(
		RemovalServiceVoidRemovalProcedure,
		svc.VoidRemoval,
		connect.WithSchema(removalServiceMethods.ByName("VoidRemoval")),
		connect.WithHandlerOptions(opts...),
	)
	removalServiceRecordPackagedReturnHandler := connect.NewUnaryHandler(
		RemovalServiceRecordPackagedReturnProcedure,
		svc.RecordPackagedReturn,
		connect.WithSchema(removalServiceMethods.ByName("RecordPackagedReturn")),
		connect.WithHandlerOptions(opts...),
	)
	removalServiceListPackagedReturnsHandler := connect.NewUnaryHandler(
		RemovalServiceListPackagedReturnsProcedure,
		svc.ListPackagedReturns,
		connect.WithSchema(removalServiceMethods.ByName("ListPackagedReturns")),
		connect.WithHandlerOptions(opts...),
	)
	removalServiceVoidPackagedReturnHandler := connect.NewUnaryHandler(
		RemovalServiceVoidPackagedReturnProcedure,
		svc.VoidPackagedReturn,
		connect.WithSchema(removalServiceMethods.ByName("VoidPackagedReturn")),
		connect.WithHandlerOptions(opts...),
	)
	return "/stillhouse.v1.RemovalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RemovalServiceCreateRemovalProcedure:
			removalServiceCreateRemovalHandler.ServeHTTP(w, r)
		case RemovalServiceListRemovalsProcedure:
			removalServiceListRemovalsHandler.ServeHTTP(w, r)
		case RemovalServiceVoidRemovalProcedure:
			removalServiceVoidRemovalHandler.ServeHTTP(w, r)
		case RemovalServiceRecordPackagedReturnProcedure:
			removalServiceRecordPackagedReturnHandler.ServeHTTP(w, r)
		case RemovalServiceListPackagedReturnsProcedure:
			removalServiceListPackagedReturnsHandler.ServeHTTP(w, r)
		case RemovalServiceVoidPackagedReturnProcedure:
			removalServiceVoidPackagedReturnHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRemovalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRemovalServiceHandler struct{}

func (UnimplementedRemovalServiceHandler) CreateRemoval(context.Context, *connect.Request[v1.CreateRemovalRequest]) (*connect.Response[v1.CreateRemovalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.CreateRemoval is not implemented"))
}

func (UnimplementedRemovalServiceHandler) ListRemovals(context.Context, *connect.Request[v1.ListRemovalsRequest]) (*connect.Response[v1.ListRemovalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.ListRemovals is not implemented"))
}

func (UnimplementedRemovalServiceHandler) VoidRemoval(context.Context, *connect.Request[v1.VoidRemovalRequest]) (*connect.Response[v1.VoidRemovalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.VoidRemoval is not implemented"))
}

func (UnimplementedRemovalServiceHandler) RecordPackagedReturn(context.Context, *connect.Request[v1.RecordPackagedReturnRequest]) (*connect.Response[v1.RecordPackagedReturnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.RecordPackagedReturn is not implemented"))
}

func (UnimplementedRemovalServiceHandler) ListPackagedReturns(context.Context, *connect.Request[v1.ListPackagedReturnsRequest]) (*connect.Response[v1.ListPackagedReturnsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.ListPackagedReturns is not implemented"))
}

func (UnimplementedRemovalServiceHandler) VoidPackagedReturn(context.Context, *connect.Request[v1.VoidPackagedReturnRequest]) (*connect.Response[v1.VoidPackagedReturnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stillhouse.v1.RemovalService.VoidPackagedReturn is not implemented"))
}
